/**
 * Mapping des descriptions en anglais extraites des données statiques
 * Mappé par nameEn pour correspondre aux SKILLS_DEFINITIONS
 */

export const SKILLS_DESCRIPTIONS_EN: Record<string, string> = {
  // Agility Skills
  "Catch": "This player may re-roll a failed Agility test when attempting to catch the ball.",
  "Diving Catch": "This player may attempt to catch the ball if a pass, throw-in or kick-off causes it to land in a square within their Tackle Zone after scattering or deviating. This Skill does not allow this player to attempt to catch the ball if it bounces into a square within their Tackle Zone. Additionally, this player may apply a +1 modifier to any attempt to catch an accurate pass if they occupy the target square.",
  "Diving Tackle": "Should an active opposition player that is attempting to Dodge, Jump or Leap in order to vacate a square in which they are being Marked by this player pass their Agility test, you may declare that this player will use this Skill. Your opponent must immediately subtract 2 from the result of the Agility test. This player is then Placed Prone in the square vacated by the opposition player.",
  "Dodge": "Once per team turn, during their activation, this player may re-roll a failed Agility test when attempting to Dodge. Additionally, this player may choose to use this Skill when they are the target of a Block action and a Stumble result is applied against them.",
  "Defensive": "During your opponent's team turn (but not during your own team turn), any opposition players being Marked by this player cannot use the Guard skill.",
  "Sure Feet": "Once per team turn, during their activation, this player may re-roll the D6 when attempting to Rush.",
  "Jump Up": "If this player is Prone they may stand up for free. Additionally, if this player is Prone when activated, they may attempt to Jump Up and perform a Block action.",
  "Leap": "During their movement, instead of jumping over a single square that is occupied by a Prone or Stunned player, a player with this Skill may choose to Leap over any single adjacent square, including unoccupied squares and squares occupied by Standing players.",
  "Safe Pair of Hands": "If this player is Knocked Down or Placed Prone (but not if they Fall Over) whilst in possession of the ball, the ball does not bounce. Instead, you may place the ball in an unoccupied square adjacent to the one this player occupies when they become Prone.",
  "Sidestep": "If this player is pushed back for any reason, they are not moved into a square chosen by the opposing coach. Instead you may choose any unoccupied square adjacent to this player.",
  "Sneaky Git": "When this player performs a Foul action, they are not Sent-off for committing a Foul should they roll a natural double on the Armour roll. Additionally, the activation of this player does not have to end once the Foul has been committed.",
  "Sprint": "When this player performs any action that includes movement, they may attempt to Rush three times, rather than the usual two.",
  
  // General Skills
  "Block": "When a Both Down result is applied during a Block action, this player may choose to ignore it and not be Knocked Down.",
  "Dauntless": "When this player performs a Block action, if the nominated target has a higher Strength characteristic than this player before counting offensive or defensive assists but after applying any other modifiers, roll a D6 and add this player's Strength characteristic to the result.",
  "Dirty Player (+1)": "When this player commits a Foul action, either the Armour roll or Injury roll made against the victim may be modified by the amount shown in brackets.",
  "Dirty Player (+2)": "When this player commits a Foul action, either the Armour roll or Injury roll made against the victim may be modified by the amount shown in brackets.",
  "Fend": "If this player is pushed back as the result of any block dice result being applied against them, they may choose to prevent the player that pushed them back from following-up.",
  "Frenzy": "Every time this player performs a Block action, they must follow-up if the target is pushed back and if they are able. If the target is still Standing after being pushed back, and if this player was able to follow-up, this player must then perform a second Block action against the same target.",
  "Kick": "If this player is nominated to be the kicking player during a kick-off, you may choose to halve the result of the D6 to determine the number of squares that the ball deviates, rounding any fractions down.",
  "Pro": "During their activation, this player may attempt to re-roll one dice. This dice may have been rolled either as a single dice roll, as part of a multiple dice roll or as part of a dice pool, but cannot be a dice that was rolled as part of an Armour, Injury or Casualty roll.",
  "Shadowing": "This player can use this Skill when an opposition player they are Marking voluntarily moves out of a square within this player's Tackle Zone.",
  "Strip Ball": "When this player targets an opposition player that is in possession of the ball with a Block action, choosing to apply a Push Back result will cause that player to drop the ball in the square they are pushed back into.",
  "Sure Hands": "This player may re-roll any failed attempt to pick up the ball. In addition, the Strip Ball skill cannot be used against a player with this Skill.",
  "Tackle": "When an active opposition player attempts to Dodge from a square in which they were being Marked by one or more players on your team with this Skill, that player cannot use the Dodge skill.",
  "Wrestle": "This player may use this Skill when a Both Down result is applied, either when they perform a Block action or when they are the target of a Block action.",
  
  // Mutations
  "Big Hand": "This player may ignore any modifier(s) for being Marked or for Pouring Rain weather conditions when they attempt to pick up the ball.",
  "Claws": "When you make an Armour roll against an opposition player that was Knocked Down as the result of a Block action performed by this player, a roll of 8+ before applying any modifiers will break their armour, regardless of their actual Armour Value.",
  "Disturbing Presence": "When an opposition player performs either a Pass action, a Throw Team-mate action or a Throw Bomb Special action, or attempts to either interfere with a pass or to catch the ball, they must apply a -1 modifier to the test for each player on your team with this Skill that is within three squares of them.",
  "Extra Arms": "This player may apply a +1 modifier when they attempt to pick up or catch the ball, or when they attempt to interfere with a pass.",
  "Foul Appearance": "When an opposition player declares a Block action targeting this player, or any Special action that targets this player, their coach must first roll a D6, even if this player has lost their Tackle Zone. On a roll of 1, the player cannot perform the declared action and the action is wasted.",
  "Horns": "When this player performs a Block action as part of a Blitz action (but not on its own), you may apply a +1 modifier to this player's Strength characteristic.",
  "Iron Hard Skin": "The Claws skill cannot be used when making an Armour roll against this player. Opposing players cannot modify any Armour rolls made against this player.",
  "Monstrous Mouth": "This player may re-roll any failed attempt to catch the ball. In addition, the Strip Ball skill cannot be used against this player.",
  "Prehensile Tail": "When an active opposition player attempts to Dodge, Jump or Leap in order to vacate a square in which they are being Marked by this player, there is an additional -1 modifier applied to the active player's Agility test.",
  "Tentacles": "This player can use this Skill when an opposition player they are Marking voluntarily moves out of a square within this player's Tackle Zone.",
  "Two Heads": "This player may apply a +1 modifier to the Agility test when they attempt to Dodge.",
  "Very Long Legs": "This player may reduce any negative modifier applied to the Agility test when they attempt to Jump over a Prone or Stunned player by 1, to a minimum of -1.",
  
  // Passing Skills
  "Accurate": "When this player performs a Quick Pass action or a Short Pass action, you may apply an additional +1 modifier to the Passing Ability test.",
  "Cannoneer": "When this player performs a Long Pass action or a Long Bomb Pass action, you may apply an additional +1 modifier to the Passing Ability test.",
  "Cloud Burster": "When this player performs a Long Pass action or a Long Bomb Pass action, you may choose to make the opposing coach re-roll a successful attempt to interfere with the pass.",
  "Dump-off": "If this player is nominated as the target of a Block action and if they are in possession of the ball, they may immediately perform a Quick Pass action, interrupting the activation of the opposition player performing the Block action.",
  "Fumblerooskie": "When this player performs a Move or Blitz action whilst in possession of the ball, they may choose to 'drop' the ball.",
  "Hail Mary Pass": "When this player performs a Pass action, the target square can be anywhere on the pitch and the range ruler does not need to be used.",
  "Leader": "A team which has one or more players with this Skill gains a single extra team re-roll, called a Leader re-roll.",
  "Nerves of Steel": "This player may ignore any modifier(s) for being Marked when they attempt to perform a Pass action, attempt to catch the ball or attempt to interfere with a pass.",
  "On the Ball": "This player may move up to three squares (regardless of their MA), following all of the normal movement rules, when the opposing coach declares that one of their players is going to perform a Pass action.",
  "Pass": "This player may re-roll a failed Passing Ability test when performing a Pass action.",
  "Running Pass": "If this player performs a Quick Pass action, their activation does not have to end once the pass is resolved.",
  "Safe Pass": "Should this player fumble a Pass action, the ball is not dropped, does not bounce from the square this player occupies, and no Turnover is caused.",
  
  // Strength Skills
  "Arm Bar": "If an opposition player Falls Over as the result of failing their Agility test when attempting to Dodge, Jump or Leap out of a square in which they were being Marked by this player, you may apply a +1 modifier to either the Armour roll or Injury roll.",
  "Brawler": "When this player performs a Block action on its own (but not as part of a Blitz action), this player may re-roll a single Both Down result.",
  "Break Tackle": "Once during their activation, after making an Agility test in order to Dodge, this player may modify the dice roll by +1 if their Strength characteristic is 4 or less, or by +2 if their Strength characteristic is 5 or more.",
  "Grab": "When this player performs a Block action, using this Skill prevents the target of the Block action from using the Sidestep skill.",
  "Guard": "This player can offer both offensive and defensive assists regardless of how many opposition players are Marking them.",
  "Juggernaut": "When this player performs a Block action as part of a Blitz action (but not on its own), they may choose to treat a Both Down result as a Push Back result.",
  "Mighty Blow (+1)": "When an opposition player is Knocked Down as the result of a Block action performed by this player, you may modify either the Armour roll or Injury roll by the amount shown in brackets.",
  "Mighty Blow (+2)": "When an opposition player is Knocked Down as the result of a Block action performed by this player, you may modify either the Armour roll or Injury roll by the amount shown in brackets.",
  "Multiple Block": "When this player performs a Block action on its own (but not as part of a Blitz action), they may choose to perform two Block actions, each targeting a different player they are Marking.",
  "Pile Driver": "When an opposition player is Knocked Down by this player as the result of a Block action, this player may immediately commit a free Foul action against the Knocked Down player.",
  "Stand Firm": "This player may choose not to be pushed back, either as the result of a Block action made against them or by a chain-push.",
  "Strong Arm": "This player may apply a +1 modifier to any Passing Ability test rolls they make when performing a Throw Team-mate action.",
  "Thick Skull": "When an Injury roll is made against this player, they can only be KO'd on a roll of 9, and will treat a roll of 8 as a Stunned result.",
  
  // Traits
  "Animal Savagery": "When this player is activated, immediately after declaring the action they will perform but before performing the action, roll a D6, applying a +2 modifier to the dice roll if you declared the player would perform a Block or Blitz action.",
  "Animosity (X)": "This player is jealous of and dislikes certain other players on their team, as shown in brackets after the name of the Skill on this player's profile.",
  "Always Hungry": "If this player wishes to perform a Throw Team-mate action, roll a D6 after they have finished moving, but before they throw their Team-mate.",
  "Ball and Chain": "When this player is activated, the only action they may perform is a 'Ball & Chain Move' Special action.",
  "Bombardier": "When activated and if they are Standing, this player can perform a 'Throw Bomb' Special action.",
  "Bone Head": "When this player is activated, immediately after declaring the action they will perform but before performing the action, roll a D6.",
  "Chainsaw": "Instead of performing a Block action, this player may perform a 'Chainsaw Attack' Special action.",
  "Decay": "If this player suffers a Casualty result on the Injury table, there is a +1 modifier applied to all rolls made against this player on the Casualty table.",
  "Hypnotic Gaze": "During their activation, this player may perform a 'Hypnotic Gaze' Special action.",
  "Kick Team-mate": "Once per team turn, in addition to another player performing either a Pass or a Throw Team-mate action, a single player with this Trait on the active team can perform a 'Kick Team-mate' Special action.",
  "Loner (X+)": "If this player wishes to use a team re-roll, roll a D6. If you roll equal to or higher than the target number shown in brackets, this player may use the team re-roll as normal.",
  "No Hands": "This player is unable to take possession of the ball. They may not attempt to pick it up, to catch it, or attempt to interfere with a pass.",
  "Plague Ridden": "Once per game, if an opposition player with a Strength characteristic of 4 or less that does not have the Decay, Regeneration or Stunty traits suffers a Casualty result of 15-16, DEAD as the result of a Block action performed or a Foul action committed by a player with this Trait that belongs to your team.",
  "Pogo Stick": "During their movement, instead of jumping over a single square that is occupied by a Prone or Stunned player, a player with this Trait may choose to Leap over any single adjacent square.",
  "Projectile Vomit": "Instead of performing a Block action, this player may perform a 'Projectile Vomit' Special action.",
  "Really Stupid": "When this player is activated, immediately after declaring the action they will perform but before performing the action, roll a D6, applying a +2 modifier to the dice roll if this player is currently adjacent to one or more Standing Team-mates that do not have this Trait.",
  "Regeneration": "After a Casualty roll has been made against this player, roll a D6. On a roll of 4+, the Casualty roll is discarded without effect and the player is placed in the Reserves box rather than the Casualty box of their team dugout.",
  "Right Stuff": "If this player also has a Strength characteristic of 3 or less, they can be thrown by a Team-mate with the Throw Team-mate skill.",
  "Secret Weapon": "When a drive in which this player took part ends, even if this player was not on the pitch at the end of the drive, this player will be Sent-off for committing a Foul.",
  "Stab": "Instead of performing a Block action, this player may perform a 'Stab' Special action.",
  "Stunty": "When this player makes an Agility test in order to Dodge, they ignore any -1 modifiers for being Marked in the square they have moved into, unless they also have either the Bombardier trait, the Chainsaw trait or the Swoop trait.",
  "Swarming": "During each Start of Drive sequence, after Step 2 but before Step 3, you may remove D3 players with this Trait from the Reserves box of your dugout and set them up on the pitch.",
  "Swoop": "If this player is thrown by a Team-mate, they do not scatter before landing as they normally would.",
  "Take Root": "When this player is activated, immediately after declaring the action they will perform but before performing the action, roll a D6.",
  "Throw Team-mate": "If this player also has a Strength characteristic of 5 or more, they may perform a Throw Team-mate action.",
  "Titchy": "This player may apply a +1 modifier to any Agility tests they make in order to Dodge.",
  "Timmm-ber!": "If this player has a Movement Allowance of 2 or less, apply a +1 modifier to the dice roll when they attempt to stand up for each Open, Standing Team-mate they are currently adjacent to.",
  "Unchannelled Fury": "When this player is activated, immediately after declaring the action they will perform but before performing the action, roll a D6, applying a +2 modifier to the dice roll if you declared the player would perform a Block or Blitz action.",
  
  // Extraordinary
  "Hit and Run": "After a player with this Trait performs a Block action, they may immediately move one free square ignoring Tackle Zones so long as they are still Standing.",
  "Drunkard": "This player suffers a -1 penalty to the dice roll when attempting to Rush.",
  "Pick-me-up": "At the end of the opposition's team turn, roll a D6 for each Prone, non-Stunned team-mate within three squares of a standing player with this Trait.",
  "Bloodlust (X+)": "To keep control of their wits, Vampires need a supply of fresh blood. Whenever a player with this trait activates, after declaring their action, they must roll a D6.",
  "My Ball": "A player with this Trait may not willingly give up the ball when in possession of it, and so may not make Pass actions, Hand-off actions, or use any other Skill or Trait that would allow them to relinquish possession of the ball.",
  "Trickster": "When this player is about to be hit by a Block action or a Special action that replaces a Block action, before determining how many dice are rolled, they may be removed from the pitch and placed in any other unoccupied square adjacent to the player performing the Block action.",
  "Breathe Fire": "Once per activation, instead of performing a Block action, this player may perform a Breathe Fire Special action.",
};

