
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
Prisma.prismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  name: 'name',
  coachName: 'coachName',
  firstName: 'firstName',
  lastName: 'lastName',
  dateOfBirth: 'dateOfBirth',
  role: 'role',
  roles: 'roles',
  patreon: 'patreon',
  kofiLinkCode: 'kofiLinkCode',
  discordUserId: 'discordUserId',
  supporterTier: 'supporterTier',
  supporterActiveUntil: 'supporterActiveUntil',
  totalDonatedCentsByCurrency: 'totalDonatedCentsByCurrency',
  privateProfile: 'privateProfile',
  valid: 'valid',
  bannedAt: 'bannedAt',
  bannedUntil: 'bannedUntil',
  banReason: 'banReason',
  mustChangePassword: 'mustChangePassword',
  deletedAt: 'deletedAt',
  deletionReason: 'deletionReason',
  lastLoginAt: 'lastLoginAt',
  leaderboardStatus: 'leaderboardStatus',
  leaderboardStatusReason: 'leaderboardStatusReason',
  leaderboardStatusUpdatedAt: 'leaderboardStatusUpdatedAt',
  leaderboardStatusUpdatedBy: 'leaderboardStatusUpdatedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  eloRating: 'eloRating'
};

exports.Prisma.EloSnapshotScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  rating: 'rating',
  delta: 'delta',
  matchId: 'matchId',
  recordedAt: 'recordedAt'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  jti: 'jti',
  userId: 'userId',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  createdAt: 'createdAt'
};

exports.Prisma.KofiTransactionScalarFieldEnum = {
  id: 'id',
  kofiTransactionId: 'kofiTransactionId',
  messageId: 'messageId',
  kofiTimestamp: 'kofiTimestamp',
  type: 'type',
  isSubscriptionPayment: 'isSubscriptionPayment',
  isFirstSubscriptionPayment: 'isFirstSubscriptionPayment',
  tierName: 'tierName',
  amountCents: 'amountCents',
  currency: 'currency',
  fromName: 'fromName',
  email: 'email',
  discordUserId: 'discordUserId',
  message: 'message',
  userId: 'userId',
  matchedVia: 'matchedVia',
  rawPayload: 'rawPayload',
  receivedAt: 'receivedAt'
};

exports.Prisma.TutorialCompletionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  lessonSlug: 'lessonSlug',
  completedAt: 'completedAt'
};

exports.Prisma.UserAchievementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  slug: 'slug',
  unlockedAt: 'unlockedAt'
};

exports.Prisma.FriendshipScalarFieldEnum = {
  id: 'id',
  requesterId: 'requesterId',
  receiverId: 'receiverId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureFlagScalarFieldEnum = {
  id: 'id',
  key: 'key',
  description: 'description',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeatureFlagUserScalarFieldEnum = {
  id: 'id',
  flagId: 'flagId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.MatchScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  status: 'status',
  seed: 'seed',
  creatorId: 'creatorId',
  currentTurnUserId: 'currentTurnUserId',
  lastMoveAt: 'lastMoveAt',
  forfeitedAt: 'forfeitedAt',
  forfeitWinnerSide: 'forfeitWinnerSide',
  forfeitReason: 'forfeitReason',
  cancelledAt: 'cancelledAt',
  cancelReason: 'cancelReason',
  aiOpponent: 'aiOpponent',
  aiDifficulty: 'aiDifficulty',
  aiTeamSide: 'aiTeamSide',
  aiUserId: 'aiUserId',
  leagueSeasonId: 'leagueSeasonId',
  leagueRoundId: 'leagueRoundId',
  leaguePairingId: 'leaguePairingId',
  leagueScoredAt: 'leagueScoredAt'
};

exports.Prisma.TurnScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  number: 'number',
  payload: 'payload',
  createdAt: 'createdAt'
};

exports.Prisma.TeamSelectionScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  userId: 'userId',
  team: 'team',
  teamId: 'teamId',
  createdAt: 'createdAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  name: 'name',
  roster: 'roster',
  ruleset: 'ruleset',
  createdAt: 'createdAt',
  treasury: 'treasury',
  rerolls: 'rerolls',
  cheerleaders: 'cheerleaders',
  assistants: 'assistants',
  apothecary: 'apothecary',
  dedicatedFans: 'dedicatedFans',
  teamValue: 'teamValue',
  currentValue: 'currentValue',
  initialBudget: 'initialBudget'
};

exports.Prisma.TeamPlayerScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  position: 'position',
  number: 'number',
  ma: 'ma',
  st: 'st',
  ag: 'ag',
  pa: 'pa',
  av: 'av',
  skills: 'skills',
  spp: 'spp',
  totalTouchdowns: 'totalTouchdowns',
  totalCasualties: 'totalCasualties',
  totalCompletions: 'totalCompletions',
  totalInterceptions: 'totalInterceptions',
  totalMvpAwards: 'totalMvpAwards',
  matchesPlayed: 'matchesPlayed',
  nigglingInjuries: 'nigglingInjuries',
  maReduction: 'maReduction',
  stReduction: 'stReduction',
  agReduction: 'agReduction',
  paReduction: 'paReduction',
  avReduction: 'avReduction',
  missNextMatch: 'missNextMatch',
  advancements: 'advancements',
  dead: 'dead',
  diedAt: 'diedAt'
};

exports.Prisma.TeamStarPlayerScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  starPlayerSlug: 'starPlayerSlug',
  cost: 'cost',
  hiredAt: 'hiredAt'
};

exports.Prisma.RosterScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  ruleset: 'ruleset',
  name: 'name',
  nameEn: 'nameEn',
  descriptionFr: 'descriptionFr',
  descriptionEn: 'descriptionEn',
  budget: 'budget',
  tier: 'tier',
  regionalRules: 'regionalRules',
  specialRules: 'specialRules',
  naf: 'naf',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SkillScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  ruleset: 'ruleset',
  nameFr: 'nameFr',
  nameEn: 'nameEn',
  description: 'description',
  descriptionEn: 'descriptionEn',
  category: 'category',
  isElite: 'isElite',
  isPassive: 'isPassive',
  isModified: 'isModified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PositionScalarFieldEnum = {
  id: 'id',
  rosterId: 'rosterId',
  slug: 'slug',
  displayName: 'displayName',
  cost: 'cost',
  min: 'min',
  max: 'max',
  ma: 'ma',
  st: 'st',
  ag: 'ag',
  pa: 'pa',
  av: 'av',
  keywords: 'keywords',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PositionSkillScalarFieldEnum = {
  id: 'id',
  positionId: 'positionId',
  skillId: 'skillId'
};

exports.Prisma.CupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  creatorId: 'creatorId',
  ruleset: 'ruleset',
  validated: 'validated',
  isPublic: 'isPublic',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  winPoints: 'winPoints',
  drawPoints: 'drawPoints',
  lossPoints: 'lossPoints',
  forfeitPoints: 'forfeitPoints',
  touchdownPoints: 'touchdownPoints',
  blockCasualtyPoints: 'blockCasualtyPoints',
  foulCasualtyPoints: 'foulCasualtyPoints',
  passPoints: 'passPoints'
};

exports.Prisma.CupParticipantScalarFieldEnum = {
  id: 'id',
  cupId: 'cupId',
  teamId: 'teamId',
  createdAt: 'createdAt'
};

exports.Prisma.MatchQueueScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  teamId: 'teamId',
  teamValue: 'teamValue',
  status: 'status',
  matchId: 'matchId',
  joinedAt: 'joinedAt'
};

exports.Prisma.LocalMatchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  isPublic: 'isPublic',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  creatorId: 'creatorId',
  teamAId: 'teamAId',
  teamBId: 'teamBId',
  cupId: 'cupId',
  shareToken: 'shareToken',
  teamAOwnerValidated: 'teamAOwnerValidated',
  teamBOwnerValidated: 'teamBOwnerValidated',
  gameState: 'gameState',
  scoreTeamA: 'scoreTeamA',
  scoreTeamB: 'scoreTeamB',
  aiOpponent: 'aiOpponent',
  aiDifficulty: 'aiDifficulty',
  aiTeamSide: 'aiTeamSide'
};

exports.Prisma.LocalMatchActionScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  half: 'half',
  turn: 'turn',
  actionType: 'actionType',
  playerId: 'playerId',
  playerName: 'playerName',
  playerTeam: 'playerTeam',
  opponentId: 'opponentId',
  opponentName: 'opponentName',
  diceResult: 'diceResult',
  fumble: 'fumble',
  playerState: 'playerState',
  armorBroken: 'armorBroken',
  opponentState: 'opponentState',
  passType: 'passType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeagueScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  creatorId: 'creatorId',
  ruleset: 'ruleset',
  status: 'status',
  isPublic: 'isPublic',
  maxParticipants: 'maxParticipants',
  allowedRosters: 'allowedRosters',
  winPoints: 'winPoints',
  drawPoints: 'drawPoints',
  lossPoints: 'lossPoints',
  forfeitPoints: 'forfeitPoints',
  tieBreakRules: 'tieBreakRules',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeagueSeasonScalarFieldEnum = {
  id: 'id',
  leagueId: 'leagueId',
  seasonNumber: 'seasonNumber',
  name: 'name',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  theme: 'theme',
  themeYear: 'themeYear',
  playoffSize: 'playoffSize',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeagueParticipantScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  teamId: 'teamId',
  seasonElo: 'seasonElo',
  wins: 'wins',
  draws: 'draws',
  losses: 'losses',
  points: 'points',
  touchdownsFor: 'touchdownsFor',
  touchdownsAgainst: 'touchdownsAgainst',
  casualtiesFor: 'casualtiesFor',
  casualtiesAgainst: 'casualtiesAgainst',
  status: 'status',
  joinedAt: 'joinedAt',
  mecenePlayed: 'mecenePlayed',
  mecenePlayedAt: 'mecenePlayedAt'
};

exports.Prisma.LeagueRoundScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  roundNumber: 'roundNumber',
  name: 'name',
  status: 'status',
  kind: 'kind',
  bracketSlot: 'bracketSlot',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeaguePairingScalarFieldEnum = {
  id: 'id',
  roundId: 'roundId',
  homeParticipantId: 'homeParticipantId',
  awayParticipantId: 'awayParticipantId',
  status: 'status',
  scheduledAt: 'scheduledAt',
  deadlineAt: 'deadlineAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TeamSpecialRuleScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  ruleset: 'ruleset',
  nameFr: 'nameFr',
  nameEn: 'nameEn',
  description: 'description',
  descriptionEn: 'descriptionEn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RegionalLeagueScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  ruleset: 'ruleset',
  nameFr: 'nameFr',
  nameEn: 'nameEn',
  description: 'description',
  descriptionEn: 'descriptionEn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeaguePostMatchSequenceScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  seasonId: 'seasonId',
  status: 'status',
  winningsApplied: 'winningsApplied',
  lastingInjuriesApplied: 'lastingInjuriesApplied',
  advancementsResolved: 'advancementsResolved',
  treasuryDeltaA: 'treasuryDeltaA',
  treasuryDeltaB: 'treasuryDeltaB',
  fanFactorDeltaA: 'fanFactorDeltaA',
  fanFactorDeltaB: 'fanFactorDeltaB',
  pendingChoices: 'pendingChoices',
  createdAt: 'createdAt',
  completedAt: 'completedAt'
};

exports.Prisma.LeagueSeasonAwardScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  championUserId: 'championUserId',
  championTeamId: 'championTeamId',
  awards: 'awards',
  createdAt: 'createdAt'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  email: 'email',
  subject: 'subject',
  message: 'message',
  userAgent: 'userAgent',
  pageUrl: 'pageUrl',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProLeagueScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  branding: 'branding',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProTeamScalarFieldEnum = {
  id: 'id',
  leagueId: 'leagueId',
  slug: 'slug',
  city: 'city',
  name: 'name',
  race: 'race',
  nflFlavor: 'nflFlavor',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  baseTv: 'baseTv',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProTeamRosterScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  position: 'position',
  ma: 'ma',
  st: 'st',
  ag: 'ag',
  pa: 'pa',
  av: 'av',
  skills: 'skills',
  niggling: 'niggling',
  maReduction: 'maReduction',
  stReduction: 'stReduction',
  agReduction: 'agReduction',
  avReduction: 'avReduction',
  status: 'status',
  form: 'form',
  careerStats: 'careerStats',
  spp: 'spp',
  tdCount: 'tdCount',
  casCount: 'casCount',
  compCount: 'compCount',
  mvpCount: 'mvpCount',
  level: 'level',
  tvCached: 'tvCached',
  maBonus: 'maBonus',
  agBonus: 'agBonus',
  paBonus: 'paBonus',
  avBonus: 'avBonus',
  stBonus: 'stBonus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProLeagueSeasonScalarFieldEnum = {
  id: 'id',
  leagueId: 'leagueId',
  year: 'year',
  status: 'status',
  engineVer: 'engineVer',
  driverKind: 'driverKind',
  startsAt: 'startsAt',
  endsAt: 'endsAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProLeagueRoundScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  roundNumber: 'roundNumber',
  status: 'status',
  scheduledAt: 'scheduledAt',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProLeagueMatchScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  roundId: 'roundId',
  homeTeamId: 'homeTeamId',
  awayTeamId: 'awayTeamId',
  status: 'status',
  scheduledAt: 'scheduledAt',
  simulatedAt: 'simulatedAt',
  completedAt: 'completedAt',
  casualtiesAppliedAt: 'casualtiesAppliedAt',
  sppAppliedAt: 'sppAppliedAt',
  isTest: 'isTest',
  driverKindOverride: 'driverKindOverride',
  seed: 'seed',
  engineVer: 'engineVer',
  replayId: 'replayId',
  scoreHome: 'scoreHome',
  scoreAway: 'scoreAway',
  outcome: 'outcome',
  touchdownCount: 'touchdownCount',
  casualtyCount: 'casualtyCount',
  turnoverCount: 'turnoverCount',
  nuffleCount: 'nuffleCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProLeagueStandingsScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  teamId: 'teamId',
  played: 'played',
  wins: 'wins',
  draws: 'draws',
  losses: 'losses',
  points: 'points',
  tdFor: 'tdFor',
  tdAgainst: 'tdAgainst',
  casualtiesFor: 'casualtiesFor',
  casualtiesAgainst: 'casualtiesAgainst',
  form: 'form',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReplayScalarFieldEnum = {
  matchId: 'matchId',
  payload: 'payload',
  highlights: 'highlights',
  durationMs: 'durationMs',
  rawJsonSize: 'rawJsonSize',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProSpectatorFollowScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  proTeamId: 'proTeamId',
  since: 'since',
  createdAt: 'createdAt'
};

exports.Prisma.ProWalletScalarFieldEnum = {
  userId: 'userId',
  crowns: 'crowns',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProTransactionScalarFieldEnum = {
  id: 'id',
  walletId: 'walletId',
  type: 'type',
  amount: 'amount',
  ref: 'ref',
  createdAt: 'createdAt'
};

exports.Prisma.ProBetMarketScalarFieldEnum = {
  id: 'id',
  matchId: 'matchId',
  type: 'type',
  config: 'config',
  status: 'status',
  closesAt: 'closesAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProBetScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  marketId: 'marketId',
  selection: 'selection',
  stake: 'stake',
  oddsAtPlace: 'oddsAtPlace',
  status: 'status',
  payoutAmount: 'payoutAmount',
  clientToken: 'clientToken',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProBetSettlementScalarFieldEnum = {
  id: 'id',
  marketId: 'marketId',
  winningSelection: 'winningSelection',
  totalStake: 'totalStake',
  totalPayout: 'totalPayout',
  betCount: 'betCount',
  settledAt: 'settledAt'
};

exports.Prisma.ProUserBadgeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  badgeCode: 'badgeCode',
  earnedAt: 'earnedAt',
  meta: 'meta'
};

exports.Prisma.ProGazetteArticleScalarFieldEnum = {
  id: 'id',
  date: 'date',
  type: 'type',
  persona: 'persona',
  title: 'title',
  body: 'body',
  relatedTeamIds: 'relatedTeamIds',
  relatedPlayerIds: 'relatedPlayerIds',
  createdAt: 'createdAt'
};

exports.Prisma.ProHallOfFameScalarFieldEnum = {
  id: 'id',
  rosterId: 'rosterId',
  teamSlug: 'teamSlug',
  teamName: 'teamName',
  playerName: 'playerName',
  race: 'race',
  position: 'position',
  ma: 'ma',
  st: 'st',
  ag: 'ag',
  pa: 'pa',
  av: 'av',
  skills: 'skills',
  careerStats: 'careerStats',
  reason: 'reason',
  citation: 'citation',
  inductedAt: 'inductedAt'
};

exports.Prisma.ProHallOfFameDedicationScalarFieldEnum = {
  id: 'id',
  hallOfFameId: 'hallOfFameId',
  userId: 'userId',
  message: 'message',
  costCrowns: 'costCrowns',
  createdAt: 'createdAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  oldValue: 'oldValue',
  newValue: 'newValue',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.EngineComparisonScalarFieldEnum = {
  id: 'id',
  engineVer: 'engineVer',
  homeTeamId: 'homeTeamId',
  awayTeamId: 'awayTeamId',
  matches: 'matches',
  seedOffset: 'seedOffset',
  meanScoreDelta: 'meanScoreDelta',
  p95ScoreDelta: 'p95ScoreDelta',
  maxScoreDelta: 'maxScoreDelta',
  meanTurnoverDelta: 'meanTurnoverDelta',
  meanTouchdownDelta: 'meanTouchdownDelta',
  meanCasualtyDelta: 'meanCasualtyDelta',
  outcomeFlippedCount: 'outcomeFlippedCount',
  divergedPct: 'divergedPct',
  source: 'source',
  createdAt: 'createdAt'
};

exports.Prisma.ProPredictionLeagueScalarFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  joinCode: 'joinCode',
  isPrivate: 'isPrivate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProPredictionLeagueMemberScalarFieldEnum = {
  id: 'id',
  leagueId: 'leagueId',
  userId: 'userId',
  joinedAt: 'joinedAt'
};

exports.Prisma.ProPredictionPickScalarFieldEnum = {
  id: 'id',
  leagueId: 'leagueId',
  userId: 'userId',
  matchId: 'matchId',
  selection: 'selection',
  result: 'result',
  correct: 'correct',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProSurvivorEntryScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  userId: 'userId',
  roundId: 'roundId',
  weekN: 'weekN',
  pickedTeamId: 'pickedTeamId',
  status: 'status',
  result: 'result',
  matchId: 'matchId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.Ruleset = exports.$Enums.Ruleset = {
  season_2: 'season_2',
  season_3: 'season_3'
};

exports.Prisma.ModelName = {
  User: 'User',
  EloSnapshot: 'EloSnapshot',
  RefreshToken: 'RefreshToken',
  KofiTransaction: 'KofiTransaction',
  TutorialCompletion: 'TutorialCompletion',
  UserAchievement: 'UserAchievement',
  Friendship: 'Friendship',
  FeatureFlag: 'FeatureFlag',
  FeatureFlagUser: 'FeatureFlagUser',
  Match: 'Match',
  Turn: 'Turn',
  TeamSelection: 'TeamSelection',
  Team: 'Team',
  TeamPlayer: 'TeamPlayer',
  TeamStarPlayer: 'TeamStarPlayer',
  Roster: 'Roster',
  Skill: 'Skill',
  Position: 'Position',
  PositionSkill: 'PositionSkill',
  Cup: 'Cup',
  CupParticipant: 'CupParticipant',
  MatchQueue: 'MatchQueue',
  LocalMatch: 'LocalMatch',
  LocalMatchAction: 'LocalMatchAction',
  League: 'League',
  LeagueSeason: 'LeagueSeason',
  LeagueParticipant: 'LeagueParticipant',
  LeagueRound: 'LeagueRound',
  LeaguePairing: 'LeaguePairing',
  TeamSpecialRule: 'TeamSpecialRule',
  RegionalLeague: 'RegionalLeague',
  LeaguePostMatchSequence: 'LeaguePostMatchSequence',
  LeagueSeasonAward: 'LeagueSeasonAward',
  Feedback: 'Feedback',
  ProLeague: 'ProLeague',
  ProTeam: 'ProTeam',
  ProTeamRoster: 'ProTeamRoster',
  ProLeagueSeason: 'ProLeagueSeason',
  ProLeagueRound: 'ProLeagueRound',
  ProLeagueMatch: 'ProLeagueMatch',
  ProLeagueStandings: 'ProLeagueStandings',
  Replay: 'Replay',
  ProSpectatorFollow: 'ProSpectatorFollow',
  ProWallet: 'ProWallet',
  ProTransaction: 'ProTransaction',
  ProBetMarket: 'ProBetMarket',
  ProBet: 'ProBet',
  ProBetSettlement: 'ProBetSettlement',
  ProUserBadge: 'ProUserBadge',
  ProGazetteArticle: 'ProGazetteArticle',
  ProHallOfFame: 'ProHallOfFame',
  ProHallOfFameDedication: 'ProHallOfFameDedication',
  AuditLog: 'AuditLog',
  EngineComparison: 'EngineComparison',
  ProPredictionLeague: 'ProPredictionLeague',
  ProPredictionLeagueMember: 'ProPredictionLeagueMember',
  ProPredictionPick: 'ProPredictionPick',
  ProSurvivorEntry: 'ProSurvivorEntry'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
