/**
 * Mots-clés par position — BB Season 3.
 *
 * ⚠️ FICHIER GÉNÉRÉ par scripts/generate-keywords-season3.ts — NE PAS éditer à
 * la main. Source : data/positionnels-bloodbowl-2025.md (parenthèse de la
 * colonne Position, ex: "Elfe, Trois-quart"). Les mots-clés officiels BB2025
 * décrivent la lignée/race et le type de joueur d'une position.
 * Pour régénérer : tsx scripts/generate-keywords-season3.ts --write
 *
 * Format : slug position -> CSV de mots-clés ("Race, Type").
 */

export const KEYWORDS_SEASON3: Record<string, string> = {
  "amazon_guerriere_aigle": "Humain, Trois-quart",
  "amazon_guerriere_jaguar": "Humain, Bloqueur",
  "amazon_guerriere_piranha": "Humain, Blitzer",
  "amazon_guerriere_python": "Humain, Lanceur",
  "black_orc_malabar_gobelin": "Gobelin, Trois-quart",
  "black_orc_orque_noir": "Orque, Bloqueur",
  "black_orc_troll_entraine": "Troll, Gros Bras",
  "bretonnian_chevalier_du_graal": "Humain, Blitzer",
  "bretonnian_ecuyer": "Humain, Trois-quart",
  "bretonnian_lanceur_chevalier": "Humain, Lanceur",
  "bretonnian_receveur_chevalier": "Humain, Receveur",
  "chaos_chosen_bloqueur_elu": "Humain, Bloqueur",
  "chaos_chosen_minotaure": "Minotaure, Gros Bras",
  "chaos_chosen_ogre_du_chaos": "Ogre, Gros Bras",
  "chaos_chosen_trois_quart_homme_bete": "Homme-bête, Trois-quart",
  "chaos_chosen_troll_du_chaos": "Troll, Gros Bras",
  "chaos_dwarf_bloqueur_nain_du_chaos": "Nain, Bloqueur",
  "chaos_dwarf_centaure_taureau": "Nain, Blitzer",
  "chaos_dwarf_forgeflamme": "Nain, Spécial",
  "chaos_dwarf_minotaure": "Minotaure, Gros Bras",
  "chaos_dwarf_surineur_sournois": "Gobelin, Spécial",
  "chaos_dwarf_trois_quart_hobgobelin": "Gobelin, Trois-quart",
  "chaos_renegade_elf_noir_renegat": "Elfe, Trois-quart",
  "chaos_renegade_gobelin_renegat": "Gobelin, Trois-quart",
  "chaos_renegade_lanceur_humain_renegat": "Humain, Lanceur",
  "chaos_renegade_minotaure_renegat": "Minotaure, Gros Bras",
  "chaos_renegade_ogre_renegat": "Ogre, Gros Bras",
  "chaos_renegade_orque_renegat": "Orque, Trois-quart",
  "chaos_renegade_rat_ogre_renegat": "Skaven, Gros Bras",
  "chaos_renegade_skaven_renegat": "Skaven, Trois-quart",
  "chaos_renegade_trois_quart_humain_renegat": "Humain, Trois-quart",
  "chaos_renegade_troll_renegat": "Troll, Gros Bras",
  "dark_elf_assassin_elfe_noir": "Elfe, Spécial",
  "dark_elf_blitzer_elfe_noir": "Elfe, Blitzer",
  "dark_elf_coureur_elfe_noir": "Elfe, Coureur",
  "dark_elf_furie_elfe_noire": "Elfe, Spécial",
  "dark_elf_trois_quart_elfe_noir": "Elfe, Trois-quart",
  "dwarf_blitzer_nain": "Nain, Blitzer",
  "dwarf_coureur_nain": "Nain, Coureur",
  "dwarf_roule_mort": "Nain, Gros Bras, Spécial",
  "dwarf_trois_quart_nain": "Nain, Trois-quart",
  "dwarf_tueur_de_trolls": "Nain, Spécial",
  "elven_union_blitzer_elfe": "Elfe, Blitzer",
  "elven_union_lanceur_elfe": "Elfe, Lanceur",
  "elven_union_receveur_elfe": "Elfe, Receveur",
  "elven_union_trois_quart_elfe": "Elfe, Trois-quart",
  "gnome_belluaire_gnome": "Gnome, Bloqueur",
  "gnome_gnome_illusioniste": "Gnome, Spécial",
  "gnome_homme_arbre": "Homme-Arbre, Gros Bras",
  "gnome_renard_sylvestre": "Animal, Coureur",
  "gnome_trois_quart_gnome": "Gnome, Trois-quart",
  "goblin_bomba": "Gobelin, Spécial",
  "goblin_cingle": "Gobelin, Spécial",
  "goblin_echassier_a_ressort": "Gobelin, Spécial",
  "goblin_fanatique": "Gobelin, Spécial",
  "goblin_gobelin": "Gobelin, Trois-quart",
  "goblin_ouligan": "Gobelin, Spécial",
  "goblin_plongeur_de_la_mort": "Gobelin, Spécial",
  "goblin_troll_entraine": "Troll, Gros Bras",
  "halfling_aspirant_halfling": "Halfling, Trois-quart",
  "halfling_balaise_halfling": "Halfling, Bloqueur",
  "halfling_homme_arbre_de_l_altern": "Homme-Arbre, Gros Bras",
  "halfling_receveur_halfling": "Halfling, Receveur",
  "high_elf_blitzer_haut_elfe": "Elfe, Blitzer",
  "high_elf_lanceur_haut_elfe": "Elfe, Lanceur",
  "high_elf_receveur_haut_elfe": "Elfe, Receveur",
  "high_elf_trois_quart_haut_elfe": "Elfe, Trois-quart",
  "human_aspirant_halfling": "Halfling, Trois-quart",
  "human_blitzer": "Humain, Blitzer",
  "human_lanceur": "Humain, Lanceur",
  "human_ogre": "Ogre, Gros Bras",
  "human_receveur": "Humain, Receveur",
  "human_trois_quart": "Humain, Trois-quart",
  "imperial_nobility_blitzer_noble": "Humain, Blitzer",
  "imperial_nobility_garde_du_corps": "Humain, Bloqueur",
  "imperial_nobility_lanceur_imperial": "Humain, Lanceur",
  "imperial_nobility_ogre": "Ogre, Gros Bras",
  "imperial_nobility_valet_imperiale": "Humain, Trois-quart",
  "khorne_khorngor": "Homme-bête, Coureur",
  "khorne_marauder_sanglant": "Humain, Trois-quart",
  "khorne_rabatteur_sanglant": "Humain, Bloqueur",
  "khorne_rejeton_sanglant": "Rejeton, Gros Bras",
  "lizardmen_bloqueur_saurus": "Homme Lézard, Bloqueur",
  "lizardmen_kroxigor": "Homme Lézard, Gros Bras",
  "lizardmen_skink_cameleon": "Skink, Lanceur",
  "lizardmen_trois_quart_skink": "Skink, Trois-quart",
  "necromantic_horror_coureur_goule": "Goule, Mort-Vivant, Coureur",
  "necromantic_horror_golem_de_chair": "Amalgame, Mort-Vivant, Bloqueur",
  "necromantic_horror_loup_garou": "Loup-Garou, Mort-Vivant, Blitzer",
  "necromantic_horror_spectre": "Spectre, Mort-Vivant, Bloqueur",
  "necromantic_horror_trois_quart_zombie": "Humain, Zombie, Mort-Vivant, Trois-quart",
  "norse_berzerker": "Humain, Blitzer",
  "norse_sanglier_a_biere": "Animal, Spécial",
  "norse_trois_quart": "Humain, Trois-quart",
  "norse_ulfwerener": "Humain, Bloqueur",
  "norse_valkyrie": "Humain, Lanceur, Receveur",
  "norse_yeti": "Yeti, Gros Bras",
  "nurgle_boursouffle": "Humain, Bloqueur",
  "nurgle_pestigor": "Homme-bête, Coureur",
  "nurgle_rejeton_putride": "Rejeton, Gros Bras",
  "nurgle_trois_quart_putrescent": "Humain, Trois-quart",
  "ogre_bloqueur_ogre": "Ogre, Gros Bras, Bloqueur",
  "ogre_botte_nabots_ogre": "Ogre, Gros Bras, Lanceur",
  "ogre_trois_quart_gnoblar": "Gnoblar, Trois-quart",
  "old_world_alliance_aspirant_halfling": "Halfling, Trois-quart",
  "old_world_alliance_blitzer_humain": "Humain, Blitzer",
  "old_world_alliance_blitzer_nain": "Nain, Blitzer",
  "old_world_alliance_coureur_nain": "Nain, Coureur",
  "old_world_alliance_homme_arbre": "Homme-Arbre, Gros Bras",
  "old_world_alliance_lanceur_humain": "Humain, Lanceur",
  "old_world_alliance_ogre": "Ogre, Gros Bras",
  "old_world_alliance_receveur_humain": "Humain, Receveur",
  "old_world_alliance_trois_quart_humain": "Humain, Trois-quart",
  "old_world_alliance_trois_quart_nain": "Nain, Trois-quart",
  "old_world_alliance_tueur_de_trolls_nain": "Nain, Spécial",
  "orc_blitzer_orque": "Orque, Blitzer",
  "orc_bloqueur_kosto": "Orque, Bloqueur",
  "orc_lanceur_orque": "Orque, Lanceur",
  "orc_trois_quart_gobelin": "Gobelin, Trois-quart",
  "orc_trois_quart_orque": "Orque, Trois-quart",
  "orc_troll": "Troll, Gros Bras",
  "skaven_blitzer_skaven": "Skaven, Blitzer",
  "skaven_coureur_d_egouts": "Skaven, Coureur",
  "skaven_lanceur_skaven": "Skaven, Lanceur",
  "skaven_rat_des_clans_skaven": "Skaven, Trois-quart",
  "skaven_rat_ogre": "Skaven, Gros Bras",
  "slann_blitzer": "Homme-Lézard, Blitzer",
  "slann_kroxigor": "Homme-Lézard, Gros Bras",
  "slann_receveur": "Homme-Lézard, Receveur",
  "slann_trois_quart": "Homme-Lézard, Trois-quart",
  "snotling_chariot_a_pompe": "Snotling, Gros Bras, Spécial",
  "snotling_echassier": "Snotling, Coureur",
  "snotling_lance_champis": "Snotling, Spécial",
  "snotling_r_bondisseur": "Snotling, Spécial",
  "snotling_trois_quart_snotling": "Snotling, Trois-quart",
  "snotling_troll_entraine": "Troll, Gros Bras",
  "tomb_kings_blitzer_des_rois_des_tombes": "Humain, Squelette, Mort-Vivant, Blitzer",
  "tomb_kings_gardien_des_tombes": "Humain, Mort-Vivant, Gros Bras, Bloqueur",
  "tomb_kings_lanceur_des_rois_des_tombes": "Humain, Squelette, Mort-Vivant, Lanceur",
  "tomb_kings_trois_quart_squelette": "Humain, Squelette, Mort-Vivant, Trois-quart",
  "undead_blitzer_revenant": "Humain, Mort-Vivant, Squelette, Blitzer",
  "undead_coureur_goule": "Goule, Mort-Vivant, Coureur",
  "undead_momie": "Humain, Mort-Vivant, Gros Bras",
  "undead_trois_quart_squelette": "Humain, Mort-Vivant, Squelette, Trois-quart",
  "undead_trois_quart_zombie": "Humain, Mort-Vivant, Zombie, Trois-quart",
  "underworld_blitzer_skaven": "Skaven, Blitzer",
  "underworld_coureur_d_egout": "Skaven, Coureur",
  "underworld_gobelin_des_bas_fond": "Gobelin, Trois-quart",
  "underworld_lanceur_skaven": "Skaven, Lanceur",
  "underworld_rat_ogre": "Skaven, Gros Bras",
  "underworld_skaven_du_clan_du_rat": "Skaven, Trois-quart",
  "underworld_snotling_des_bas_fond": "Snotling, Trois-quart",
  "underworld_troll": "Troll, Gros Bras",
  "vampire_blitzer_vampire": "Vampire, Mort-Vivant, Blitzer",
  "vampire_coureur_vampire": "Vampire, Mort-Vivant, Coureur",
  "vampire_lanceur_vampire": "Vampire, Mort-Vivant, Lanceur",
  "vampire_trois_quart_sbire": "Humain, Sbire, Trois-quart",
  "vampire_vargheist": "Vampire, Mort-Vivant, Gros Bras",
  "wood_elf_danceur_de_guerre": "Elfe, Blitzer",
  "wood_elf_homme_arbre_de_la_loren": "Homme-arbre, Gros Bras",
  "wood_elf_lanceur_elfe_sylvain": "Elfe, Lanceur",
  "wood_elf_receveur_elfe_sylvain": "Elfe, Receveur",
  "wood_elf_trois_quart_elfe_sylvain": "Elfe, Trois-quart",
};
