/**
 * Système de positions unifiées avec slugs uniques
 * Chaque position a un slug unique (ex: skaven_lineman) et un nom d'affichage
 */
export const RULESETS = ["season_2", "season_3"];
export const DEFAULT_RULESET = "season_2";
const SEASON_TWO_ROSTERS = {
    skaven: {
        name: "Skavens",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "skaven_lineman",
                displayName: "Lineman",
                cost: 50,
                min: 0,
                max: 16,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "",
            },
            {
                slug: "skaven_thrower",
                displayName: "Thrower",
                cost: 85,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 2,
                av: 8,
                skills: "pass,sure-hands",
            },
            {
                slug: "skaven_blitzer",
                displayName: "Blitzer",
                cost: 90,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "block",
            },
            {
                slug: "skaven_gutter_runner",
                displayName: "Gutter Runner",
                cost: 85,
                min: 0,
                max: 4,
                ma: 9,
                st: 2,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "dodge",
            },
            {
                slug: "skaven_rat_ogre",
                displayName: "Rat Ogre",
                cost: 150,
                min: 0,
                max: 1,
                ma: 6,
                st: 5,
                ag: 5,
                pa: 6,
                av: 9,
                skills: "animal-savagery,frenzy,loner-4,mighty-blow-1,prehensile-tail",
            },
        ],
    },
    lizardmen: {
        name: "Hommes-Lézards",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "lizardmen_skink_runner",
                displayName: "Skink Runner",
                cost: 60,
                min: 0,
                max: 12,
                ma: 8,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge,stunty",
            },
            {
                slug: "lizardmen_chameleon_skink",
                displayName: "Chameleon Skink",
                cost: 70,
                min: 0,
                max: 2,
                ma: 7,
                st: 2,
                ag: 3,
                pa: 3,
                av: 8,
                skills: "dodge,on-the-ball,shadowing,stunty",
            },
            {
                slug: "lizardmen_saurus",
                displayName: "Saurus",
                cost: 85,
                min: 0,
                max: 6,
                ma: 6,
                st: 4,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "",
            },
            {
                slug: "lizardmen_kroxigor",
                displayName: "Kroxigor",
                cost: 140,
                min: 0,
                max: 1,
                ma: 6,
                st: 5,
                ag: 5,
                pa: 6,
                av: 10,
                skills: "bone-head,loner-4,mighty-blow-1,prehensile-tail,thick-skull,throw-team-mate",
            },
        ],
    },
    wood_elf: {
        name: "Elfes Sylvains",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "wood_elf_lineman",
                displayName: "Lineman",
                cost: 70,
                min: 0,
                max: 12,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "",
            },
            {
                slug: "wood_elf_thrower",
                displayName: "Thrower",
                cost: 95,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 2,
                av: 8,
                skills: "pass,sure-hands",
            },
            {
                slug: "wood_elf_catcher",
                displayName: "Catcher",
                cost: 90,
                min: 0,
                max: 4,
                ma: 8,
                st: 2,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "catch,dodge",
            },
            {
                slug: "wood_elf_wardancer",
                displayName: "Wardancer",
                cost: 125,
                min: 0,
                max: 2,
                ma: 8,
                st: 3,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "block,dodge,leap",
            },
            {
                slug: "wood_elf_treeman",
                displayName: "Treeman",
                cost: 120,
                min: 0,
                max: 1,
                ma: 2,
                st: 6,
                ag: 5,
                pa: 5,
                av: 11,
                skills: "loner-4,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate",
            },
        ],
    },
    dark_elf: {
        name: "Elfes Noirs",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "dark_elf_lineman",
                displayName: "Dark Elf Linemen",
                cost: 70,
                min: 0,
                max: 12,
                ma: 6,
                st: 3,
                ag: 2,
                pa: 4,
                av: 9,
                skills: "",
            },
            {
                slug: "dark_elf_runner",
                displayName: "Runner",
                cost: 80,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 3,
                av: 8,
                skills: "dump-off",
            },
            {
                slug: "dark_elf_blitzer",
                displayName: "Blitzer",
                cost: 100,
                min: 0,
                max: 4,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 4,
                av: 9,
                skills: "block",
            },
            {
                slug: "dark_elf_assassin",
                displayName: "Assassin",
                cost: 85,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 5,
                av: 8,
                skills: "shadowing,stab",
            },
            {
                slug: "dark_elf_witch_elf",
                displayName: "Witch Elf",
                cost: 110,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 5,
                av: 8,
                skills: "dodge,frenzy,jump-up",
            },
        ],
    },
    dwarf: {
        name: "Nains",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "dwarf_blocker_lineman",
                displayName: "Dwarf Blocker Linemen",
                cost: 70,
                min: 0,
                max: 12,
                ma: 4,
                st: 3,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "block,tackle,thick-skull",
            },
            {
                slug: "dwarf_runner",
                displayName: "Runner",
                cost: 85,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "sure-hands,thick-skull",
            },
            {
                slug: "dwarf_blitzer",
                displayName: "Blitzer",
                cost: 80,
                min: 0,
                max: 2,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 4,
                av: 10,
                skills: "block,thick-skull",
            },
            {
                slug: "dwarf_troll_slayer",
                displayName: "Troll Slayer",
                cost: 95,
                min: 0,
                max: 2,
                ma: 5,
                st: 3,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "block,dauntless,frenzy,thick-skull",
            },
            {
                slug: "dwarf_deathroller",
                displayName: "Deathroller",
                cost: 170,
                min: 0,
                max: 1,
                ma: 4,
                st: 7,
                ag: 5,
                pa: 6,
                av: 11,
                skills: "break-tackle,dirty-player-2,juggernaut,loner-5,mighty-blow-1,no-hands,secret-weapon,stand-firm,armored-skull",
            },
        ],
    },
    goblin: {
        name: "Gobelins",
        budget: 1000,
        tier: "IV",
        naf: false,
        positions: [
            {
                slug: "goblin_lineman",
                displayName: "Goblin Linemen",
                cost: 40,
                min: 0,
                max: 16,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge,right-stuff,stunty",
            },
            {
                slug: "goblin_bomma",
                displayName: "Bomma",
                cost: 45,
                min: 0,
                max: 1,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "bombardier,dodge,secret-weapon,stunty",
            },
            {
                slug: "goblin_looney",
                displayName: "Looney",
                cost: 40,
                min: 0,
                max: 1,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 6,
                av: 8,
                skills: "chainsaw,secret-weapon,stunty",
            },
            {
                slug: "goblin_fanatic",
                displayName: "Fanatic",
                cost: 70,
                min: 0,
                max: 1,
                ma: 3,
                st: 7,
                ag: 3,
                pa: 6,
                av: 8,
                skills: "ball-and-chain,no-hands,secret-weapon,stunty",
            },
            {
                slug: "goblin_pogoer",
                displayName: "Pogoer",
                cost: 75,
                min: 0,
                max: 1,
                ma: 7,
                st: 2,
                ag: 3,
                pa: 5,
                av: 8,
                skills: "dodge,pogo-stick,stunty",
            },
            {
                slug: "goblin_ooligan",
                displayName: "'Ooligan",
                cost: 65,
                min: 0,
                max: 1,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 6,
                av: 8,
                skills: "dirty-player-1,dodge,disturbing-presence,right-stuff,stunty",
            },
            {
                slug: "goblin_doom_diver",
                displayName: "Doom Diver",
                cost: 60,
                min: 0,
                max: 1,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 6,
                av: 8,
                skills: "right-stuff,stunty",
            },
            {
                slug: "goblin_trained_troll",
                displayName: "Trained Troll",
                cost: 115,
                min: 0,
                max: 2,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
        ],
    },
    undead: {
        name: "Morts-Vivants",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "undead_skeleton_lineman",
                displayName: "Skeleton Linemen",
                cost: 40,
                min: 0,
                max: 12,
                ma: 5,
                st: 3,
                ag: 4,
                pa: 6,
                av: 8,
                skills: "regeneration,thick-skull",
            },
            {
                slug: "undead_zombie_lineman",
                displayName: "Zombie Linemen",
                cost: 40,
                min: 0,
                max: 12,
                ma: 4,
                st: 3,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "regeneration",
            },
            {
                slug: "undead_ghoul_runner",
                displayName: "Ghoul Runner",
                cost: 75,
                min: 0,
                max: 4,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge",
            },
            {
                slug: "undead_wight_blitzer",
                displayName: "Wight Blitzer",
                cost: 90,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 5,
                av: 9,
                skills: "block,regeneration",
            },
            {
                slug: "undead_mummy",
                displayName: "Mummy",
                cost: 125,
                min: 0,
                max: 2,
                ma: 3,
                st: 5,
                ag: 5,
                pa: 6,
                av: 10,
                skills: "mighty-blow-1,regeneration",
            },
        ],
    },
    chaos_renegade: {
        name: "Renégats du Chaos",
        budget: 1000,
        tier: "III",
        naf: false,
        positions: [
            {
                slug: "chaos_renegade_human_lineman",
                displayName: "Renegade Human Linemen",
                cost: 50,
                min: 0,
                max: 12,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "",
            },
            {
                slug: "chaos_renegade_human_thrower",
                displayName: "Renegade Human Thrower",
                cost: 75,
                min: 0,
                max: 1,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 3,
                av: 9,
                skills: "animosity,pass,safe-pair-of-hands",
            },
            {
                slug: "chaos_renegade_goblin",
                displayName: "Renegade Goblin",
                cost: 40,
                min: 0,
                max: 1,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "animosity,dodge,right-stuff,stunty",
            },
            {
                slug: "chaos_renegade_orc",
                displayName: "Renegade Orc",
                cost: 50,
                min: 0,
                max: 1,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 5,
                av: 10,
                skills: "animosity",
            },
            {
                slug: "chaos_renegade_skaven",
                displayName: "Renegade Skaven",
                cost: 50,
                min: 0,
                max: 1,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "animosity",
            },
            {
                slug: "chaos_renegade_dark_elf",
                displayName: "Renegade Dark Elf",
                cost: 75,
                min: 0,
                max: 1,
                ma: 6,
                st: 3,
                ag: 2,
                pa: 3,
                av: 9,
                skills: "animosity",
            },
            {
                slug: "chaos_renegade_troll",
                displayName: "Renegade Troll",
                cost: 115,
                min: 0,
                max: 1,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
            {
                slug: "chaos_renegade_ogre",
                displayName: "Renegade Ogre",
                cost: 140,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
            },
            {
                slug: "chaos_renegade_minotaur",
                displayName: "Renegade Minotaur",
                cost: 150,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "frenzy,horns,loner-5,mighty-blow-1,thick-skull,wild-animal",
            },
            {
                slug: "chaos_renegade_rat_ogre",
                displayName: "Renegade Rat Ogre",
                cost: 150,
                min: 0,
                max: 1,
                ma: 6,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "animal-savagery,frenzy,loner-5,mighty-blow-1,prehensile-tail",
            },
        ],
    },
    ogre: {
        name: "Ogres",
        budget: 1000,
        tier: "IV",
        naf: false,
        positions: [
            {
                slug: "ogre_gnoblar_lineman",
                displayName: "Gnoblar Linemen",
                cost: 15,
                min: 0,
                max: 16,
                ma: 5,
                st: 1,
                ag: 3,
                pa: 5,
                av: 6,
                skills: "dodge,right-stuff,sidestep,stunty,titchy",
            },
            {
                slug: "ogre_runt_punter",
                displayName: "Ogre Runt Punter",
                cost: 145,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 4,
                av: 10,
                skills: "bone-head,kick-team-mate,loner-5,mighty-blow-1,thick-skull",
            },
            {
                slug: "ogre_blocker",
                displayName: "Ogre Blocker",
                cost: 140,
                min: 0,
                max: 5,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
            },
        ],
    },
    halfling: {
        name: "Halflings",
        budget: 1000,
        tier: "IV",
        naf: false,
        positions: [
            {
                slug: "halfling_hopeful_lineman",
                displayName: "Halfling Hopeful Linemen",
                cost: 30,
                min: 0,
                max: 16,
                ma: 5,
                st: 2,
                ag: 3,
                pa: 4,
                av: 7,
                skills: "dodge,right-stuff,stunty",
            },
            {
                slug: "halfling_hefty",
                displayName: "Halfling Hefty",
                cost: 50,
                min: 0,
                max: 2,
                ma: 5,
                st: 2,
                ag: 3,
                pa: 3,
                av: 8,
                skills: "dodge,fend,stunty",
            },
            {
                slug: "halfling_catcher",
                displayName: "Halfling Catcher",
                cost: 55,
                min: 0,
                max: 2,
                ma: 5,
                st: 2,
                ag: 3,
                pa: 5,
                av: 7,
                skills: "catch,dodge,right-stuff,sprint,stunty",
            },
            {
                slug: "halfling_altern_forest_treeman",
                displayName: "Altern Forest Treeman",
                cost: 120,
                min: 0,
                max: 2,
                ma: 2,
                st: 6,
                ag: 5,
                pa: 5,
                av: 11,
                skills: "loner-5,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate,timmm-ber",
            },
        ],
    },
    underworld: {
        name: "Bas-Fonds",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "underworld_underworld_goblin_lineman",
                displayName: "Underworld Goblin Linemen",
                cost: 40,
                min: 0,
                max: 12,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge,right-stuff,stunty",
            },
            {
                slug: "underworld_underworld_snotling",
                displayName: "Underworld Snotling",
                cost: 15,
                min: 0,
                max: 6,
                ma: 5,
                st: 1,
                ag: 3,
                pa: 5,
                av: 6,
                skills: "dodge,right-stuff,sidestep,stunty,titchy",
            },
            {
                slug: "underworld_skaven_clanrat",
                displayName: "Skaven Clanrat",
                cost: 50,
                min: 0,
                max: 3,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "animosity-underworld",
            },
            {
                slug: "underworld_skaven_thrower",
                displayName: "Skaven Thrower",
                cost: 85,
                min: 0,
                max: 1,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 2,
                av: 8,
                skills: "animosity-underworld,pass,sure-hands",
            },
            {
                slug: "underworld_gutter_runner",
                displayName: "Gutter Runner",
                cost: 85,
                min: 0,
                max: 1,
                ma: 9,
                st: 2,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "animosity-underworld,dodge",
            },
            {
                slug: "underworld_skaven_blitzer",
                displayName: "Skaven Blitzer",
                cost: 90,
                min: 0,
                max: 1,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 5,
                av: 9,
                skills: "animosity-underworld,block",
            },
            {
                slug: "underworld_underworld_troll",
                displayName: "Underworld Troll",
                cost: 115,
                min: 0,
                max: 1,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
            {
                slug: "underworld_mutant_rat_ogre",
                displayName: "Mutant Rat Ogre",
                cost: 150,
                min: 0,
                max: 1,
                ma: 6,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "animal-savagery,frenzy,loner-5,mighty-blow-1,prehensile-tail",
            },
        ],
    },
    chaos_chosen: {
        name: "Élus du Chaos",
        budget: 1000,
        tier: "III",
        naf: false,
        positions: [
            {
                slug: "chaos_chosen_beastman_runner_lineman",
                displayName: "Beastman Runner Linemen",
                cost: 60,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "horns",
            },
            {
                slug: "chaos_chosen_chosen_blocker",
                displayName: "Chosen Blocker",
                cost: 100,
                min: 0,
                max: 4,
                ma: 5,
                st: 4,
                ag: 3,
                pa: 5,
                av: 10,
                skills: "",
            },
            {
                slug: "chaos_chosen_chaos_troll",
                displayName: "Chaos Troll",
                cost: 115,
                min: 0,
                max: 1,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
            {
                slug: "chaos_chosen_chaos_ogre",
                displayName: "Chaos Ogre",
                cost: 140,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
            },
            {
                slug: "chaos_chosen_minotaur",
                displayName: "Minotaur",
                cost: 150,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "frenzy,horns,loner-5,mighty-blow-1,thick-skull,wild-animal",
            },
        ],
    },
    imperial_nobility: {
        name: "Noblesse Impériale",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "imperial_nobility_imperial_retainer_lineman",
                displayName: "Imperial Retainer Linemen",
                cost: 45,
                min: 0,
                max: 12,
                ma: 6,
                st: 3,
                ag: 4,
                pa: 4,
                av: 8,
                skills: "fend",
            },
            {
                slug: "imperial_nobility_imperial_thrower",
                displayName: "Imperial Thrower",
                cost: 75,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 3,
                av: 9,
                skills: "pass,running-pass",
            },
            {
                slug: "imperial_nobility_noble_blitzer",
                displayName: "Noble Blitzer",
                cost: 105,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "block,catch",
            },
            {
                slug: "imperial_nobility_bodyguard",
                displayName: "Bodyguard",
                cost: 90,
                min: 0,
                max: 4,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 5,
                av: 9,
                skills: "stand-firm,wrestle",
            },
            {
                slug: "imperial_nobility_ogre",
                displayName: "Ogre",
                cost: 140,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
            },
        ],
    },
    necromantic_horror: {
        name: "Horreurs Nécromantiques",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "necromantic_horror_zombie_lineman",
                displayName: "Zombie Linemen",
                cost: 40,
                min: 0,
                max: 16,
                ma: 4,
                st: 3,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "regeneration",
            },
            {
                slug: "necromantic_horror_ghoul_runner",
                displayName: "Ghoul Runner",
                cost: 75,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge",
            },
            {
                slug: "necromantic_horror_wraith",
                displayName: "Wraith",
                cost: 95,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 6,
                av: 9,
                skills: "block,foul-appearance,no-hands,regeneration,sidestep",
            },
            {
                slug: "necromantic_horror_werewolf",
                displayName: "Werewolf",
                cost: 125,
                min: 0,
                max: 2,
                ma: 8,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "claws,frenzy,regeneration",
            },
            {
                slug: "necromantic_horror_flesh_golem",
                displayName: "Flesh Golem",
                cost: 115,
                min: 0,
                max: 2,
                ma: 4,
                st: 4,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "regeneration,stand-firm,thick-skull",
            },
        ],
    },
    orc: {
        name: "Orques",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "orc_orc_lineman",
                displayName: "Orc Linemen",
                cost: 50,
                min: 0,
                max: 16,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 4,
                av: 10,
                skills: "animosity",
            },
            {
                slug: "orc_thrower",
                displayName: "Thrower",
                cost: 65,
                min: 0,
                max: 2,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 3,
                av: 9,
                skills: "animosity-all,pass,sure-hands",
            },
            {
                slug: "orc_blitzer",
                displayName: "Blitzer",
                cost: 80,
                min: 0,
                max: 4,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 10,
                skills: "animosity-all,block",
            },
            {
                slug: "orc_big_un_blocker",
                displayName: "Big Un Blocker",
                cost: 90,
                min: 0,
                max: 4,
                ma: 5,
                st: 4,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "animosity",
            },
            {
                slug: "orc_goblin",
                displayName: "Goblin",
                cost: 40,
                min: 0,
                max: 4,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge,right-stuff,stunty",
            },
            {
                slug: "orc_untrained_troll",
                displayName: "Untrained Troll",
                cost: 115,
                min: 0,
                max: 1,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
        ],
    },
    nurgle: {
        name: "Nurgle",
        budget: 1000,
        tier: "III",
        naf: false,
        positions: [
            {
                slug: "nurgle_rotter_lineman",
                displayName: "Rotter Linemen",
                cost: 35,
                min: 0,
                max: 12,
                ma: 5,
                st: 3,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "decay,plague-ridden",
            },
            {
                slug: "nurgle_pestigor",
                displayName: "Pestigor",
                cost: 75,
                min: 0,
                max: 4,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "horns,plague-ridden,regeneration",
            },
            {
                slug: "nurgle_bloater",
                displayName: "Bloater",
                cost: 115,
                min: 0,
                max: 4,
                ma: 4,
                st: 4,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "disturbing-presence,foul-appearance,plague-ridden,regeneration",
            },
            {
                slug: "nurgle_rotspawn",
                displayName: "Rotspawn",
                cost: 140,
                min: 0,
                max: 1,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 6,
                av: 10,
                skills: "disturbing-presence,foul-appearance,loner-5,mighty-blow-1,plague-ridden,really-stupid-2,regeneration,tentacles",
            },
        ],
    },
    old_world_alliance: {
        name: "Alliance du Vieux Monde",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "old_world_alliance_old_world_human_lineman",
                displayName: "Old World Human Linemen",
                cost: 50,
                min: 0,
                max: 12,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "",
            },
            {
                slug: "old_world_alliance_old_world_human_thrower",
                displayName: "Old World Human Thrower",
                cost: 80,
                min: 0,
                max: 1,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 3,
                av: 9,
                skills: "animosity-all-dwarf-halfling,pass,sure-hands",
            },
            {
                slug: "old_world_alliance_old_world_human_catcher",
                displayName: "Old World Human Catcher",
                cost: 65,
                min: 0,
                max: 1,
                ma: 8,
                st: 2,
                ag: 3,
                pa: 5,
                av: 8,
                skills: "animosity-all-dwarf-halfling,catch,dodge",
            },
            {
                slug: "old_world_alliance_old_world_human_blitzer",
                displayName: "Old World Human Blitzer",
                cost: 90,
                min: 0,
                max: 1,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "animosity-all-dwarf-halfling,block",
            },
            {
                slug: "old_world_alliance_old_world_dwarf_blocker",
                displayName: "Old World Dwarf Blocker",
                cost: 75,
                min: 0,
                max: 2,
                ma: 4,
                st: 3,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "arm-bar,brawler,loner-4,thick-skull",
            },
            {
                slug: "old_world_alliance_old_world_dwarf_runner",
                displayName: "Old World Dwarf Runner",
                cost: 85,
                min: 0,
                max: 1,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "loner-4,sure-hands,thick-skull",
            },
            {
                slug: "old_world_alliance_old_world_dwarf_blitzer",
                displayName: "Old World Dwarf Blitzer",
                cost: 80,
                min: 0,
                max: 1,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 4,
                av: 10,
                skills: "block,loner-4,thick-skull",
            },
            {
                slug: "old_world_alliance_old_world_dwarf_troll_slayer",
                displayName: "Old World Dwarf Troll Slayer",
                cost: 95,
                min: 0,
                max: 1,
                ma: 5,
                st: 3,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "block,dauntless,frenzy,loner-4,thick-skull",
            },
            {
                slug: "old_world_alliance_old_world_halfling_hopeful",
                displayName: "Old World Halfling Hopeful",
                cost: 30,
                min: 0,
                max: 2,
                ma: 5,
                st: 2,
                ag: 3,
                pa: 4,
                av: 7,
                skills: "animosity-all-dwarf-human,dodge,right-stuff,stunty",
            },
            {
                slug: "old_world_alliance_ogre",
                displayName: "Ogre",
                cost: 140,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
            },
            {
                slug: "old_world_alliance_altern_forest_treeman",
                displayName: "Altern Forest Treeman",
                cost: 120,
                min: 0,
                max: 1,
                ma: 2,
                st: 6,
                ag: 5,
                pa: 5,
                av: 11,
                skills: "loner-5,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate,timmm-ber",
            },
        ],
    },
    elven_union: {
        name: "Union Elfique",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "elven_union_lineman",
                displayName: "Linemen",
                cost: 60,
                min: 0,
                max: 12,
                ma: 6,
                st: 3,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "",
            },
            {
                slug: "elven_union_thrower",
                displayName: "Thrower",
                cost: 75,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 2,
                pa: 2,
                av: 8,
                skills: "pass",
            },
            {
                slug: "elven_union_catcher",
                displayName: "Catcher",
                cost: 100,
                min: 0,
                max: 4,
                ma: 8,
                st: 3,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "catch,nerves-of-steel",
            },
            {
                slug: "elven_union_blitzer",
                displayName: "Blitzer",
                cost: 115,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 3,
                av: 9,
                skills: "block,sidestep",
            },
        ],
    },
    human: {
        name: "Humains",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "human_human_lineman",
                displayName: "Human Linemen",
                cost: 50,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "",
            },
            {
                slug: "human_thrower",
                displayName: "Thrower",
                cost: 80,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 2,
                av: 9,
                skills: "pass,sure-hands",
            },
            {
                slug: "human_catcher",
                displayName: "Catcher",
                cost: 65,
                min: 0,
                max: 4,
                ma: 8,
                st: 2,
                ag: 3,
                pa: 5,
                av: 8,
                skills: "catch,dodge",
            },
            {
                slug: "human_blitzer",
                displayName: "Blitzer",
                cost: 85,
                min: 0,
                max: 4,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "block",
            },
            {
                slug: "human_halfling_hopeful",
                displayName: "Halfling Hopeful",
                cost: 30,
                min: 0,
                max: 3,
                ma: 5,
                st: 2,
                ag: 3,
                pa: 4,
                av: 7,
                skills: "dodge,right-stuff,stunty",
            },
            {
                slug: "human_ogre",
                displayName: "Ogre",
                cost: 140,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
            },
        ],
    },
    black_orc: {
        name: "Orques Noirs",
        budget: 1000,
        tier: "III",
        naf: false,
        positions: [
            {
                slug: "black_orc_goblin_bruiser_lineman",
                displayName: "Goblin Bruiser Linemen",
                cost: 45,
                min: 0,
                max: 12,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "dodge,right-stuff,stunty,thick-skull",
            },
            {
                slug: "black_orc_black_orc",
                displayName: "Black Orc",
                cost: 90,
                min: 0,
                max: 6,
                ma: 4,
                st: 4,
                ag: 4,
                pa: 5,
                av: 10,
                skills: "brawler,grab",
            },
            {
                slug: "black_orc_trained_troll",
                displayName: "Trained Troll",
                cost: 115,
                min: 0,
                max: 1,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
        ],
    },
    chaos_dwarf: {
        name: "Nains du Chaos",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "chaos_dwarf_hobgoblin_lineman",
                displayName: "Hobgoblin Linemen",
                cost: 40,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "shadowing",
            },
            {
                slug: "chaos_dwarf_hobgoblin_sneaky_stabba",
                displayName: "Hobgoblin Sneaky Stabba",
                cost: 70,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 5,
                av: 8,
                skills: "stab",
            },
            {
                slug: "chaos_dwarf_chaos_dwarf_blocker",
                displayName: "Chaos Dwarf Blocker",
                cost: 70,
                min: 0,
                max: 4,
                ma: 4,
                st: 3,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "block,iron-hard-skin,thick-skull",
            },
            {
                slug: "chaos_dwarf_chaos_dwarf_flamesmith",
                displayName: "Chaos Dwarf Flamesmith",
                cost: 80,
                min: 0,
                max: 2,
                ma: 5,
                st: 3,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "brawler",
            },
            {
                slug: "chaos_dwarf_bull_centaur_blitzer",
                displayName: "Bull Centaur Blitzer",
                cost: 130,
                min: 0,
                max: 2,
                ma: 6,
                st: 4,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "disturbing-presence,thick-skull,sprint,sure-feet",
            },
            {
                slug: "chaos_dwarf_renegade_minotaur",
                displayName: "Renegade Minotaur",
                cost: 150,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "thick-skull,frenzy,horns,loner-4,mighty-blow-1,wild-animal",
            },
        ],
    },
    slann: {
        name: "Slann",
        budget: 1000,
        tier: "II",
        naf: true,
        positions: [
            {
                slug: "slann_lineman",
                displayName: "Lineman",
                cost: 60,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "pogo-stick,very-long-legs",
            },
            {
                slug: "slann_catcher",
                displayName: "Catcher",
                cost: 80,
                min: 0,
                max: 4,
                ma: 7,
                st: 2,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "diving-catch,pogo-stick,very-long-legs",
            },
            {
                slug: "slann_blitzer",
                displayName: "Blitzer",
                cost: 110,
                min: 0,
                max: 4,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "diving-tackle,jump-up,pogo-stick,very-long-legs",
            },
            {
                slug: "slann_kroxigor",
                displayName: "Kroxigor",
                cost: 140,
                min: 0,
                max: 1,
                ma: 6,
                st: 5,
                ag: 5,
                pa: 6,
                av: 10,
                skills: "bone-head,loner-4,mighty-blow-1,prehensile-tail,thick-skull",
            },
        ],
    },
    amazon: {
        name: "Amazones",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "amazon_lineman",
                displayName: "Trois-Quart Aigle",
                cost: 50,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "shadowing",
            },
            {
                slug: "amazon_thrower",
                displayName: "Lanceuse Pythée",
                cost: 80,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "pass,accurate",
            },
            {
                slug: "amazon_catcher",
                displayName: "Receveuse Nymphe",
                cost: 90,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "dodge,sprint",
            },
            {
                slug: "amazon_blitzer",
                displayName: "Bloqueuse Jaguar",
                cost: 110,
                min: 0,
                max: 2,
                ma: 5,
                st: 4,
                ag: 4,
                pa: 5,
                av: 9,
                skills: "block",
            },
        ],
    },
    high_elf: {
        name: "Hauts Elfes",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "high_elf_lineman",
                displayName: "Ligne-Quart",
                cost: 70,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "",
            },
            {
                slug: "high_elf_catcher",
                displayName: "Receveur",
                cost: 90,
                min: 0,
                max: 4,
                ma: 7,
                st: 2,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "catch",
            },
            {
                slug: "high_elf_thrower",
                displayName: "Lanceur",
                cost: 100,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 2,
                pa: 3,
                av: 8,
                skills: "pass,accurate",
            },
            {
                slug: "high_elf_blitzer",
                displayName: "Blitzer",
                cost: 100,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 4,
                av: 9,
                skills: "block",
            },
        ],
    },
    khorne: {
        name: "Khorne",
        budget: 1000,
        tier: "III",
        naf: false,
        positions: [
            {
                slug: "khorne_marauder",
                displayName: "Marauder",
                cost: 50,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "",
            },
            {
                slug: "khorne_khorngor",
                displayName: "Khorngor",
                cost: 70,
                min: 0,
                max: 4,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "thick-skull,frenzy",
            },
            {
                slug: "khorne_bloodletter",
                displayName: "Bloodletter",
                cost: 110,
                min: 0,
                max: 4,
                ma: 5,
                st: 4,
                ag: 4,
                pa: 6,
                av: 10,
                skills: "thick-skull,iron-hard-skin",
            },
            {
                slug: "khorne_bloodspawn",
                displayName: "Bloodspawn",
                cost: 160,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "thick-skull,frenzy,loner-4,mighty-blow-1,wild-animal",
            },
        ],
    },
    vampire: {
        name: "Vampires",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "vampire_vampire",
                displayName: "Vampire",
                cost: 110,
                min: 0,
                max: 16,
                ma: 6,
                st: 4,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "hypnotic-gaze,regeneration",
            },
            {
                slug: "vampire_thrall",
                displayName: "Thrall",
                cost: 40,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "",
            },
        ],
    },
    tomb_kings: {
        name: "Rois des Tombes",
        budget: 1000,
        tier: "II",
        naf: false,
        positions: [
            {
                slug: "tomb_kings_skeleton",
                displayName: "Squelette",
                cost: 40,
                min: 0,
                max: 16,
                ma: 5,
                st: 3,
                ag: 4,
                pa: 4,
                av: 8,
                skills: "regeneration",
            },
            {
                slug: "tomb_kings_tomb_guardian",
                displayName: "Gardien des Tombes",
                cost: 100,
                min: 0,
                max: 4,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 6,
                av: 10,
                skills: "block,thick-skull,regeneration",
            },
            {
                slug: "tomb_kings_thrower",
                displayName: "Lanceur",
                cost: 70,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "pass,accurate,regeneration",
            },
            {
                slug: "tomb_kings_blitzer",
                displayName: "Blitzer",
                cost: 90,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "block,thick-skull,regeneration",
            },
        ],
    },
    gnome: {
        name: "Gnomes",
        budget: 1000,
        tier: "IV",
        naf: false,
        positions: [
            {
                slug: "gnome_lineman",
                displayName: "Trois-Quart Coureur",
                cost: 50,
                min: 0,
                max: 16,
                ma: 6,
                st: 2,
                ag: 3,
                pa: 4,
                av: 7,
                skills: "dodge,thick-skull",
            },
            {
                slug: "gnome_gnome_with_piston",
                displayName: "Gnome avec pilonneuse",
                cost: 70,
                min: 0,
                max: 2,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 5,
                av: 9,
                skills: "iron-hard-skin",
            },
            {
                slug: "gnome_dynamite_thrower",
                displayName: "Lanceur de Dynamite",
                cost: 80,
                min: 0,
                max: 2,
                ma: 5,
                st: 2,
                ag: 3,
                pa: 6,
                av: 8,
                skills: "pass",
            },
            {
                slug: "gnome_beastmaster",
                displayName: "Maître des bêtes Gnomes",
                cost: 90,
                min: 0,
                max: 2,
                ma: 5,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "iron-hard-skin",
            },
            {
                slug: "gnome_treeman",
                displayName: "Homme-Arbre",
                cost: 120,
                min: 0,
                max: 1,
                ma: 2,
                st: 6,
                ag: 5,
                pa: 6,
                av: 11,
                skills: "guard,iron-hard-skin,loner-4,mighty-blow-1,stand-firm,take-root,wild-animal",
            },
        ],
    },
    norse: {
        name: "Nordiques",
        budget: 1000,
        tier: "I",
        naf: false,
        positions: [
            {
                slug: "norse_lineman",
                displayName: "Ligne-Quart",
                cost: 70,
                min: 0,
                max: 16,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 4,
                av: 9,
                skills: "block,thick-skull",
            },
            {
                slug: "norse_runner",
                displayName: "Coureur à bâton",
                cost: 70,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 3,
                pa: 4,
                av: 8,
                skills: "shadowing,thick-skull,dodge",
            },
            {
                slug: "norse_thrower",
                displayName: "Lanceur",
                cost: 70,
                min: 0,
                max: 2,
                ma: 6,
                st: 3,
                ag: 3,
                pa: 3,
                av: 8,
                skills: "pass,accurate,thick-skull",
            },
            {
                slug: "norse_valkyrie",
                displayName: "Valkyrie",
                cost: 90,
                min: 0,
                max: 2,
                ma: 7,
                st: 3,
                ag: 2,
                pa: 4,
                av: 8,
                skills: "thick-skull,dodge,sprint,leap",
            },
            {
                slug: "norse_ulfwernar",
                displayName: "Ulfwernar",
                cost: 110,
                min: 0,
                max: 2,
                ma: 5,
                st: 4,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "block,thick-skull,frenzy",
            },
            {
                slug: "norse_yhetee",
                displayName: "Yhetee",
                cost: 140,
                min: 0,
                max: 1,
                ma: 5,
                st: 5,
                ag: 4,
                pa: 6,
                av: 9,
                skills: "thick-skull,frenzy,claws,loner-4,mighty-blow-1,wild-animal",
            },
        ],
    },
    snotling: {
        name: "Snotlings",
        budget: 1000,
        tier: "IV",
        naf: false,
        positions: [
            {
                slug: "snotling_snotling_lineman",
                displayName: "Snotling",
                cost: 15,
                min: 0,
                max: 16,
                ma: 5,
                st: 1,
                ag: 3,
                pa: 5,
                av: 6,
                skills: "animosity-underworld,projectile-vomit,animal-savagery,always-hungry,really-stupid-2,right-stuff,stunty,titchy",
            },
            {
                slug: "snotling_fungus_flinga",
                displayName: "Fungus Flinga",
                cost: 30,
                min: 0,
                max: 2,
                ma: 5,
                st: 1,
                ag: 3,
                pa: 4,
                av: 6,
                skills: "animosity-underworld,projectile-vomit,animal-savagery,really-stupid-2,right-stuff,secret-weapon",
            },
            {
                slug: "snotling_fun_hoppa",
                displayName: "Fan Happa",
                cost: 20,
                min: 0,
                max: 2,
                ma: 6,
                st: 1,
                ag: 3,
                pa: 5,
                av: 6,
                skills: "animosity-all-dwarf-halfling,animosity-all-dwarf-human,pogo-stick,animal-savagery,really-stupid-2,right-stuff",
            },
            {
                slug: "snotling_stilty_runna",
                displayName: "Milky Snotling",
                cost: 20,
                min: 0,
                max: 2,
                ma: 6,
                st: 1,
                ag: 3,
                pa: 5,
                av: 6,
                skills: "animosity-underworld,pogo-stick,animal-savagery,really-stupid-2,right-stuff,swarming",
            },
            {
                slug: "snotling_pump_wagon",
                displayName: "Pump Wagon",
                cost: 105,
                min: 0,
                max: 2,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 6,
                av: 9,
                skills: "armored-skull,dirty-player-1,juggernaut,mighty-blow-1,secret-weapon,stand-firm,thick-skull",
            },
            {
                slug: "snotling_trained_troll",
                displayName: "Trained Troll",
                cost: 115,
                min: 0,
                max: 2,
                ma: 4,
                st: 5,
                ag: 5,
                pa: 5,
                av: 10,
                skills: "always-hungry,loner-3,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
            },
        ],
    },
};
const cloneRoster = (roster) => ({
    ...roster,
    positions: roster.positions.map((position) => ({ ...position })),
});
const cloneRosterMap = (source) => Object.fromEntries(Object.entries(source).map(([slug, roster]) => [
    slug,
    cloneRoster(roster),
]));
export const TEAM_ROSTERS_BY_RULESET = {
    season_2: SEASON_TWO_ROSTERS,
    season_3: cloneRosterMap(SEASON_TWO_ROSTERS),
};
export const TEAM_ROSTERS = TEAM_ROSTERS_BY_RULESET[DEFAULT_RULESET];
const getRostersForRuleset = (ruleset = DEFAULT_RULESET) => {
    return TEAM_ROSTERS_BY_RULESET[ruleset] ?? TEAM_ROSTERS_BY_RULESET[DEFAULT_RULESET];
};
// Fonction utilitaire pour obtenir une position par son slug
export function getPositionBySlug(slug, ruleset = DEFAULT_RULESET) {
    const rosterMap = getRostersForRuleset(ruleset);
    for (const roster of Object.values(rosterMap)) {
        const position = roster.positions.find((p) => p.slug === slug);
        if (position)
            return position;
    }
    if (ruleset !== DEFAULT_RULESET) {
        return getPositionBySlug(slug, DEFAULT_RULESET);
    }
    return null;
}
// Fonction utilitaire pour obtenir toutes les positions d'une équipe
export function getTeamPositions(teamRoster, ruleset = DEFAULT_RULESET) {
    const roster = getRostersForRuleset(ruleset)[teamRoster];
    if (roster) {
        return roster.positions;
    }
    if (ruleset !== DEFAULT_RULESET) {
        return getTeamPositions(teamRoster, DEFAULT_RULESET);
    }
    return [];
}
// Fonction utilitaire pour obtenir le nom d'affichage d'un slug
export function getDisplayName(slug, ruleset = DEFAULT_RULESET) {
    const position = getPositionBySlug(slug, ruleset);
    return position ? position.displayName : slug;
}
// Fonction utilitaire pour obtenir le slug à partir du nom d'affichage et de l'équipe
export function getSlugFromDisplayName(displayName, teamRoster, ruleset = DEFAULT_RULESET) {
    const positions = getTeamPositions(teamRoster, ruleset);
    const position = positions.find(p => p.displayName === displayName);
    if (position) {
        return position.slug;
    }
    if (ruleset !== DEFAULT_RULESET) {
        return getSlugFromDisplayName(displayName, teamRoster, DEFAULT_RULESET);
    }
    return null;
}
// Mapping des anciennes clés vers les nouveaux slugs (pour migration)
export const LEGACY_POSITION_MAPPING = {
    // Skaven
    "lineman": "skaven_lineman",
    "thrower": "skaven_thrower",
    "blitzer": "skaven_blitzer",
    "gutter": "skaven_gutter_runner",
    "gutter_runner": "skaven_gutter_runner",
    "ratogre": "skaven_rat_ogre",
    "rat_ogre": "skaven_rat_ogre",
    // Lizardmen
    "skink": "lizardmen_skink_runner",
    "lizardmen_skink": "lizardmen_skink_runner", // Migration ancien slug
    "chameleon_skink": "lizardmen_chameleon_skink",
    "saurus": "lizardmen_saurus",
    "kroxigor": "lizardmen_kroxigor",
};
