/**
 * Système de positions unifiées avec slugs uniques
 * Chaque position a un slug unique (ex: skaven_lineman) et un nom d'affichage
 */

export interface PositionDefinition {
  slug: string;        // Slug unique (ex: skaven_lineman)
  displayName: string; // Nom d'affichage (ex: Lineman)
  cost: number;        // Coût en kpo
  min: number;         // Minimum requis
  max: number;         // Maximum autorisé
  ma: number;          // Movement Allowance
  st: number;          // Strength
  ag: number;          // Agility
  pa: number;          // Passing
  av: number;          // Armour Value
  skills: string;      // Compétences de base (séparées par virgules)
}

export interface TeamRoster {
  name: string;
  budget: number;
  tier: "I" | "II" | "III" | "IV";
  naf: boolean;
  descriptionFr?: string;
  descriptionEn?: string;
  regionalRules?: string[];
  specialRules?: string;
  positions: PositionDefinition[];
}

export type Ruleset = "season_2" | "season_3";
export const RULESETS: Ruleset[] = ["season_2", "season_3"];
export const DEFAULT_RULESET: Ruleset = "season_2";

type TeamRosterMap = Record<string, TeamRoster>;

// Mapping complet des équipes avec leurs positions
const SEASON_TWO_ROSTERS: TeamRosterMap = {
  skaven: {
    name: "Skavens",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les Skavens sont une race de rats humanoïdes qui se reproduisent rapidement et sont connus pour leur agilité et leur vitesse. Leurs équipes Blood Bowl sont réputées pour leur jeu rapide et leur capacité à marquer rapidement.",
    descriptionEn: "Skaven are a race of humanoid rats that breed quickly and are known for their agility and speed. Their Blood Bowl teams are renowned for their fast play and ability to score quickly.",
    regionalRules: ["underworld_challenge"],
    specialRules: undefined,
    positions: [
      {
        slug: "skaven_lineman",
        displayName: "Lineman",
        cost: 50,
        min: 0,
        max: 16,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "skaven_thrower",
        displayName: "Thrower",
        cost: 85,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 2,
        av: 8,
        skills: "pass,sure-hands",
      },
      {
        slug: "skaven_blitzer",
        displayName: "Blitzer",
        cost: 90,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block",
      },
      {
        slug: "skaven_gutter_runner",
        displayName: "Gutter Runner",
        cost: 85,
        min: 0,
        max: 4,
        ma: 9,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "dodge",
      },
      {
        slug: "skaven_rat_ogre",
        displayName: "Rat Ogre",
        cost: 150,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 5,
        pa: 6,
        av: 9,
        skills: "animal-savagery,frenzy,loner-4,mighty-blow-1,prehensile-tail",
      },
    ],
  },
  lizardmen: {
    name: "Hommes-Lézards",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Hommes-Lézards sont une race ancienne de Lustrie, combinant la force brute des Saurus avec l'agilité des Skinks. Leurs équipes sont équilibrées entre puissance et vitesse.",
    descriptionEn: "Lizardmen are an ancient race from Lustria, combining the brute strength of Saurus with the agility of Skinks. Their teams are balanced between power and speed.",
    regionalRules: ["lustrian_superleague"],
    specialRules: undefined,
    positions: [
      {
        slug: "lizardmen_skink_runner",
        displayName: "Skink Runner",
        cost: 60,
        min: 0,
        max: 12,
        ma: 8,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,stunty",
      },
      {
        slug: "lizardmen_chameleon_skink",
        displayName: "Chameleon Skink",
        cost: 70,
        min: 0,
        max: 2,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,on-the-ball,shadowing,stunty",
      },
      {
        slug: "lizardmen_saurus",
        displayName: "Saurus",
        cost: 85,
        min: 0,
        max: 6,
        ma: 6,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "",
      },
      {
        slug: "lizardmen_kroxigor",
        displayName: "Kroxigor",
        cost: 140,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "bone-head,loner-4,mighty-blow-1,prehensile-tail,thick-skull,throw-team-mate",
      },
    ],
  },
  wood_elf: {
    name: "Elfes Sylvains",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Elfes Sylvains sont des maîtres de l'agilité et de la vitesse. Leurs équipes Blood Bowl excellent dans le jeu de passe et la mobilité, mais sont fragiles.",
    descriptionEn: "Wood Elves are masters of agility and speed. Their Blood Bowl teams excel at passing and mobility, but are fragile.",
    regionalRules: ["elven_kingdoms_league"],
    specialRules: undefined,
    positions: [
      {
        slug: "wood_elf_lineman",
        displayName: "Lineman",
        cost: 70,
        min: 0,
        max: 12,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "wood_elf_thrower",
        displayName: "Thrower",
        cost: 95,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "pass,sure-hands",
      },
      {
        slug: "wood_elf_catcher",
        displayName: "Catcher",
        cost: 90,
        min: 0,
        max: 4,
        ma: 8,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "catch,dodge",
      },
      {
        slug: "wood_elf_wardancer",
        displayName: "Wardancer",
        cost: 125,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "block,dodge,leap",
      },
      {
        slug: "wood_elf_treeman",
        displayName: "Treeman",
        cost: 120,
        min: 0,
        max: 1,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "loner-4,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate",
      },
    ],
  },
  dark_elf: {
    name: "Elfes Noirs",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Elfes Noirs sont une race cruelle et agressive qui combine agilité et violence. Leurs équipes Blood Bowl sont rapides et dangereuses, spécialisées dans le blocage et la blessure.",
    descriptionEn: "Dark Elves are a cruel and aggressive race that combines agility with violence. Their Blood Bowl teams are fast and dangerous, specializing in blocking and injuring.",
    regionalRules: ["elven_kingdoms_league"],
    specialRules: undefined,
    positions: [
      {
        slug: "dark_elf_lineman",
        displayName: "Dark Elf Linemen",
        cost: 70,
        min: 0,
        max: 12,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 4,
        av: 9,
        skills: "",
      },
      {
        slug: "dark_elf_runner",
        displayName: "Runner",
        cost: 80,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "dump-off",
      },
      {
        slug: "dark_elf_blitzer",
        displayName: "Blitzer",
        cost: 100,
        min: 0,
        max: 4,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 9,
        skills: "block",
      },
      {
        slug: "dark_elf_assassin",
        displayName: "Assassin",
        cost: 85,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 5,
        av: 8,
        skills: "shadowing,stab",
      },
      {
        slug: "dark_elf_witch_elf",
        displayName: "Witch Elf",
        cost: 110,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 5,
        av: 8,
        skills: "dodge,frenzy,jump-up",
      },
    ],
  },
  dwarf: {
    name: "Nains",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Nains sont une race robuste et résistante, connue pour leur force et leur endurance. Leurs équipes Blood Bowl sont lentes mais très résistantes, spécialisées dans le blocage défensif.",
    descriptionEn: "Dwarves are a sturdy and resilient race, known for their strength and endurance. Their Blood Bowl teams are slow but very tough, specializing in defensive blocking.",
    regionalRules: ["old_world_classic", "worlds_edge_superleague"],
    specialRules: undefined,
    positions: [
      {
        slug: "dwarf_blocker_lineman",
        displayName: "Dwarf Blocker Linemen",
        cost: 70,
        min: 0,
        max: 12,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "block,tackle,thick-skull",
      },
      {
        slug: "dwarf_runner",
        displayName: "Runner",
        cost: 85,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "sure-hands,thick-skull",
      },
      {
        slug: "dwarf_blitzer",
        displayName: "Blitzer",
        cost: 80,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "block,thick-skull",
      },
      {
        slug: "dwarf_troll_slayer",
        displayName: "Troll Slayer",
        cost: 95,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "block,dauntless,frenzy,thick-skull",
      },
      {
        slug: "dwarf_deathroller",
        displayName: "Deathroller",
        cost: 170,
        min: 0,
        max: 1,
        ma: 4,
        st: 7,
        ag: 5,
        pa: 6,
        av: 11,
        skills: "break-tackle,dirty-player-2,juggernaut,loner-5,mighty-blow-1,no-hands,secret-weapon,stand-firm,armored-skull",
      },
    ],
  },
  goblin: {
    name: "Gobelins",
    budget: 1000,
    tier: "IV",
    naf: false,
    descriptionFr: "Les Gobelins sont de petits joueurs agiles mais fragiles, connus pour leur utilisation d'armes secrètes et de tactiques déloyales. Leurs équipes Blood Bowl sont imprévisibles et dangereuses.",
    descriptionEn: "Goblins are small, agile but fragile players, known for their use of secret weapons and underhanded tactics. Their Blood Bowl teams are unpredictable and dangerous.",
    regionalRules: ["badlands_brawl", "underworld_challenge"],
    specialRules: undefined,
    positions: [
      {
        slug: "goblin_lineman",
        displayName: "Goblin Linemen",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,right-stuff,stunty",
      },
      {
        slug: "goblin_bomma",
        displayName: "Bomma",
        cost: 45,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "bombardier,dodge,secret-weapon,stunty",
      },
      {
        slug: "goblin_looney",
        displayName: "Looney",
        cost: 40,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "chainsaw,secret-weapon,stunty",
      },
      {
        slug: "goblin_fanatic",
        displayName: "Fanatic",
        cost: 70,
        min: 0,
        max: 1,
        ma: 3,
        st: 7,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "ball-and-chain,no-hands,secret-weapon,stunty",
      },
      {
        slug: "goblin_pogoer",
        displayName: "Pogoer",
        cost: 75,
        min: 0,
        max: 1,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "dodge,pogo-stick,stunty",
      },
      {
        slug: "goblin_ooligan",
        displayName: "'Ooligan",
        cost: 65,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "dirty-player-1,dodge,disturbing-presence,right-stuff,stunty",
      },
      {
        slug: "goblin_doom_diver",
        displayName: "Doom Diver",
        cost: 60,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "right-stuff,stunty",
      },
      {
        slug: "goblin_trained_troll",
        displayName: "Trained Troll",
        cost: 115,
        min: 0,
        max: 2,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
    ],
  },
  undead: {
    name: "Morts-Vivants",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les Morts-Vivants sont une équipe composée de squelettes, zombies et autres créatures ressuscitées. Leurs équipes sont résistantes et bénéficient de la régénération, mais manquent d'agilité.",
    descriptionEn: "The Undead are a team composed of skeletons, zombies and other resurrected creatures. Their teams are resilient and benefit from regeneration, but lack agility.",
    regionalRules: ["sylvanian_spotlight"],
    specialRules: undefined,
    positions: [
      {
        slug: "undead_skeleton_lineman",
        displayName: "Skeleton Linemen",
        cost: 40,
        min: 0,
        max: 12,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 8,
        skills: "regeneration,thick-skull",
      },
      {
        slug: "undead_zombie_lineman",
        displayName: "Zombie Linemen",
        cost: 40,
        min: 0,
        max: 12,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "regeneration",
      },
      {
        slug: "undead_ghoul_runner",
        displayName: "Ghoul Runner",
        cost: 75,
        min: 0,
        max: 4,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge",
      },
      {
        slug: "undead_wight_blitzer",
        displayName: "Wight Blitzer",
        cost: 90,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 5,
        av: 9,
        skills: "block,regeneration",
      },
      {
        slug: "undead_mummy",
        displayName: "Mummy",
        cost: 125,
        min: 0,
        max: 2,
        ma: 3,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "mighty-blow-1,regeneration",
      },
    ],
  },
  chaos_renegade: {
    name: "Renégats du Chaos",
    budget: 1000,
    tier: "III",
    naf: false,
    descriptionFr: "Les Renégats du Chaos sont des équipes composées de joueurs de différentes races unis par leur rejet de l'ordre. Leurs équipes sont variées et imprévisibles.",
    descriptionEn: "Chaos Renegades are teams composed of players from different races united by their rejection of order. Their teams are varied and unpredictable.",
    regionalRules: ["favoured_of"],
    specialRules: undefined,
    positions: [
      {
        slug: "chaos_renegade_human_lineman",
        displayName: "Renegade Human Linemen",
        cost: 50,
        min: 0,
        max: 12,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "",
      },
      {
        slug: "chaos_renegade_human_thrower",
        displayName: "Renegade Human Thrower",
        cost: 75,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "animosity,pass,safe-pair-of-hands",
      },
      {
        slug: "chaos_renegade_goblin",
        displayName: "Renegade Goblin",
        cost: 40,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "animosity,dodge,right-stuff,stunty",
      },
      {
        slug: "chaos_renegade_orc",
        displayName: "Renegade Orc",
        cost: 50,
        min: 0,
        max: 1,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_skaven",
        displayName: "Renegade Skaven",
        cost: 50,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_dark_elf",
        displayName: "Renegade Dark Elf",
        cost: 75,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_troll",
        displayName: "Renegade Troll",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
      {
        slug: "chaos_renegade_ogre",
        displayName: "Renegade Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
      },
      {
        slug: "chaos_renegade_minotaur",
        displayName: "Renegade Minotaur",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "frenzy,horns,loner-5,mighty-blow-1,thick-skull,wild-animal",
      },
      {
        slug: "chaos_renegade_rat_ogre",
        displayName: "Renegade Rat Ogre",
        cost: 150,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "animal-savagery,frenzy,loner-5,mighty-blow-1,prehensile-tail",
      },
    ],
  },
  ogre: {
    name: "Ogres",
    budget: 1000,
    tier: "IV",
    naf: false,
    descriptionFr: "Les Ogres sont des géants puissants mais peu intelligents, accompagnés de leurs serviteurs Gnoblars. Leurs équipes sont très fortes mais manquent de finesse.",
    descriptionEn: "Ogres are powerful but unintelligent giants, accompanied by their Gnoblar servants. Their teams are very strong but lack finesse.",
    regionalRules: ["badlands_brawl", "old_world_classic"],
    specialRules: undefined,
    positions: [
      {
        slug: "ogre_gnoblar_lineman",
        displayName: "Gnoblar Linemen",
        cost: 15,
        min: 0,
        max: 16,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 5,
        av: 6,
        skills: "dodge,right-stuff,sidestep,stunty,titchy",
      },
      {
        slug: "ogre_runt_punter",
        displayName: "Ogre Runt Punter",
        cost: 145,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 4,
        av: 10,
        skills: "bone-head,kick-team-mate,loner-5,mighty-blow-1,thick-skull",
      },
      {
        slug: "ogre_blocker",
        displayName: "Ogre Blocker",
        cost: 140,
        min: 0,
        max: 5,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
      },
    ],
  },
  halfling: {
    name: "Halflings",
    budget: 1000,
    tier: "IV",
    naf: false,
    descriptionFr: "Les Halflings sont de petits joueurs agiles mais très fragiles. Leurs équipes Blood Bowl sont rapides mais vulnérables, souvent accompagnées d'un Treeman pour la protection.",
    descriptionEn: "Halflings are small, agile but very fragile players. Their Blood Bowl teams are fast but vulnerable, often accompanied by a Treeman for protection.",
    regionalRules: ["halfling_thimble_cup", "old_world_classic"],
    specialRules: undefined,
    positions: [
      {
        slug: "halfling_hopeful_lineman",
        displayName: "Halfling Hopeful Linemen",
        cost: 30,
        min: 0,
        max: 16,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,right-stuff,stunty",
      },
      {
        slug: "halfling_hefty",
        displayName: "Halfling Hefty",
        cost: 50,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,fend,stunty",
      },
      {
        slug: "halfling_catcher",
        displayName: "Halfling Catcher",
        cost: 55,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 5,
        av: 7,
        skills: "catch,dodge,right-stuff,sprint,stunty",
      },
      {
        slug: "halfling_altern_forest_treeman",
        displayName: "Altern Forest Treeman",
        cost: 120,
        min: 0,
        max: 2,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "loner-5,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate,timmm-ber",
      },
    ],
  },
  underworld: {
    name: "Bas-Fonds",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Bas-Fonds sont une équipe mixte composée de Skavens et de Gobelins mutants. Leurs équipes combinent agilité et utilisation d'armes secrètes.",
    descriptionEn: "Underworld Denizens are a mixed team composed of Skaven and mutant Goblins. Their teams combine agility with the use of secret weapons.",
    regionalRules: ["underworld_challenge"],
    specialRules: undefined,
    positions: [
      {
        slug: "underworld_underworld_goblin_lineman",
        displayName: "Underworld Goblin Linemen",
        cost: 40,
        min: 0,
        max: 12,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,right-stuff,stunty",
      },
      {
        slug: "underworld_underworld_snotling",
        displayName: "Underworld Snotling",
        cost: 15,
        min: 0,
        max: 6,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 5,
        av: 6,
        skills: "dodge,right-stuff,sidestep,stunty,titchy",
      },
      {
        slug: "underworld_skaven_clanrat",
        displayName: "Skaven Clanrat",
        cost: 50,
        min: 0,
        max: 3,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "animosity-underworld",
      },
      {
        slug: "underworld_skaven_thrower",
        displayName: "Skaven Thrower",
        cost: 85,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 2,
        av: 8,
        skills: "animosity-underworld,pass,sure-hands",
      },
      {
        slug: "underworld_gutter_runner",
        displayName: "Gutter Runner",
        cost: 85,
        min: 0,
        max: 1,
        ma: 9,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "animosity-underworld,dodge",
      },
      {
        slug: "underworld_skaven_blitzer",
        displayName: "Skaven Blitzer",
        cost: 90,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 5,
        av: 9,
        skills: "animosity-underworld,block",
      },
      {
        slug: "underworld_underworld_troll",
        displayName: "Underworld Troll",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
      {
        slug: "underworld_mutant_rat_ogre",
        displayName: "Mutant Rat Ogre",
        cost: 150,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "animal-savagery,frenzy,loner-5,mighty-blow-1,prehensile-tail",
      },
    ],
  },
  chaos_chosen: {
    name: "Élus du Chaos",
    budget: 1000,
    tier: "III",
    naf: false,
    descriptionFr: "Les Élus du Chaos sont des guerriers dévoués aux dieux du Chaos, développant des mutations au fil du temps. Leurs équipes deviennent plus puissantes avec l'expérience.",
    descriptionEn: "Chaos Chosen are warriors dedicated to the Chaos gods, developing mutations over time. Their teams become more powerful with experience.",
    regionalRules: ["favoured_of"],
    specialRules: undefined,
    positions: [
      {
        slug: "chaos_chosen_beastman_runner_lineman",
        displayName: "Beastman Runner Linemen",
        cost: 60,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "horns",
      },
      {
        slug: "chaos_chosen_chosen_blocker",
        displayName: "Chosen Blocker",
        cost: 100,
        min: 0,
        max: 4,
        ma: 5,
        st: 4,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "",
      },
      {
        slug: "chaos_chosen_chaos_troll",
        displayName: "Chaos Troll",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
      {
        slug: "chaos_chosen_chaos_ogre",
        displayName: "Chaos Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
      },
      {
        slug: "chaos_chosen_minotaur",
        displayName: "Minotaur",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "frenzy,horns,loner-5,mighty-blow-1,thick-skull,wild-animal",
      },
    ],
  },
  imperial_nobility: {
    name: "Noblesse Impériale",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "La Noblesse Impériale représente l'élite de l'Empire, combinant compétences nobles et serviteurs dévoués. Leurs équipes sont équilibrées et polyvalentes.",
    descriptionEn: "Imperial Nobility represents the elite of the Empire, combining noble skills and devoted servants. Their teams are balanced and versatile.",
    regionalRules: ["old_world_classic"],
    specialRules: undefined,
    positions: [
      {
        slug: "imperial_nobility_imperial_retainer_lineman",
        displayName: "Imperial Retainer Linemen",
        cost: 45,
        min: 0,
        max: 12,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 4,
        av: 8,
        skills: "fend",
      },
      {
        slug: "imperial_nobility_imperial_thrower",
        displayName: "Imperial Thrower",
        cost: 75,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "pass,running-pass",
      },
      {
        slug: "imperial_nobility_noble_blitzer",
        displayName: "Noble Blitzer",
        cost: 105,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,catch",
      },
      {
        slug: "imperial_nobility_bodyguard",
        displayName: "Bodyguard",
        cost: 90,
        min: 0,
        max: 4,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 5,
        av: 9,
        skills: "stand-firm,wrestle",
      },
      {
        slug: "imperial_nobility_ogre",
        displayName: "Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
      },
    ],
  },
  necromantic_horror: {
    name: "Horreurs Nécromantiques",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les Horreurs Nécromantiques sont des créatures ressuscitées par la magie nécromantique, combinant morts-vivants et créatures monstrueuses. Leurs équipes sont résistantes et dangereuses.",
    descriptionEn: "Necromantic Horrors are creatures resurrected by necromantic magic, combining undead and monstrous creatures. Their teams are resilient and dangerous.",
    regionalRules: ["sylvanian_spotlight"],
    specialRules: undefined,
    positions: [
      {
        slug: "necromantic_horror_zombie_lineman",
        displayName: "Zombie Linemen",
        cost: 40,
        min: 0,
        max: 16,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "regeneration",
      },
      {
        slug: "necromantic_horror_ghoul_runner",
        displayName: "Ghoul Runner",
        cost: 75,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge",
      },
      {
        slug: "necromantic_horror_wraith",
        displayName: "Wraith",
        cost: 95,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "block,foul-appearance,no-hands,regeneration,sidestep",
      },
      {
        slug: "necromantic_horror_werewolf",
        displayName: "Werewolf",
        cost: 125,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "claws,frenzy,regeneration",
      },
      {
        slug: "necromantic_horror_flesh_golem",
        displayName: "Flesh Golem",
        cost: 115,
        min: 0,
        max: 2,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "regeneration,stand-firm,thick-skull",
      },
    ],
  },
  orc: {
    name: "Orques",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les Orques sont une race brutale et agressive, connue pour leur force et leur violence. Leurs équipes Blood Bowl sont puissantes et spécialisées dans le blocage offensif.",
    descriptionEn: "Orcs are a brutal and aggressive race, known for their strength and violence. Their Blood Bowl teams are powerful and specialize in offensive blocking.",
    regionalRules: ["badlands_brawl"],
    specialRules: undefined,
    positions: [
      {
        slug: "orc_orc_lineman",
        displayName: "Orc Linemen",
        cost: 50,
        min: 0,
        max: 16,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "animosity",
      },
      {
        slug: "orc_thrower",
        displayName: "Thrower",
        cost: 65,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "animosity-all,pass,sure-hands",
      },
      {
        slug: "orc_blitzer",
        displayName: "Blitzer",
        cost: 80,
        min: 0,
        max: 4,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "animosity-all,block",
      },
      {
        slug: "orc_big_un_blocker",
        displayName: "Big Un Blocker",
        cost: 90,
        min: 0,
        max: 4,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "animosity",
      },
      {
        slug: "orc_goblin",
        displayName: "Goblin",
        cost: 40,
        min: 0,
        max: 4,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,right-stuff,stunty",
      },
      {
        slug: "orc_untrained_troll",
        displayName: "Untrained Troll",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
    ],
  },
  nurgle: {
    name: "Nurgle",
    budget: 1000,
    tier: "III",
    naf: false,
    descriptionFr: "Les équipes de Nurgle sont dédiées au dieu de la peste et de la décomposition. Leurs joueurs sont résistants et peuvent transmettre des maladies à leurs adversaires.",
    descriptionEn: "Nurgle teams are dedicated to the god of plague and decay. Their players are resilient and can spread diseases to their opponents.",
    regionalRules: ["favoured_of"],
    specialRules: undefined,
    positions: [
      {
        slug: "nurgle_rotter_lineman",
        displayName: "Rotter Linemen",
        cost: 35,
        min: 0,
        max: 12,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "decay,plague-ridden",
      },
      {
        slug: "nurgle_pestigor",
        displayName: "Pestigor",
        cost: 75,
        min: 0,
        max: 4,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "horns,plague-ridden,regeneration",
      },
      {
        slug: "nurgle_bloater",
        displayName: "Bloater",
        cost: 115,
        min: 0,
        max: 4,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "disturbing-presence,foul-appearance,plague-ridden,regeneration",
      },
      {
        slug: "nurgle_rotspawn",
        displayName: "Rotspawn",
        cost: 140,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "disturbing-presence,foul-appearance,loner-5,mighty-blow-1,plague-ridden,really-stupid-2,regeneration,tentacles",
      },
    ],
  },
  old_world_alliance: {
    name: "Alliance du Vieux Monde",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "L'Alliance du Vieux Monde est une équipe mixte composée de Humains, Nains et Halflings. Leurs équipes combinent les forces de différentes races pour créer une équipe équilibrée.",
    descriptionEn: "The Old World Alliance is a mixed team composed of Humans, Dwarves and Halflings. Their teams combine the strengths of different races to create a balanced team.",
    regionalRules: ["old_world_classic"],
    specialRules: undefined,
    positions: [
      {
        slug: "old_world_alliance_old_world_human_lineman",
        displayName: "Old World Human Linemen",
        cost: 50,
        min: 0,
        max: 12,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "",
      },
      {
        slug: "old_world_alliance_old_world_human_thrower",
        displayName: "Old World Human Thrower",
        cost: 80,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "animosity-all-dwarf-halfling,pass,sure-hands",
      },
      {
        slug: "old_world_alliance_old_world_human_catcher",
        displayName: "Old World Human Catcher",
        cost: 65,
        min: 0,
        max: 1,
        ma: 8,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "animosity-all-dwarf-halfling,catch,dodge",
      },
      {
        slug: "old_world_alliance_old_world_human_blitzer",
        displayName: "Old World Human Blitzer",
        cost: 90,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "animosity-all-dwarf-halfling,block",
      },
      {
        slug: "old_world_alliance_old_world_dwarf_blocker",
        displayName: "Old World Dwarf Blocker",
        cost: 75,
        min: 0,
        max: 2,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "arm-bar,brawler,loner-4,thick-skull",
      },
      {
        slug: "old_world_alliance_old_world_dwarf_runner",
        displayName: "Old World Dwarf Runner",
        cost: 85,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "loner-4,sure-hands,thick-skull",
      },
      {
        slug: "old_world_alliance_old_world_dwarf_blitzer",
        displayName: "Old World Dwarf Blitzer",
        cost: 80,
        min: 0,
        max: 1,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "block,loner-4,thick-skull",
      },
      {
        slug: "old_world_alliance_old_world_dwarf_troll_slayer",
        displayName: "Old World Dwarf Troll Slayer",
        cost: 95,
        min: 0,
        max: 1,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "block,dauntless,frenzy,loner-4,thick-skull",
      },
      {
        slug: "old_world_alliance_old_world_halfling_hopeful",
        displayName: "Old World Halfling Hopeful",
        cost: 30,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "animosity-all-dwarf-human,dodge,right-stuff,stunty",
      },
      {
        slug: "old_world_alliance_ogre",
        displayName: "Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
      },
      {
        slug: "old_world_alliance_altern_forest_treeman",
        displayName: "Altern Forest Treeman",
        cost: 120,
        min: 0,
        max: 1,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "loner-5,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate,timmm-ber",
      },
    ],
  },
  elven_union: {
    name: "Union Elfique",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "L'Union Elfique est une équipe composée d'elfes de différentes nations unies. Leurs équipes combinent agilité et compétences de passe pour un jeu rapide et élégant.",
    descriptionEn: "The Elven Union is a team composed of elves from different united nations. Their teams combine agility and passing skills for fast and elegant play.",
    regionalRules: ["elven_kingdoms_league"],
    specialRules: undefined,
    positions: [
      {
        slug: "elven_union_lineman",
        displayName: "Linemen",
        cost: 60,
        min: 0,
        max: 12,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "elven_union_thrower",
        displayName: "Thrower",
        cost: 75,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "pass",
      },
      {
        slug: "elven_union_catcher",
        displayName: "Catcher",
        cost: 100,
        min: 0,
        max: 4,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "catch,nerves-of-steel",
      },
      {
        slug: "elven_union_blitzer",
        displayName: "Blitzer",
        cost: 115,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "block,sidestep",
      },
    ],
  },
  human: {
    name: "Humains",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les Humains sont une race polyvalente et adaptable, capable de jouer tous les styles de jeu. Leurs équipes Blood Bowl sont équilibrées et peuvent s'adapter à différentes stratégies.",
    descriptionEn: "Humans are a versatile and adaptable race, capable of playing all styles of play. Their Blood Bowl teams are balanced and can adapt to different strategies.",
    regionalRules: ["old_world_classic"],
    specialRules: undefined,
    positions: [
      {
        slug: "human_human_lineman",
        displayName: "Human Linemen",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "",
      },
      {
        slug: "human_thrower",
        displayName: "Thrower",
        cost: 80,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 2,
        av: 9,
        skills: "pass,sure-hands",
      },
      {
        slug: "human_catcher",
        displayName: "Catcher",
        cost: 65,
        min: 0,
        max: 4,
        ma: 8,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "catch,dodge",
      },
      {
        slug: "human_blitzer",
        displayName: "Blitzer",
        cost: 85,
        min: 0,
        max: 4,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block",
      },
      {
        slug: "human_halfling_hopeful",
        displayName: "Halfling Hopeful",
        cost: 30,
        min: 0,
        max: 3,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,right-stuff,stunty",
      },
      {
        slug: "human_ogre",
        displayName: "Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,loner-5,mighty-blow-1,thick-skull,throw-team-mate",
      },
    ],
  },
  black_orc: {
    name: "Orques Noirs",
    budget: 1000,
    tier: "III",
    naf: false,
    descriptionFr: "Les Orques Noirs sont des guerriers disciplinés et bien équipés, plus organisés que les Orques standards. Leurs équipes Blood Bowl sont puissantes et mieux structurées.",
    descriptionEn: "Black Orcs are disciplined and well-equipped warriors, more organized than standard Orcs. Their Blood Bowl teams are powerful and better structured.",
    regionalRules: ["badlands_brawl"],
    specialRules: undefined,
    positions: [
      {
        slug: "black_orc_goblin_bruiser_lineman",
        displayName: "Goblin Bruiser Linemen",
        cost: 45,
        min: 0,
        max: 12,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,right-stuff,stunty,thick-skull",
      },
      {
        slug: "black_orc_black_orc",
        displayName: "Black Orc",
        cost: 90,
        min: 0,
        max: 6,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "brawler,grab",
      },
      {
        slug: "black_orc_trained_troll",
        displayName: "Trained Troll",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-5,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
    ],
  },
  chaos_dwarf: {
    name: "Nains du Chaos",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Nains du Chaos sont des nains corrompus par le Chaos, combinant la résistance des nains avec la brutalité du Chaos. Leurs équipes sont résistantes et agressives.",
    descriptionEn: "Chaos Dwarves are dwarves corrupted by Chaos, combining dwarven resilience with Chaos brutality. Their teams are resilient and aggressive.",
    regionalRules: ["badlands_brawl", "worlds_edge_superleague", "favoured_of"],
    specialRules: undefined,
    positions: [
      {
        slug: "chaos_dwarf_hobgoblin_lineman",
        displayName: "Hobgoblin Linemen",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "shadowing",
      },
      {
        slug: "chaos_dwarf_hobgoblin_sneaky_stabba",
        displayName: "Hobgoblin Sneaky Stabba",
        cost: 70,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "stab",
      },
      {
        slug: "chaos_dwarf_chaos_dwarf_blocker",
        displayName: "Chaos Dwarf Blocker",
        cost: 70,
        min: 0,
        max: 4,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "block,iron-hard-skin,thick-skull",
      },
      {
        slug: "chaos_dwarf_chaos_dwarf_flamesmith",
        displayName: "Chaos Dwarf Flamesmith",
        cost: 80,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "brawler",
      },
      {
        slug: "chaos_dwarf_bull_centaur_blitzer",
        displayName: "Bull Centaur Blitzer",
        cost: 130,
        min: 0,
        max: 2,
        ma: 6,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "disturbing-presence,thick-skull,sprint,sure-feet",
      },
      {
        slug: "chaos_dwarf_renegade_minotaur",
        displayName: "Renegade Minotaur",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "thick-skull,frenzy,horns,loner-4,mighty-blow-1,wild-animal",
      },
    ],
  },
  slann: {
    name: "Slann",
    budget: 1000,
    tier: "II",
    naf: true,
    descriptionFr: "Les Slann sont une race ancienne de grenouilles humanoïdes de Lustrie, connus pour leur agilité et leur capacité de saut exceptionnelle. Leurs équipes Blood Bowl sont rapides et acrobatiques.",
    descriptionEn: "Slann are an ancient race of humanoid frogs from Lustria, known for their agility and exceptional jumping ability. Their Blood Bowl teams are fast and acrobatic.",
    regionalRules: ["lustrian_superleague"],
    specialRules: undefined,
    positions: [
      {
        slug: "slann_lineman",
        displayName: "Lineman",
        cost: 60,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "pogo-stick,very-long-legs",
      },
      {
        slug: "slann_catcher",
        displayName: "Catcher",
        cost: 80,
        min: 0,
        max: 4,
        ma: 7,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "diving-catch,pogo-stick,very-long-legs",
      },
      {
        slug: "slann_blitzer",
        displayName: "Blitzer",
        cost: 110,
        min: 0,
        max: 4,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "diving-tackle,jump-up,pogo-stick,very-long-legs",
      },
      {
        slug: "slann_kroxigor",
        displayName: "Kroxigor",
        cost: 140,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "bone-head,loner-4,mighty-blow-1,prehensile-tail,thick-skull",
      },
    ],
  },
  amazon: {
    name: "Amazones",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Amazones sont des guerrières féroces de Lustrie, connues pour leur agilité et leur compétence au combat. Leurs équipes Blood Bowl sont rapides et agressives.",
    descriptionEn: "Amazons are fierce warriors from Lustria, known for their agility and combat prowess. Their Blood Bowl teams are fast and aggressive.",
    regionalRules: ["lustrian_superleague"],
    specialRules: undefined,
    positions: [
      {
        slug: "amazon_lineman",
        displayName: "Trois-Quart Aigle",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "shadowing",
      },
      {
        slug: "amazon_thrower",
        displayName: "Lanceuse Pythée",
        cost: 80,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "pass,accurate",
      },
      {
        slug: "amazon_catcher",
        displayName: "Receveuse Nymphe",
        cost: 90,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "dodge,sprint",
      },
      {
        slug: "amazon_blitzer",
        displayName: "Bloqueuse Jaguar",
        cost: 110,
        min: 0,
        max: 2,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 5,
        av: 9,
        skills: "block",
      },
    ],
  },
  high_elf: {
    name: "Hauts Elfes",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Quand Blood Bowl atteignit Ulthuan pour la première fois, il y eut beaucoup de nez retroussés et de 'tut' méprisants, car cela semblait n'être rien de plus que deux équipes de voyous incivilisés qui se frappaient sans raison. Il devint rapidement évident que ce n'était pas la seule façon de jouer, cependant, et dans les années qui suivirent, les équipes de Hauts Elfes révolutionnèrent le jeu de passe du sport. Ils ont de nombreux avantages quand il s'agit de gagner (par opposition à massacrer l'adversaire, ce qui n'est pas toujours la même chose !), et leurs excellents joueurs sont l'épitomé du côté le plus gracieux du jeu. Le seul vrai problème avec les équipes de Hauts Elfes est qu'elles peuvent être très pointilleuses sur qui, quand ou où elles jouent, alors nous devons être reconnaissants qu'elles daignent jouer contre des races inférieures !",
    descriptionEn: "When Blood Bowl first reached Ulthuan, there was much turning up of noses and loud disdainful tutting, for it appeared as nothing more than two teams of uncivilised yobs pummelling each other senseless. It quickly became apparent that this was not the sole way of playing, however, and in the years that followed High Elf teams revolutionised the sport's passing game. They have many advantages when it comes to winning (as opposed to slaughtering the opposition, which isn't always the same thing!), and their fine players are the epitome of the more graceful side of the game. The only real problem with High Elf teams is that they can be very picky about who, when or where they play, so we must be thankful they deign to play lesser races at all!",
    regionalRules: ["elven_kingdoms_league"],
    specialRules: "NONE",
    positions: [
      {
        slug: "high_elf_lineman",
        displayName: "High Elf Lineman",
        cost: 65,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "",
      },
      {
        slug: "high_elf_thrower",
        displayName: "High Elf Thrower",
        cost: 100,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 2,
        av: 9,
        skills: "cloud-burster,pass,safe-pass",
      },
      {
        slug: "high_elf_catcher",
        displayName: "High Elf Catcher",
        cost: 90,
        min: 0,
        max: 4,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "catch",
      },
      {
        slug: "high_elf_blitzer",
        displayName: "High Elf Blitzer",
        cost: 100,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 9,
        skills: "block",
      },
    ],
  },
  khorne: {
    name: "Khorne",
    budget: 1000,
    tier: "III",
    naf: false,
    descriptionFr: "Les équipes de Khorne sont dédiées au dieu du sang et du combat. Leurs joueurs sont des berserkers violents qui recherchent la destruction de leurs adversaires.",
    descriptionEn: "Khorne teams are dedicated to the god of blood and combat. Their players are violent berserkers who seek the destruction of their opponents.",
    regionalRules: ["favoured_of"],
    specialRules: undefined,
    positions: [
      {
        slug: "khorne_marauder",
        displayName: "Marauder",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "khorne_khorngor",
        displayName: "Khorngor",
        cost: 70,
        min: 0,
        max: 4,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "thick-skull,frenzy",
      },
      {
        slug: "khorne_bloodletter",
        displayName: "Bloodletter",
        cost: 110,
        min: 0,
        max: 4,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "thick-skull,iron-hard-skin",
      },
      {
        slug: "khorne_bloodspawn",
        displayName: "Bloodspawn",
        cost: 160,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "thick-skull,frenzy,loner-4,mighty-blow-1,wild-animal",
      },
    ],
  },
  vampire: {
    name: "Vampires",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les équipes de Vampires sont composées de maîtres vampires et de leurs serviteurs Thralls. Les vampires sont puissants mais doivent contrôler leur soif de sang.",
    descriptionEn: "Vampire teams are composed of master vampires and their Thrall servants. Vampires are powerful but must control their bloodlust.",
    regionalRules: ["sylvanian_spotlight"],
    specialRules: undefined,
    positions: [
      {
        slug: "vampire_vampire",
        displayName: "Vampire",
        cost: 110,
        min: 0,
        max: 16,
        ma: 6,
        st: 4,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "hypnotic-gaze,regeneration",
      },
      {
        slug: "vampire_thrall",
        displayName: "Thrall",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "",
      },
    ],
  },
  tomb_kings: {
    name: "Rois des Tombes",
    budget: 1000,
    tier: "II",
    naf: false,
    descriptionFr: "Les Rois des Tombes sont des équipes de morts-vivants égyptiens ressuscités, combinant squelettes et créatures momifiées. Leurs équipes sont résistantes et mystérieuses.",
    descriptionEn: "Tomb Kings are teams of resurrected Egyptian undead, combining skeletons and mummified creatures. Their teams are resilient and mysterious.",
    regionalRules: ["sylvanian_spotlight"],
    specialRules: undefined,
    positions: [
      {
        slug: "tomb_kings_skeleton",
        displayName: "Squelette",
        cost: 40,
        min: 0,
        max: 16,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 4,
        av: 8,
        skills: "regeneration",
      },
      {
        slug: "tomb_kings_tomb_guardian",
        displayName: "Gardien des Tombes",
        cost: 100,
        min: 0,
        max: 4,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "block,thick-skull,regeneration",
      },
      {
        slug: "tomb_kings_thrower",
        displayName: "Lanceur",
        cost: 70,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "pass,accurate,regeneration",
      },
      {
        slug: "tomb_kings_blitzer",
        displayName: "Blitzer",
        cost: 90,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "block,thick-skull,regeneration",
      },
    ],
  },
  gnome: {
    name: "Gnomes",
    budget: 1000,
    tier: "IV",
    naf: false,
    descriptionFr: "Les Gnomes sont de petits joueurs agiles mais très fragiles, souvent accompagnés de créatures sauvages. Leurs équipes Blood Bowl sont imprévisibles et excentriques.",
    descriptionEn: "Gnomes are small, agile but very fragile players, often accompanied by wild creatures. Their Blood Bowl teams are unpredictable and eccentric.",
    regionalRules: ["halfling_thimble_cup"],
    specialRules: undefined,
    positions: [
      {
        slug: "gnome_lineman",
        displayName: "Trois-Quart Coureur",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,thick-skull",
      },
      {
        slug: "gnome_gnome_with_piston",
        displayName: "Gnome avec pilonneuse",
        cost: 70,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 5,
        av: 9,
        skills: "iron-hard-skin",
      },
      {
        slug: "gnome_dynamite_thrower",
        displayName: "Lanceur de Dynamite",
        cost: 80,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "pass",
      },
      {
        slug: "gnome_beastmaster",
        displayName: "Maître des bêtes Gnomes",
        cost: 90,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "iron-hard-skin",
      },
      {
        slug: "gnome_treeman",
        displayName: "Homme-Arbre",
        cost: 120,
        min: 0,
        max: 1,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 6,
        av: 11,
        skills: "guard,iron-hard-skin,loner-4,mighty-blow-1,stand-firm,take-root,wild-animal",
      },
    ],
  },
  norse: {
    name: "Nordiques",
    budget: 1000,
    tier: "I",
    naf: false,
    descriptionFr: "Les Nordiques sont des guerriers vikings féroces des terres du nord, connus pour leur bravoure et leur résistance au froid. Leurs équipes Blood Bowl sont agressives et résistantes.",
    descriptionEn: "Norse are fierce Viking warriors from the northern lands, known for their bravery and cold resistance. Their Blood Bowl teams are aggressive and resilient.",
    regionalRules: ["old_world_classic", "favoured_of"],
    specialRules: undefined,
    positions: [
      {
        slug: "norse_lineman",
        displayName: "Ligne-Quart",
        cost: 70,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,thick-skull",
      },
      {
        slug: "norse_runner",
        displayName: "Coureur à bâton",
        cost: 70,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "shadowing,thick-skull,dodge",
      },
      {
        slug: "norse_thrower",
        displayName: "Lanceur",
        cost: 70,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "pass,accurate,thick-skull",
      },
      {
        slug: "norse_valkyrie",
        displayName: "Valkyrie",
        cost: 90,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "thick-skull,dodge,sprint,leap",
      },
      {
        slug: "norse_ulfwernar",
        displayName: "Ulfwernar",
        cost: 110,
        min: 0,
        max: 2,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "block,thick-skull,frenzy",
      },
      {
        slug: "norse_yhetee",
        displayName: "Yhetee",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "thick-skull,frenzy,claws,loner-4,mighty-blow-1,wild-animal",
      },
    ],
  },
  snotling: {
    name: "Snotlings",
    budget: 1000,
    tier: "IV",
    naf: false,
    descriptionFr: "Les Snotlings sont les plus petits et les plus faibles des gobelinoïdes, mais ils compensent par leur nombre et leur utilisation d'armes secrètes. Leurs équipes sont chaotiques et imprévisibles.",
    descriptionEn: "Snotlings are the smallest and weakest of goblinoids, but they compensate with their numbers and use of secret weapons. Their teams are chaotic and unpredictable.",
    regionalRules: ["underworld_challenge"],
    specialRules: undefined,
    positions: [
      {
        slug: "snotling_snotling_lineman",
        displayName: "Snotling",
        cost: 15,
        min: 0,
        max: 16,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 5,
        av: 6,
        skills: "animosity-underworld,projectile-vomit,animal-savagery,always-hungry,really-stupid-2,right-stuff,stunty,titchy",
      },
      {
        slug: "snotling_fungus_flinga",
        displayName: "Fungus Flinga",
        cost: 30,
        min: 0,
        max: 2,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "animosity-underworld,projectile-vomit,animal-savagery,really-stupid-2,right-stuff,secret-weapon",
      },
      {
        slug: "snotling_fun_hoppa",
        displayName: "Fan Happa",
        cost: 20,
        min: 0,
        max: 2,
        ma: 6,
        st: 1,
        ag: 3,
        pa: 5,
        av: 6,
        skills: "animosity-all-dwarf-halfling,animosity-all-dwarf-human,pogo-stick,animal-savagery,really-stupid-2,right-stuff",
      },
      {
        slug: "snotling_stilty_runna",
        displayName: "Milky Snotling",
        cost: 20,
        min: 0,
        max: 2,
        ma: 6,
        st: 1,
        ag: 3,
        pa: 5,
        av: 6,
        skills: "animosity-underworld,pogo-stick,animal-savagery,really-stupid-2,right-stuff,swarming",
      },
      {
        slug: "snotling_pump_wagon",
        displayName: "Pump Wagon",
        cost: 105,
        min: 0,
        max: 2,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 6,
        av: 9,
        skills: "armored-skull,dirty-player-1,juggernaut,mighty-blow-1,secret-weapon,stand-firm,thick-skull",
      },
      {
        slug: "snotling_trained_troll",
        displayName: "Trained Troll",
        cost: 115,
        min: 0,
        max: 2,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "always-hungry,loner-3,mighty-blow-1,projectile-vomit,really-stupid-2,regeneration,throw-team-mate",
      },
    ],
  },
};

const cloneRoster = (roster: TeamRoster): TeamRoster => ({
  ...roster,
  positions: roster.positions.map((position) => ({ ...position })),
});

const cloneRosterMap = (source: TeamRosterMap): TeamRosterMap =>
  Object.fromEntries(
    Object.entries(source).map(([slug, roster]) => [slug, cloneRoster(roster)]),
  );

export const TEAM_ROSTERS_BY_RULESET: Record<Ruleset, TeamRosterMap> = {
  season_2: SEASON_TWO_ROSTERS,
  season_3: cloneRosterMap(SEASON_TWO_ROSTERS),
};

export const TEAM_ROSTERS = TEAM_ROSTERS_BY_RULESET[DEFAULT_RULESET];

const getRostersForRuleset = (ruleset: Ruleset = DEFAULT_RULESET): TeamRosterMap => {
  return TEAM_ROSTERS_BY_RULESET[ruleset] ?? TEAM_ROSTERS_BY_RULESET[DEFAULT_RULESET];
};

// Fonction utilitaire pour obtenir une position par son slug
export function getPositionBySlug(
  slug: string,
  ruleset: Ruleset = DEFAULT_RULESET,
): PositionDefinition | null {
  const rosterMap = getRostersForRuleset(ruleset);
  for (const roster of Object.values(rosterMap)) {
    const position = roster.positions.find((p) => p.slug === slug);
    if (position) return position;
  }
  if (ruleset !== DEFAULT_RULESET) {
    return getPositionBySlug(slug, DEFAULT_RULESET);
  }
  return null;
}

// Fonction utilitaire pour obtenir toutes les positions d'une équipe
export function getTeamPositions(
  teamRoster: string,
  ruleset: Ruleset = DEFAULT_RULESET,
): PositionDefinition[] {
  const roster = getRostersForRuleset(ruleset)[teamRoster];
  if (roster) {
    return roster.positions;
  }
  if (ruleset !== DEFAULT_RULESET) {
    return getTeamPositions(teamRoster, DEFAULT_RULESET);
  }
  return [];
}

// Fonction utilitaire pour obtenir le nom d'affichage d'un slug
export function getDisplayName(slug: string, ruleset: Ruleset = DEFAULT_RULESET): string {
  const position = getPositionBySlug(slug, ruleset);
  return position ? position.displayName : slug;
}

// Fonction utilitaire pour obtenir le slug à partir du nom d'affichage et de l'équipe
export function getSlugFromDisplayName(
  displayName: string,
  teamRoster: string,
  ruleset: Ruleset = DEFAULT_RULESET,
): string | null {
  const positions = getTeamPositions(teamRoster, ruleset);
  const position = positions.find((p) => p.displayName === displayName);
  if (position) {
    return position.slug;
  }
  if (ruleset !== DEFAULT_RULESET) {
    return getSlugFromDisplayName(displayName, teamRoster, DEFAULT_RULESET);
  }
  return null;
}

// Mapping des anciennes clés vers les nouveaux slugs (pour migration)
export const LEGACY_POSITION_MAPPING: Record<string, string> = {
  // Skaven
  "lineman": "skaven_lineman",
  "thrower": "skaven_thrower", 
  "blitzer": "skaven_blitzer",
  "gutter": "skaven_gutter_runner",
  "gutter_runner": "skaven_gutter_runner",
  "ratogre": "skaven_rat_ogre",
  "rat_ogre": "skaven_rat_ogre",
  
  // Lizardmen
  "skink": "lizardmen_skink_runner",
  "lizardmen_skink": "lizardmen_skink_runner", // Migration ancien slug
  "chameleon_skink": "lizardmen_chameleon_skink",
  "saurus": "lizardmen_saurus",
  "kroxigor": "lizardmen_kroxigor",
};
