/**
 * Rosters Saison 3 de Blood Bowl
 * Générés automatiquement à partir de mordorbihan.fr
 * Source: https://mordorbihan.fr/fr/bloodbowl/2025/equipes
 * 
 * Ces données sont conformes aux règles Saison 3 (2025)
 */

import type { TeamRoster } from './positions';

export const SEASON_THREE_ROSTERS: Record<string, TeamRoster> = {
  old_world_alliance: {
    name: "Alliance du Vieux Monde",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "old_world_alliance_trois_quart_humain",
        displayName: "Trois-Quart Humain",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "",
      },
      {
        slug: "old_world_alliance_aspirant_halfling",
        displayName: "Aspirant Halfling",
        cost: 30,
        min: 0,
        max: 3,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,titchy,right-stuff",
      },
      {
        slug: "old_world_alliance_trois_quart_nain",
        displayName: "Trois-Quart Nain",
        cost: 70,
        min: 0,
        max: 3,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "block,thick-skull,defensive",
      },
      {
        slug: "old_world_alliance_lanceur_humain",
        displayName: "Lanceur Humain",
        cost: 75,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "pass,sure-hands",
      },
      {
        slug: "old_world_alliance_receveur_humain",
        displayName: "Receveur Humain",
        cost: 75,
        min: 0,
        max: 1,
        ma: 8,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,catch",
      },
      {
        slug: "old_world_alliance_coureur_nain",
        displayName: "Coureur Nain",
        cost: 80,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "thick-skull,sure-hands,sprint",
      },
      {
        slug: "old_world_alliance_blitzer_humain",
        displayName: "Blitzer Humain",
        cost: 85,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,tackle",
      },
      {
        slug: "old_world_alliance_tueur_de_trolls_nain",
        displayName: "Tueur de Trolls Nain",
        cost: 95,
        min: 0,
        max: 1,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 5,
        av: 9,
        skills: "block,thick-skull,frenzy,hate,dauntless",
      },
      {
        slug: "old_world_alliance_blitzer_nain",
        displayName: "Blitzer Nain",
        cost: 100,
        min: 0,
        max: 1,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 4,
        av: 10,
        skills: "block,thick-skull,tackle,diving-tackle",
      },
      {
        slug: "old_world_alliance_homme_arbre",
        displayName: "Homme-arbre *",
        cost: 120,
        min: 0,
        max: 1,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "strong-arm,mighty-blow-1,thick-skull,throw-team-mate,take-root,stand-firm,timmm-ber",
      },
      {
        slug: "old_world_alliance_ogre",
        displayName: "Ogre *",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,throw-team-mate,loner-3",
      }
    ],
  },

  amazon: {
    name: "Amazones",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "amazon_guerriere_aigle",
        displayName: "Guerrière Aigle",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge",
      },
      {
        slug: "amazon_guerriere_python",
        displayName: "Guerrière Python",
        cost: 80,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,pass,safe-pass,on-the-ball",
      },
      {
        slug: "amazon_guerriere_piranha",
        displayName: "Guerrière Piranha",
        cost: 90,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,hit-and-run,jump-up",
      },
      {
        slug: "amazon_guerriere_jaguar",
        displayName: "Guerrière Jaguar",
        cost: 110,
        min: 0,
        max: 2,
        ma: 6,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "defensive,dodge",
      }
    ],
  },

  underworld: {
    name: "Bas-Fonds",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "underworld_gobelin_des_bas_fond",
        displayName: "Gobelin des Bas-Fond",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,titchy,right-stuff",
      },
      {
        slug: "underworld_snotling_des_bas_fond",
        displayName: "Snotling des Bas-Fond",
        cost: 15,
        min: 0,
        max: 6,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "dodge,sidestep,insignifiant,stunty,titchy,right-stuff",
      },
      {
        slug: "underworld_skaven_du_clan_du_rat",
        displayName: "Skaven du Clan du Rat",
        cost: 50,
        min: 0,
        max: 3,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "animosity-underworld",
      },
      {
        slug: "underworld_lanceur_skaven",
        displayName: "Lanceur Skaven",
        cost: 80,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 2,
        av: 8,
        skills: "animosity-underworld,pass,sure-hands",
      },
      {
        slug: "underworld_coureur_d_egout",
        displayName: "Coureur d'égout",
        cost: 85,
        min: 0,
        max: 1,
        ma: 9,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "animosity-underworld,dodge,stab",
      },
      {
        slug: "underworld_blitzer_skaven",
        displayName: "Blitzer Skaven",
        cost: 90,
        min: 0,
        max: 1,
        ma: 8,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "animosity-underworld,strip-ball,block",
      },
      {
        slug: "underworld_troll",
        displayName: "Troll *",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,loner-4,always-hungry",
      },
      {
        slug: "underworld_rat_ogre",
        displayName: "Rat-ogre *",
        cost: 150,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,frenzy,prehensile-tail,animal-savagery,loner-4",
      }
    ],
  },

  dark_elf: {
    name: "Elfes noirs",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "dark_elf_trois_quart_elfe_noir",
        displayName: "Trois-quart Elfe Noir",
        cost: 65,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "",
      },
      {
        slug: "dark_elf_coureur_elfe_noir",
        displayName: "Coureur Elfe Noir",
        cost: 80,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "clearance,dump-off",
      },
      {
        slug: "dark_elf_assassin_elfe_noir",
        displayName: "Assassin Elfe Noir",
        cost: 90,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "hit-and-run,stab,shadowing",
      },
      {
        slug: "dark_elf_blitzer_elfe_noir",
        displayName: "Blitzer Elfe Noir",
        cost: 105,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "block",
      },
      {
        slug: "dark_elf_furie_elfe_noire",
        displayName: "Furie Elfe Noire",
        cost: 110,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "dodge,frenzy,jump-up",
      }
    ],
  },

  wood_elf: {
    name: "Elfes sylvains",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "wood_elf_trois_quart_elfe_sylvain",
        displayName: "Trois-quart Elfe Sylvain",
        cost: 65,
        min: 0,
        max: 12,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "",
      },
      {
        slug: "wood_elf_lanceur_elfe_sylvain",
        displayName: "Lanceur Elfe Sylvain",
        cost: 85,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "safe-pair-of-hands,pass",
      },
      {
        slug: "wood_elf_receveur_elfe_sylvain",
        displayName: "Receveur Elfe Sylvain",
        cost: 90,
        min: 0,
        max: 2,
        ma: 8,
        st: 2,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "dodge,catch,sprint",
      },
      {
        slug: "wood_elf_danceur_de_guerre",
        displayName: "Danceur de Guerre",
        cost: 130,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "block,dodge,leap",
      },
      {
        slug: "wood_elf_homme_arbre_de_la_loren",
        displayName: "Homme-Arbre de la Loren",
        cost: 120,
        min: 0,
        max: 1,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "strong-arm,mighty-blow-1,thick-skull,throw-team-mate,take-root,loner-4,stand-firm",
      }
    ],
  },

  chaos_chosen: {
    name: "Élus du Chaos",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "chaos_chosen_trois_quart_homme_bete",
        displayName: "Trois-quart Homme-bête",
        cost: 55,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "horns,thick-skull",
      },
      {
        slug: "chaos_chosen_bloqueur_elu",
        displayName: "Bloqueur Élu",
        cost: 100,
        min: 0,
        max: 4,
        ma: 5,
        st: 4,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "arm-bar",
      },
      {
        slug: "chaos_chosen_troll_du_chaos",
        displayName: "Troll du Chaos *",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,loner-4,always-hungry",
      },
      {
        slug: "chaos_chosen_ogre_du_chaos",
        displayName: "Ogre du Chaos *",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,throw-team-mate,loner-4",
      },
      {
        slug: "chaos_chosen_minotaure",
        displayName: "Minotaure *",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,horns,thick-skull,frenzy,wild-animal,loner-4",
      }
    ],
  },

  gnome: {
    name: "Gnomes",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "gnome_trois_quart_gnome",
        displayName: "Trois-quart Gnome",
        cost: 40,
        min: 0,
        max: 16,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "wrestle,titchy,right-stuff,jump-up",
      },
      {
        slug: "gnome_gnome_illusioniste",
        displayName: "Gnome Illusioniste",
        cost: 50,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 3,
        av: 7,
        skills: "trickster,wrestle,titchy,jump-up",
      },
      {
        slug: "gnome_renard_sylvestre",
        displayName: "Renard Sylvestre",
        cost: 50,
        min: 0,
        max: 2,
        ma: 7,
        st: 2,
        ag: 2,
        pa: 6,
        av: 6,
        skills: "dodge,sidestep,my-ball,titchy",
      },
      {
        slug: "gnome_belluaire_gnome",
        displayName: "Belluaire Gnome",
        cost: 55,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "guard,wrestle,titchy,jump-up",
      },
      {
        slug: "gnome_homme_arbre",
        displayName: "Homme-Arbre",
        cost: 120,
        min: 0,
        max: 2,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "strong-arm,mighty-blow-1,thick-skull,throw-team-mate,take-root,stand-firm,timmm-ber",
      }
    ],
  },

  goblin: {
    name: "Gobelins",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "goblin_gobelin",
        displayName: "Gobelin",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,titchy,right-stuff",
      },
      {
        slug: "goblin_troll_entraine",
        displayName: "Troll entrainé",
        cost: 115,
        min: 0,
        max: 2,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,always-hungry",
      },
      {
        slug: "goblin_cingle",
        displayName: "Cinglé",
        cost: 40,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "secret-weapon,dodge,titchy,no-hands,chainsaw",
      },
      {
        slug: "goblin_bomba",
        displayName: "Bomba",
        cost: 45,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "secret-weapon,bombardier,dodge,titchy",
      },
      {
        slug: "goblin_ouligan",
        displayName: "Ouligan'",
        cost: 60,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "dodge,dirty-player-1,titchy,right-stuff,disturbing-presence,provocation",
      },
      {
        slug: "goblin_plongeur_de_la_mort",
        displayName: "Plongeur de la Mort",
        cost: 65,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "dodge,titchy,pile-on,right-stuff",
      },
      {
        slug: "goblin_fanatique",
        displayName: "Fanatique",
        cost: 70,
        min: 0,
        max: 1,
        ma: 3,
        st: 7,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "secret-weapon,ball-and-chain,titchy,no-hands",
      },
      {
        slug: "goblin_echassier_a_ressort",
        displayName: "Échassier à ressort",
        cost: 75,
        min: 0,
        max: 1,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,titchy,pogo-stick",
      }
    ],
  },

  halfling: {
    name: "Halflings",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "halfling_aspirant_halfling",
        displayName: "Aspirant Halfling",
        cost: 30,
        min: 0,
        max: 16,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,titchy,right-stuff",
      },
      {
        slug: "halfling_balaise_halfling",
        displayName: "Balaise Halfling",
        cost: 50,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,titchy,fend",
      },
      {
        slug: "halfling_receveur_halfling",
        displayName: "Receveur Halfling",
        cost: 55,
        min: 0,
        max: 2,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,titchy,right-stuff,catch,sprint",
      },
      {
        slug: "halfling_homme_arbre_de_l_altern",
        displayName: "Homme-Arbre de l'Altern",
        cost: 120,
        min: 0,
        max: 2,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "strong-arm,mighty-blow-1,thick-skull,throw-team-mate,take-root,stand-firm,timmm-ber",
      }
    ],
  },

  high_elf: {
    name: "Hauts elfes",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "high_elf_trois_quart_haut_elfe",
        displayName: "Trois-quart Haut Elfe",
        cost: 65,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "",
      },
      {
        slug: "high_elf_receveur_haut_elfe",
        displayName: "Receveur Haut Elfe",
        cost: 90,
        min: 0,
        max: 4,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "catch",
      },
      {
        slug: "high_elf_lanceur_haut_elfe",
        displayName: "Lanceur Haut Elfe",
        cost: 100,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 2,
        av: 9,
        skills: "pass,safe-pass,cloud-burster",
      },
      {
        slug: "high_elf_blitzer_haut_elfe",
        displayName: "Blitzer Haut Elfe",
        cost: 100,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 4,
        av: 9,
        skills: "block",
      }
    ],
  },

  lizardmen: {
    name: "Hommes Lézard",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "lizardmen_trois_quart_skink",
        displayName: "Trois-quart Skink",
        cost: 60,
        min: 0,
        max: 16,
        ma: 8,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,titchy",
      },
      {
        slug: "lizardmen_bloqueur_saurus",
        displayName: "Bloqueur Saurus",
        cost: 90,
        min: 0,
        max: 6,
        ma: 6,
        st: 4,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "instable,juggernaut",
      },
      {
        slug: "lizardmen_skink_cameleon",
        displayName: "Skink Caméléon",
        cost: 70,
        min: 0,
        max: 2,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,titchy,shadowing,on-the-ball",
      },
      {
        slug: "lizardmen_kroxigor",
        displayName: "Kroxigor",
        cost: 140,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,prehensile-tail,loner-4",
      }
    ],
  },

  necromantic_horror: {
    name: "Horreurs nécromantiques",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "necromantic_horror_trois_quart_zombie",
        displayName: "Trois-quart Zombie",
        cost: 40,
        min: 0,
        max: 16,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "fork,instable,regeneration",
      },
      {
        slug: "necromantic_horror_coureur_goule",
        displayName: "Coureur Goule",
        cost: 75,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,regeneration",
      },
      {
        slug: "necromantic_horror_spectre",
        displayName: "Spectre",
        cost: 85,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "block,sidestep,regeneration,foul-appearance,no-hands",
      },
      {
        slug: "necromantic_horror_golem_de_chair",
        displayName: "Golem de chair",
        cost: 110,
        min: 0,
        max: 2,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "thick-skull,instable,regeneration,stand-firm",
      },
      {
        slug: "necromantic_horror_loup_garou",
        displayName: "Loup-Garou",
        cost: 120,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "frenzy,claws,regeneration",
      }
    ],
  },

  human: {
    name: "Humains",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "human_trois_quart",
        displayName: "Trois-Quart",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "",
      },
      {
        slug: "human_aspirant_halfling",
        displayName: "Aspirant Halfling",
        cost: 30,
        min: 0,
        max: 3,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,titchy,right-stuff",
      },
      {
        slug: "human_lanceur",
        displayName: "Lanceur",
        cost: 75,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "pass,sure-hands",
      },
      {
        slug: "human_receveur",
        displayName: "Receveur",
        cost: 75,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,catch",
      },
      {
        slug: "human_blitzer",
        displayName: "Blitzer",
        cost: 85,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,tackle",
      },
      {
        slug: "human_ogre",
        displayName: "Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,throw-team-mate,loner-3",
      }
    ],
  },

  khorne: {
    name: "Khorne",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "khorne_marauder_sanglant",
        displayName: "Marauder Sanglant",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "frenzy",
      },
      {
        slug: "khorne_rabatteur_sanglant",
        displayName: "Rabatteur Sanglant",
        cost: 105,
        min: 0,
        max: 4,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "frenzy",
      },
      {
        slug: "khorne_khorngor",
        displayName: "Khorngor",
        cost: 70,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "horns,thick-skull,juggernaut,jump-up",
      },
      {
        slug: "khorne_rejeton_sanglant",
        displayName: "Rejeton Sanglant",
        cost: 160,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,frenzy,wild-animal,claws,loner-4",
      }
    ],
  },

  undead: {
    name: "Morts ambulants",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "undead_trois_quart_squelette",
        displayName: "Trois-quart Squelette",
        cost: 40,
        min: 0,
        max: 16,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 8,
        skills: "thick-skull,regeneration",
      },
      {
        slug: "undead_trois_quart_zombie",
        displayName: "Trois-quart Zombie",
        cost: 40,
        min: 0,
        max: 16,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "fork,instable,regeneration",
      },
      {
        slug: "undead_coureur_goule",
        displayName: "Coureur Goule",
        cost: 75,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,regeneration",
      },
      {
        slug: "undead_blitzer_revenant",
        displayName: "Blitzer Revenant",
        cost: 90,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 5,
        av: 9,
        skills: "block,thick-skull,regeneration,tackle",
      },
      {
        slug: "undead_momie",
        displayName: "Momie",
        cost: 125,
        min: 0,
        max: 2,
        ma: 3,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "mighty-blow-1,regeneration",
      }
    ],
  },

  chaos_dwarf: {
    name: "Nains du chaos",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "chaos_dwarf_trois_quart_hobgobelin",
        displayName: "Trois-quart Hobgobelin",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "chaos_dwarf_bloqueur_nain_du_chaos",
        displayName: "Bloqueur Nain du Chaos",
        cost: 70,
        min: 0,
        max: 4,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "block,thick-skull,iron-hard-skin",
      },
      {
        slug: "chaos_dwarf_surineur_sournois",
        displayName: "Surineur sournois",
        cost: 60,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "stab,shadowing",
      },
      {
        slug: "chaos_dwarf_forgeflamme",
        displayName: "Forgeflamme",
        cost: 80,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "brawler,thick-skull,disturbing-presence,breathe-fire",
      },
      {
        slug: "chaos_dwarf_centaure_taureau",
        displayName: "Centaure taureau",
        cost: 130,
        min: 0,
        max: 2,
        ma: 6,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "thick-skull,sure-feet,instable,sprint",
      },
      {
        slug: "chaos_dwarf_minotaure",
        displayName: "Minotaure",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,horns,thick-skull,frenzy,wild-animal,loner-4",
      }
    ],
  },

  dwarf: {
    name: "Nains",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "dwarf_trois_quart_nain",
        displayName: "Trois-quart Nain",
        cost: 70,
        min: 0,
        max: 16,
        ma: 4,
        st: 3,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "block,thick-skull,defensive",
      },
      {
        slug: "dwarf_coureur_nain",
        displayName: "Coureur Nain",
        cost: 80,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "thick-skull,sure-hands,sprint",
      },
      {
        slug: "dwarf_tueur_de_trolls",
        displayName: "Tueur de Trolls",
        cost: 95,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 5,
        av: 9,
        skills: "block,thick-skull,frenzy,hate,dauntless",
      },
      {
        slug: "dwarf_blitzer_nain",
        displayName: "Blitzer Nain",
        cost: 100,
        min: 0,
        max: 2,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 4,
        av: 10,
        skills: "block,thick-skull,tackle,diving-tackle",
      },
      {
        slug: "dwarf_roule_mort",
        displayName: "Roule-Mort",
        cost: 170,
        min: 0,
        max: 1,
        ma: 5,
        st: 7,
        ag: 5,
        pa: 6,
        av: 11,
        skills: "secret-weapon,mighty-blow-1,break-tackle,dirty-player-1,juggernaut,no-hands,loner-4,stand-firm,tackle",
      }
    ],
  },

  imperial_nobility: {
    name: "Noblesse Impériale",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "imperial_nobility_valet_imperiale",
        displayName: "Valet impériale",
        cost: 45,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "fend",
      },
      {
        slug: "imperial_nobility_garde_du_corps",
        displayName: "Garde du corps",
        cost: 85,
        min: 0,
        max: 4,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "wrestle,stand-firm",
      },
      {
        slug: "imperial_nobility_lanceur_imperial",
        displayName: "Lanceur impérial",
        cost: 75,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 2,
        av: 9,
        skills: "pass,pro,running-pass-2025",
      },
      {
        slug: "imperial_nobility_blitzer_noble",
        displayName: "Blitzer Noble",
        cost: 90,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,pro,catch",
      },
      {
        slug: "imperial_nobility_ogre",
        displayName: "Ogre",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,throw-team-mate,loner-3",
      }
    ],
  },

  norse: {
    name: "Nordiques",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "norse_trois_quart",
        displayName: "Trois-Quart",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "block,thick-skull,instable,drunkard",
      },
      {
        slug: "norse_sanglier_a_biere",
        displayName: "Sanglier à bière",
        cost: 20,
        min: 0,
        max: 2,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 6,
        av: 6,
        skills: "dodge,stunty,titchy,pick-me-up,no-hands",
      },
      {
        slug: "norse_berzerker",
        displayName: "Berzerker",
        cost: 90,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "block,frenzy,jump-up",
      },
      {
        slug: "norse_valkyrie",
        displayName: "Valkyrie",
        cost: 95,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "strip-ball,dauntless,pass,catch",
      },
      {
        slug: "norse_ulfwerener",
        displayName: "Ulfwerener",
        cost: 105,
        min: 0,
        max: 2,
        ma: 6,
        st: 4,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "frenzy,instable",
      },
      {
        slug: "norse_yeti",
        displayName: "Yéti",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "frenzy,wild-animal,claws,disturbing-presence,loner-4",
      }
    ],
  },

  nurgle: {
    name: "Nurgle",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "nurgle_trois_quart_putrescent",
        displayName: "Trois-Quart Putrescent",
        cost: 40,
        min: 0,
        max: 16,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "contagieux,decay",
      },
      {
        slug: "nurgle_boursouffle",
        displayName: "Boursoufflé",
        cost: 110,
        min: 0,
        max: 4,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "contagieux,instable,disturbing-presence,regeneration,foul-appearance,stand-firm",
      },
      {
        slug: "nurgle_pestigor",
        displayName: "Pestigor",
        cost: 70,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "surefoot,contagieux,horns,thick-skull,regeneration",
      },
      {
        slug: "nurgle_rejeton_putride",
        displayName: "Rejeton Putride",
        cost: 140,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "mighty-blow-1,contagieux,really-stupid,pick-me-up,disturbing-presence,regeneration,foul-appearance,loner-4,tentacles",
      }
    ],
  },

  ogre: {
    name: "Ogres",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "ogre_trois_quart_gnoblar",
        displayName: "Trois-Quart Gnoblar",
        cost: 15,
        min: 0,
        max: 16,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "dodge,sidestep,stunty,titchy,right-stuff",
      },
      {
        slug: "ogre_bloqueur_ogre",
        displayName: "Bloqueur Ogre",
        cost: 140,
        min: 0,
        max: 5,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,throw-team-mate",
      },
      {
        slug: "ogre_botte_nabots_ogre",
        displayName: "Botte-nabots Ogre",
        cost: 145,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 4,
        av: 10,
        skills: "kick-team-mate,bone-head,mighty-blow-1,thick-skull",
      }
    ],
  },

  black_orc: {
    name: "Orques Noirs",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "black_orc_malabar_gobelin",
        displayName: "Malabar Gobelin",
        cost: 45,
        min: 0,
        max: 16,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "thick-skull,dodge,titchy,right-stuff",
      },
      {
        slug: "black_orc_orque_noir",
        displayName: "Orque Noir",
        cost: 90,
        min: 0,
        max: 6,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "brawler,grab",
      },
      {
        slug: "black_orc_troll_entraine",
        displayName: "Troll entrainé",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,always-hungry",
      }
    ],
  },

  orc: {
    name: "Orques",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "orc_trois_quart_orque",
        displayName: "Trois-quart Orque",
        cost: 50,
        min: 0,
        max: 16,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "",
      },
      {
        slug: "orc_trois_quart_gobelin",
        displayName: "Trois-quart Gobelin",
        cost: 40,
        min: 0,
        max: 4,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "dodge,titchy,right-stuff",
      },
      {
        slug: "orc_lanceur_orque",
        displayName: "Lanceur Orque",
        cost: 75,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "pass,sure-hands",
      },
      {
        slug: "orc_blitzer_orque",
        displayName: "Blitzer Orque",
        cost: 85,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "block,break-tackle",
      },
      {
        slug: "orc_bloqueur_kosto",
        displayName: "Bloqueur Kosto",
        cost: 95,
        min: 0,
        max: 2,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "mighty-blow-1,thick-skull,instable,provocation",
      },
      {
        slug: "orc_troll",
        displayName: "Troll",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,loner-4,always-hungry",
      }
    ],
  },

  chaos_renegade: {
    name: "Renégats du Chaos",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "chaos_renegade_trois_quart_humain_renegat",
        displayName: "Trois-Quart Humain Renégat",
        cost: 50,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_gobelin_renegat",
        displayName: "Gobelin Renégat",
        cost: 40,
        min: 0,
        max: 1,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "animosity,dodge,titchy,right-stuff",
      },
      {
        slug: "chaos_renegade_orque_renegat",
        displayName: "Orque Renégat",
        cost: 50,
        min: 0,
        max: 1,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_skaven_renegat",
        displayName: "Skaven Renégat",
        cost: 50,
        min: 0,
        max: 1,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_elf_noir_renegat",
        displayName: "Elf noir Renégat",
        cost: 65,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "animosity",
      },
      {
        slug: "chaos_renegade_lanceur_humain_renegat",
        displayName: "Lanceur Humain Renégat",
        cost: 75,
        min: 0,
        max: 1,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "animosity,pass,sure-hands",
      },
      {
        slug: "chaos_renegade_troll_renegat",
        displayName: "Troll Renégat",
        cost: 115,
        min: 0,
        max: 1,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,loner-4,always-hungry",
      },
      {
        slug: "chaos_renegade_ogre_renegat",
        displayName: "Ogre Renégat",
        cost: 140,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "bone-head,mighty-blow-1,thick-skull,throw-team-mate,loner-4",
      },
      {
        slug: "chaos_renegade_minotaure_renegat",
        displayName: "Minotaure Renégat",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,horns,thick-skull,frenzy,wild-animal,loner-4",
      },
      {
        slug: "chaos_renegade_rat_ogre_renegat",
        displayName: "Rat Ogre Renégat",
        cost: 150,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,frenzy,prehensile-tail,animal-savagery,loner-4",
      }
    ],
  },

  tomb_kings: {
    name: "Rois des tombes",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "tomb_kings_trois_quart_squelette",
        displayName: "Trois-quart Squelette",
        cost: 40,
        min: 0,
        max: 16,
        ma: 5,
        st: 3,
        ag: 4,
        pa: 6,
        av: 8,
        skills: "thick-skull,regeneration",
      },
      {
        slug: "tomb_kings_gardien_des_tombes",
        displayName: "Gardien des Tombes",
        cost: 115,
        min: 0,
        max: 4,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "brawler,decay,regeneration",
      },
      {
        slug: "tomb_kings_lanceur_des_rois_des_tombes",
        displayName: "Lanceur des Rois des Tombes",
        cost: 65,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 3,
        av: 9,
        skills: "thick-skull,pass,sure-hands,regeneration",
      },
      {
        slug: "tomb_kings_blitzer_des_rois_des_tombes",
        displayName: "Blitzer des Rois des Tombes",
        cost: 85,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 5,
        av: 9,
        skills: "block,thick-skull,regeneration",
      }
    ],
  },

  skaven: {
    name: "Skavens",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "skaven_rat_des_clans_skaven",
        displayName: "Rat des clans Skaven",
        cost: 50,
        min: 0,
        max: 16,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "skaven_lanceur_skaven",
        displayName: "Lanceur Skaven",
        cost: 80,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 2,
        av: 8,
        skills: "pass,sure-hands",
      },
      {
        slug: "skaven_coureur_d_egouts",
        displayName: "Coureur d'Égouts",
        cost: 85,
        min: 0,
        max: 2,
        ma: 9,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "dodge,stab",
      },
      {
        slug: "skaven_blitzer_skaven",
        displayName: "Blitzer Skaven",
        cost: 90,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "strip-ball,block",
      },
      {
        slug: "skaven_rat_ogre",
        displayName: "Rat Ogre",
        cost: 150,
        min: 0,
        max: 1,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,frenzy,prehensile-tail,animal-savagery,loner-4",
      }
    ],
  },

  snotling: {
    name: "Snotlings",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "snotling_trois_quart_snotling",
        displayName: "Trois-quart Snotling",
        cost: 15,
        min: 0,
        max: 16,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "dodge,sidestep,insignifiant,stunty,titchy,right-stuff",
      },
      {
        slug: "snotling_echassier",
        displayName: "Échassier",
        cost: 20,
        min: 0,
        max: 2,
        ma: 6,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "dodge,sidestep,titchy,right-stuff,sprint",
      },
      {
        slug: "snotling_r_bondisseur",
        displayName: "R'bondisseur",
        cost: 20,
        min: 0,
        max: 2,
        ma: 6,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "dodge,sidestep,titchy,pogo-stick,right-stuff",
      },
      {
        slug: "snotling_lance_champis",
        displayName: "Lance-champis",
        cost: 30,
        min: 0,
        max: 2,
        ma: 5,
        st: 1,
        ag: 3,
        pa: 4,
        av: 6,
        skills: "secret-weapon,bombardier,dodge,sidestep,stunty,titchy,right-stuff",
      },
      {
        slug: "snotling_chariot_a_pompe",
        displayName: "Chariot à Pompe",
        cost: 100,
        min: 0,
        max: 2,
        ma: 5,
        st: 5,
        ag: 5,
        pa: 6,
        av: 9,
        skills: "mighty-blow-1,really-stupid,dirty-player-1,juggernaut,stand-firm",
      },
      {
        slug: "snotling_troll_entraine",
        displayName: "Troll entrainé",
        cost: 115,
        min: 0,
        max: 2,
        ma: 4,
        st: 5,
        ag: 5,
        pa: 5,
        av: 10,
        skills: "mighty-blow-1,projectile-vomit,really-stupid,throw-team-mate,regeneration,always-hungry",
      }
    ],
  },

  elven_union: {
    name: "Union elfique",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "elven_union_trois_quart_elfe",
        displayName: "Trois-quart Elfe",
        cost: 65,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "fumblerooskie",
      },
      {
        slug: "elven_union_lanceur_elfe",
        displayName: "Lanceur Elfe",
        cost: 75,
        min: 0,
        max: 2,
        ma: 6,
        st: 3,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "pass,hail-mary-pass",
      },
      {
        slug: "elven_union_receveur_elfe",
        displayName: "Receveur Elfe",
        cost: 100,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "nerves-of-steel,catch,diving-catch",
      },
      {
        slug: "elven_union_blitzer_elfe",
        displayName: "Blitzer Elfe",
        cost: 115,
        min: 0,
        max: 2,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "block,sidestep",
      }
    ],
  },

  vampire: {
    name: "Vampires",
    budget: 1000,
    tier: "II",
    naf: false,
    positions: [
      {
        slug: "vampire_trois_quart_sbire",
        displayName: "Trois-quart Sbire",
        cost: 40,
        min: 0,
        max: 16,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "",
      },
      {
        slug: "vampire_coureur_vampire",
        displayName: "Coureur Vampire",
        cost: 100,
        min: 0,
        max: 2,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "hypnotic-gaze,regeneration,bloodlust",
      },
      {
        slug: "vampire_blitzer_vampire",
        displayName: "Blitzer Vampire",
        cost: 110,
        min: 0,
        max: 2,
        ma: 6,
        st: 4,
        ag: 2,
        pa: 4,
        av: 9,
        skills: "juggernaut,hypnotic-gaze,regeneration,bloodlust",
      },
      {
        slug: "vampire_lanceur_vampire",
        displayName: "Lanceur Vampire",
        cost: 110,
        min: 0,
        max: 2,
        ma: 6,
        st: 4,
        ag: 2,
        pa: 2,
        av: 9,
        skills: "pass,hypnotic-gaze,regeneration,bloodlust",
      },
      {
        slug: "vampire_vargheist",
        displayName: "Vargheist",
        cost: 150,
        min: 0,
        max: 1,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "frenzy,claws,regeneration,bloodlust,loner-4",
      }
    ],
  }
};
