/**
 * Système de Star Players de Blood Bowl
 * Les Star Players sont des mercenaires légendaires pouvant être recrutés par plusieurs équipes
 */
/**
 * Liste complète des Star Players disponibles
 */
export const STAR_PLAYERS = {
    glart_smashrip: {
        slug: "glart_smashrip",
        displayName: "Glart Smashrip",
        cost: 195000,
        ma: 9,
        st: 4,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "block,claw,juggernaut,loner-4,stand-firm",
        hirableBy: ["all"], // Favori de... ou Défi des Bas-fonds
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Favoris de...' ou 'Défi des Bas-fonds'. Une fois par match, quand Glart effectue un Blitz, il peut gagner la compétence Frénésie. Vous devez déclarer que cette règle spéciale est utilisée quand Glart est activé. Glart ne peut pas utiliser la compétence Projection pendant qu'il utilise cette règle spéciale."
    },
    gloriel_summerbloom: {
        slug: "gloriel_summerbloom",
        displayName: "Gloriel Summerbloom",
        cost: 150000,
        ma: 7,
        st: 2,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "accurate,dodge,loner-3,pass,side-step,safe-pair-of-hands",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Ligue des Royaumes Elfiques'. Tout ou Rien: Une fois par match, quand Gloriel effectue une Passe, elle peut gagner la compétence Passe Désespérée. Vous devez déclarer que cette règle spéciale est utilisée quand Gloriel est activée."
    },
    grak: {
        slug: "grak",
        displayName: "Grak",
        cost: 250000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 4,
        av: 10,
        skills: "bone-head,hurl-teammate,loner-4,mighty-blow-1,thick-skull",
        hirableBy: ["all"],
        specialRule: "Joue pour toute équipe. Deux pour Un!: Grak et Crumbleberry doivent être recrutés ensemble et comptent comme deux Star Players. Cependant, si Grak ou Crumbleberry est retiré du jeu à cause d'un résultat KO ou Éliminé! sur le tableau de Blessures, l'autre remplace le trait Solitaire (4+) par Solitaire (2+)."
    },
    crumbleberry: {
        slug: "crumbleberry",
        displayName: "Crumbleberry",
        cost: 0, // Inclus avec Grak
        ma: 5,
        st: 2,
        ag: 3,
        pa: 6,
        av: 7,
        skills: "dodge,loner-4,right-stuff,stunty,sure-feet",
        hirableBy: ["all"],
        specialRule: "Voir Grak - ils sont recrutés ensemble."
    },
    gretchen_wachter: {
        slug: "gretchen_wachter",
        displayName: "Gretchen Wächter 'La Veuve du Blood Bowl'",
        cost: 260000,
        ma: 7,
        st: 3,
        ag: 2,
        pa: null,
        av: 9,
        skills: "disturbing-presence,dodge,fend,jump-up,loner-4,no-hands,regeneration,side-step",
        hirableBy: ["sylvanian_spotlight"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Spot de Sylvanie'. Éthérée: Une fois par match, après un test d'Agilité pour esquiver, Gretchen peut décider de modifier le résultat en y ajoutant sa valeur de caractéristique Force."
    },
    griff_oberwald: {
        slug: "griff_oberwald",
        displayName: "Griff Oberwald",
        cost: 280000,
        ma: 7,
        st: 4,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "block,dodge,fend,loner-3,sprint,sure-feet",
        hirableBy: ["old_world_classic", "halfling_thimble_cup"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling' ou 'Classique du Vieux Monde'. Grand Professionnel: Une fois par match, Griff peut relancer un dé qui a été jeté soit pour un jet d'un seul dé, soit pour un jet de plusieurs dés ou faisant partie d'un groupe de dés (il ne peut pas s'agir d'un jeté pour un jet d'Armure, de Blessure ou d'Élimination)."
    },
    mighty_zug: {
        slug: "mighty_zug",
        displayName: "Mighty Zug",
        cost: 220000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "block,loner-4,mighty-blow-1",
        hirableBy: ["old_world_classic", "halfling_thimble_cup"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling', 'Classique du Vieux Monde' ou 'Super-ligue du Bord du Monde'. Coup Destructeur: Une fois par match, quand un joueur adverse est Plaqué en résultat d'un Blocage de Zug, vous pouvez appliquer un modificateur additionnel de +1 au jet d'Armure. Ce modificateur peut être appliqué après le jet de dés."
    },
    morg_n_thorg: {
        slug: "morg_n_thorg",
        displayName: "Morg 'n' Thorg",
        cost: 340000,
        ma: 6,
        st: 6,
        ag: 3,
        pa: 4,
        av: 11,
        skills: "block,hurl-teammate,loner-4,mighty-blow-2,thick-skull",
        hirableBy: ["all"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Spot de Sylvanie'. La Baliste: Une fois par match, si Morg rate le test de Passe quand il effectue une Passe ou un Lancer de Coéquipier, vous pouvez relancer le D6."
    },
    roxanna_darknail: {
        slug: "roxanna_darknail",
        displayName: "Roxanna Darknail",
        cost: 270000,
        ma: 8,
        st: 3,
        ag: 1,
        pa: 4,
        av: 8,
        skills: "dodge,frenzy,jump-up,juggernaut,leap,loner-4",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Ligue des Royaumes Elfiques'. Pointe de Vitesse: Une fois par match, Roxanna peut tenter de Foncer trois fois au lieu de deux. Vous devez déclarer que vous utilisez cette règle spéciale après que Roxanna a Foncé deux fois."
    },
    rumbelow_sheepskin: {
        slug: "rumbelow_sheepskin",
        displayName: "Rumbelow Sheepskin",
        cost: 170000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: null,
        av: 8,
        skills: "block,horns,juggernaut,loner-4,no-hands,tackle,thick-skull",
        hirableBy: ["old_world_classic", "halfling_thimble_cup"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling', 'Classique du Vieux Monde' ou 'Super-ligue du Bord du Monde'. Bélier: Une fois par match, quand un joueur adverse est Plaqué en résultat d'un Blocage de Rumbelow, vous pouvez appliquer un modificateur additionnel de +1 au jet d'Armure ou au jet de Blessure. Ce modificateur peut être appliqué après le jet de dés."
    },
    skrull_halfheight: {
        slug: "skrull_halfheight",
        displayName: "Skrull Halfheight",
        cost: 150000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "accurate,loner-4,nerves-of-steel,pass,regeneration,sure-hands,thick-skull",
        hirableBy: ["sylvanian_spotlight", "worlds_edge_superleague"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Spot de Sylvanie' ou 'Super-ligue du Bord du Monde'. Jeu de Passe Suprême: Une fois par match, après avoir effectué le test de Passe quand il effectue une Passe, Skrull peut décider de modifier le jet de dé en lui ajoutant sa valeur de caractéristique de Force."
    },
    grim_ironjaw: {
        slug: "grim_ironjaw",
        displayName: "Grim Ironjaw",
        cost: 200000,
        ma: 5,
        st: 4,
        ag: 3,
        pa: null,
        av: 9,
        skills: "block,dauntless,frenzy,loner-4,multiple-block,thick-skull",
        hirableBy: ["old_world_classic", "halfling_thimble_cup"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling', 'Classique du Vieux Monde' ou 'Super-ligue du Bord du Monde'. Tueur: Une fois par match, quand un joueur adverse avec une caractéristique Force de 5 ou plus est Plaqué en résultat d'un Blocage de Grim, vous pouvez appliquer un modificateur additionnel de +1 au jet d'Armure ou de Blessure. Ce modificateur peut être appliqué après le jet de dés."
    },
    hakflem_skuttlespike: {
        slug: "hakflem_skuttlespike",
        displayName: "Hakflem Skuttlespike",
        cost: 180000,
        ma: 9,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "dodge,extra-arms,loner-4,prehensile-tail,two-heads",
        hirableBy: ["underworld_challenge"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Favoris de...' ou 'Défi des Bas-fonds'. Traître: Une fois par match, si un équipier sur une case adjacente à Hakflem est en possession du ballon quand Hakflem est activé, ce joueur peut être immédiatement Plaqué et Hakflem peut prendre possession du ballon. L'utilisation de cette règle spéciale n'entraîne pas de Turnover."
    },
    helmut_wulf: {
        slug: "helmut_wulf",
        displayName: "Helmut Wulf",
        cost: 140000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: null,
        av: 9,
        skills: "chainsaw,loner-4,pro,secret-weapon,stand-firm",
        hirableBy: ["all"],
        specialRule: "Joue pour toute équipe. Vieux Pro: Une fois par match, Helmut peut utiliser sa compétence Pro pour relancer un seul dé d'un jet d'Armure."
    },
    karla_von_kill: {
        slug: "karla_von_kill",
        displayName: "Karla Von Kill",
        cost: 210000,
        ma: 6,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,dauntless,dodge,jump-up,loner-4",
        hirableBy: ["old_world_classic", "lustrian_superleague"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling', 'Super-ligue de Lustrie' ou 'Classique du Vieux Monde'. Indomptable: Une fois par match, quand Karla réussit son jet pour utiliser sa compétence Intrépide, elle peut augmenter sa caractéristique de Force pour être le double de celle de la cible de ce Blocage."
    },
    lord_borak: {
        slug: "lord_borak",
        displayName: "Lord Borak the Despoiler",
        cost: 260000,
        ma: 5,
        st: 5,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "block,dirty-player-2,loner-4,mighty-blow-1,sneaky-git",
        hirableBy: ["favoured_of"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Favoris de...'. Seigneur du Chaos: Une équipe qui inclut Lord Borak gagne une relance d'Équipe supplémentaire pour la première mi-temps. Si elle n'est pas utilisée pendant la première mi-temps, elle est transférée pour la seconde mi-temps. Cependant, si Lord Borak est retiré du jeu avant l'utilisation de cette relance, elle est alors perdue."
    },
    the_black_gobbo: {
        slug: "the_black_gobbo",
        displayName: "The Black Gobbo",
        cost: 225000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "bombardier,disturbing-presence,dodge,loner-3,side-step,sneaky-git,stab,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Bagarre des Terres Arides' ou 'Défi des Bas-fonds'. Le Plus Sournois de Tous: Si votre équipe inclut le Black Gobbo, vous pouvez relancer un jet d'Agression par tour d'équipe, tant que l'une d'elles est commise par le Black Gobbo."
    },
    deeproot_strongbranch: {
        slug: "deeproot_strongbranch",
        displayName: "Deeproot Strongbranch",
        cost: 280000,
        ma: 2,
        st: 7,
        ag: 5,
        pa: 4,
        av: 11,
        skills: "block,loner-4,mighty-blow-2,stand-firm,strong-arm,thick-skull,throw-team-mate,timmm-ber",
        hirableBy: ["old_world_classic", "halfling_thimble_cup"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling' ou 'Classique du Vieux Monde'. Fiable: Si Deeproot commet une maladresse avec l'action Lancer de Coéquipier, le joueur lancé rebondit automatiquement mais atterrit automatiquement sans pieds. L'utilisation de cette règle spéciale n'entraîne pas de Turnover."
    },
    eldril_sidewinder: {
        slug: "eldril_sidewinder",
        displayName: "Eldril Sidewinder",
        cost: 230000,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 5,
        av: 8,
        skills: "catch,dodge,hypnotic-gaze,loner-4,nerves-of-steel,on-the-ball",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Ligue des Royaumes Elfiques'. Danse Hypnotisante: Une fois par match, Eldril peut relancer un test d'Agilité raté quand il tente d'utiliser le trait Regard Hypnotique."
    },
    lucien_swift: {
        slug: "lucien_swift",
        displayName: "Lucien Swift",
        cost: 340000,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 5,
        av: 9,
        skills: "block,loner-4,mighty-blow-1,tackle",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Ligue des Royaumes Elfiques'. Deux pour Un: St Lucien ou Valen est retiré du jeu à cause d'un résultat K.-O. ou Éliminé! sur le tableau de Blessures, l'autre remplace le trait Solitaire (4+) par Solitaire (2+)."
    },
    valen_swift: {
        slug: "valen_swift",
        displayName: "Valen Swift",
        cost: 340000,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "accurate,loner-4,nerves-of-steel,pass,safe-pair-of-hands,sure-hands",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Voir Lucien Swift - ils sont recrutés ensemble."
    },
    varag_ghoul_chewer: {
        slug: "varag_ghoul_chewer",
        displayName: "Varag Ghoul-Chewer",
        cost: 280000,
        ma: 6,
        st: 5,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "block,jump-up,loner-4,mighty-blow-1,thick-skull",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Bagarre des Terres Arides' ou 'Défi des Bas-fonds'. Coup Destructeur: Une fois par match, quand un joueur adverse est Plaqué en résultat d'un Blocage de Varag, vous pouvez appliquer un modificateur additionnel de +1 au jet d'Armure. Ce modificateur peut être appliqué après le jet de dés."
    },
    grombrindal: {
        slug: "grombrindal",
        displayName: "Grombrindal, the White Dwarf",
        cost: 210000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "block,dauntless,loner-4,mighty-blow-1,stand-firm,thick-skull",
        hirableBy: ["old_world_classic", "worlds_edge_superleague"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Coupe Dé à Coudre Halfling', 'Super-ligue de Lustrie' ou 'Classique du Vieux Monde' ou 'Super-ligue du Bord du Monde'. Sagesse du Nain Blanc: Une fois par tour d'équipe, quand un des coéquipiers de Grombrindal se trouvant sur une case adjacente à lui est activé, ce joueur gagne la compétence Esquive en Force, Intrépide, Châtaigne (+1) ou Équilibre jusqu'à la fin de son activation."
    },
    willow_rosebark: {
        slug: "willow_rosebark",
        displayName: "Willow Rosebark",
        cost: 150000,
        ma: 5,
        st: 4,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "dauntless,loner-4,side-step,thick-skull",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Ligue des Royaumes Elfiques'. Indomptable: Une fois par match, quand Willow réussit son jet pour utiliser sa compétence Intrépide, elle peut augmenter sa caractéristique de Force pour être le double de celle de la cible de ce Blocage."
    },
    zolcath_the_zoat: {
        slug: "zolcath_the_zoat",
        displayName: "Zolcath le Zoat",
        cost: 230000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "disturbing-presence,juggernaut,loner-4,mighty-blow-1,prehensile-tail,regeneration,sure-feet",
        hirableBy: ["lustrian_superleague", "elven_kingdoms_league"],
        specialRule: "Joue pour toute équipe avec la règle spéciale 'Super-ligue de Lustrie' ou 'Ligue des Royaumes Elfiques'. 'Êtes-vous un Zoat?': Une fois par match, quand Zolcath est activé, il peut gagner le trait Regard Hypnotique. Vous devez déclarer que cette règle spéciale est utilisée quand Zolcath est activé."
    },
    // ===== STAR PLAYERS ADDITIONNELS (nufflezone.com) =====
    akhorne_the_squirrel: {
        slug: "akhorne_the_squirrel",
        displayName: "Akhorne l'Écureuil",
        cost: 80000,
        ma: 7,
        st: 1,
        ag: 2,
        pa: null,
        av: 6,
        skills: "claws,dauntless,dodge,frenzy,jump-up,loner-4,no-hands,side-step,stunty,titchy",
        hirableBy: ["all"],
        specialRule: "Blind Rage: Peut relancer le D6 pour Dauntless"
    },
    barik_farblast: {
        slug: "barik_farblast",
        displayName: "Barik Tireloin",
        cost: 80000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 3,
        av: 9,
        skills: "cannoneer,hail-mary-pass,loner-4,pass,secret-weapon,sure-hands,thick-skull",
        hirableBy: ["halfling_thimble_cup", "old_world_classic", "worlds_edge_superleague"],
        specialRule: "Blast It!: Peut relancer les résultats de déviation sur Hail Mary Pass"
    },
    bomber_dribblesnot: {
        slug: "bomber_dribblesnot",
        displayName: "Bomber Morvonez",
        cost: 50000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "bombardier,dodge,loner-4,secret-weapon,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Kaboom!: Résultats de bombes améliorés"
    },
    fungus_the_loon: {
        slug: "fungus_the_loon",
        displayName: "Fungus le Cinglé",
        cost: 80000,
        ma: 4,
        st: 7,
        ag: 3,
        pa: null,
        av: 8,
        skills: "ball-chain,loner-4,mighty-blow-1,no-hands,secret-weapon,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Whirling Dervish: Peut affecter plusieurs joueurs adjacents"
    },
    nobbla_blackwart: {
        slug: "nobbla_blackwart",
        displayName: "Nobbla La Teigne",
        cost: 120000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "block,chainsaw,dodge,loner-4,secret-weapon,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Chainsaw Expert: Améliore l'utilisation de la tronçonneuse"
    },
    ripper_bolgrot: {
        slug: "ripper_bolgrot",
        displayName: "Bolgrot l'Écrabouilleur",
        cost: 250000,
        ma: 4,
        st: 6,
        ag: 3,
        pa: null,
        av: 10,
        skills: "break-tackle,grab,juggernaut,loner-4,mighty-blow-1,really-stupid,thick-skull",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Crushing Blow: Bonus aux jets de blessure"
    },
    scrappa_sorehead: {
        slug: "scrappa_sorehead",
        displayName: "Scrappa Malocrâne",
        cost: 130000,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,leap,loner-4,right-stuff,sprint,stunty,sure-feet,very-long-legs",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Kaboom!: Améliore les lancers de bombe"
    },
    skitter_stab_stab: {
        slug: "skitter_stab_stab",
        displayName: "Skitter Stab-Stab",
        cost: 150000,
        ma: 9,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "dodge,loner-4,shadowing,stab,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Stab-Stab: Améliore l'efficacité de Stab"
    },
    kreek_rustgouger: {
        slug: "kreek_rustgouger",
        displayName: "Kreek Arracherouille",
        cost: 170000,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "loner-4,prehensile-tail,tackle,tentacles,two-heads,wrestle",
        hirableBy: ["favoured_of"],
        specialRule: "Watch Out!: Esquive gratuite lors du premier blocage reçu"
    },
    anqi_panqi: {
        slug: "anqi_panqi",
        displayName: "Anqi Panqi",
        cost: 190000,
        ma: 7,
        st: 4,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "block,grab,loner-4,stand-firm",
        hirableBy: ["lustrian_superleague"],
        specialRule: "Savage Blow: Peut relancer les dés de bloc"
    },
    boa_konssstriktor: {
        slug: "boa_konssstriktor",
        displayName: "Boa Kon'ssstriktor",
        cost: 200000,
        ma: 6,
        st: 5,
        ag: 2,
        pa: null,
        av: 10,
        skills: "bone-head,disturbing-presence,guard,loner-4,mighty-blow-1,prehensile-tail",
        hirableBy: ["lustrian_superleague"],
        specialRule: "Constrict: Peut immobiliser les adversaires"
    },
    cindy_piewhistle: {
        slug: "cindy_piewhistle",
        displayName: "Cindy Piffretarte",
        cost: 50000,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 3,
        av: 7,
        skills: "dodge,loner-4,right-stuff,stunty,sure-hands",
        hirableBy: ["halfling_thimble_cup"],
        specialRule: "Master Chef Assistant: Bonus aux relances"
    },
    count_luthor_von_drakenborg: {
        slug: "count_luthor_von_drakenborg",
        displayName: "Comte Luthor von Drakenborg",
        cost: 340000,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "block,hypnotic-gaze,juggernaut,loner-4,regeneration,side-step",
        hirableBy: ["sylvanian_spotlight"],
        specialRule: "Lord of the Undead: Améliore les jets de régénération"
    },
    bryce_cambuel: {
        slug: "bryce_cambuel",
        displayName: "Bryce 'Le tronçon' Cambuel",
        cost: 130000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "chainsaw,loner-4,secret-weapon,stand-firm,thick-skull",
        hirableBy: ["old_world_classic"],
        specialRule: "Lumberjack: Bonus avec la tronçonneuse"
    },
    estelle_la_veneaux: {
        slug: "estelle_la_veneaux",
        displayName: "Estelle la Veneaux",
        cost: 190000,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 2,
        av: 9,
        skills: "dodge,dump-off,jump-up,loner-4,no-hands,pass,safe-pair-of-hands",
        hirableBy: ["old_world_classic"],
        specialRule: "Incorporeal: Ignore certains blocages"
    },
    frank_n_stein: {
        slug: "frank_n_stein",
        displayName: "Frank 'n' Stein",
        cost: 250000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: null,
        av: 10,
        skills: "block,juggernaut,loner-4,mighty-blow-1,regeneration,stand-firm,thick-skull",
        hirableBy: ["sylvanian_spotlight"],
        specialRule: "Brutal Block: Améliore les blessures causées"
    },
    glotl_stop: {
        slug: "glotl_stop",
        displayName: "Glotl Stop",
        cost: 270000,
        ma: 6,
        st: 6,
        ag: 5,
        pa: null,
        av: 10,
        skills: "frenzy,loner-4,mighty-blow-1,prehensile-tail,thick-skull,wild-animal",
        hirableBy: ["lustrian_superleague"],
        specialRule: "Frenzied Rush: Améliore Frenzy"
    },
    grashnak_blackhoof: {
        slug: "grashnak_blackhoof",
        displayName: "Grashnak Noirsabot",
        cost: 240000,
        ma: 6,
        st: 6,
        ag: 4,
        pa: null,
        av: 9,
        skills: "frenzy,horns,loner-4,mighty-blow-1,thick-skull",
        hirableBy: ["badlands_brawl"],
        specialRule: "Devastating Charge: Bonus sur les charges"
    },
    ivan_deathshroud: {
        slug: "ivan_deathshroud",
        displayName: "Ivan 'l'Animal' Deathshroud",
        cost: 190000,
        ma: 6,
        st: 4,
        ag: 4,
        pa: null,
        av: 9,
        skills: "block,loner-4,regeneration,thick-skull",
        hirableBy: ["sylvanian_spotlight"],
        specialRule: "Unkillable: Améliore Regeneration"
    },
    ivar_eriksson: {
        slug: "ivar_eriksson",
        displayName: "Ivar Eriksson",
        cost: 245000,
        ma: 6,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,dauntless,jump-up,loner-4,pile-driver,stand-firm,thick-skull",
        hirableBy: ["old_world_classic", "favoured_of"],
        specialRule: "Bladestorm: Peut affecter plusieurs joueurs adjacents"
    },
    jeremiah_kool: {
        slug: "jeremiah_kool",
        displayName: "Jeremiah Kool",
        cost: 120000,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 2,
        av: 8,
        skills: "animosity-all,cannoneer,dodge,hail-mary-pass,loner-4,pass,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Hospital Pass: Peut passer malgré les marquages"
    },
    jordell_freshbreeze: {
        slug: "jordell_freshbreeze",
        displayName: "Jordell Flechevive",
        cost: 250000,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "block,diving-catch,dodge,jump-up,loner-4,side-step",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Catch of the Day: Améliore les réceptions"
    },
    karina_von_riesz: {
        slug: "karina_von_riesz",
        displayName: "Capitaine Karina von Riesz",
        cost: 230000,
        ma: 6,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,bloodlust-3,dauntless,hypnotic-gaze,jump-up,loner-4,stakes",
        hirableBy: ["sylvanian_spotlight"],
        specialRule: "Blood Frenzy: Peut mordre les joueurs ST≤3"
    },
    kiroth_krakeneye: {
        slug: "kiroth_krakeneye",
        displayName: "Kiroth Krakeneye",
        cost: 160000,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "foul-appearance,loner-4,pass,safe-pair-of-hands,sure-hands,tackle,tentacles",
        hirableBy: ["favoured_of"],
        specialRule: "Kraken's Embrace: Améliore Tentacles"
    },
    lord_borak_the_despoiler: {
        slug: "lord_borak_the_despoiler",
        displayName: "Lord Borak le Destructeur",
        cost: 260000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: null,
        av: 10,
        skills: "block,dirty-player-2,loner-4,mighty-blow-1,sneaky-git",
        hirableBy: ["favoured_of"],
        specialRule: "Despoiler: Améliore Dirty Player"
    },
    max_spleenripper: {
        slug: "max_spleenripper",
        displayName: "Max Eclaterate",
        cost: 130000,
        ma: 5,
        st: 4,
        ag: 4,
        pa: null,
        av: 9,
        skills: "chainsaw,loner-4,secret-weapon",
        hirableBy: ["favoured_of"],
        specialRule: "Frenzied Chainsaw: Chainsaw améliorée"
    },
    puggy_baconbreath: {
        slug: "puggy_baconbreath",
        displayName: "Puggy Haleinedebacon",
        cost: 120000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "block,dodge,loner-4,nerves-of-steel,right-stuff,stunty,thick-skull",
        hirableBy: ["halfling_thimble_cup", "old_world_classic"],
        specialRule: "Halfling Toss Master: Améliore Right Stuff"
    },
    rashnak_backstabber: {
        slug: "rashnak_backstabber",
        displayName: "Rashnak Backstabber",
        cost: 130000,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 6,
        av: 8,
        skills: "animosity-all,dodge,loner-4,side-step,sneaky-git,stab,stunty",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Treacherous: Double dommage sur Stab"
    },
    rodney_roachbait: {
        slug: "rodney_roachbait",
        displayName: "Rodney Roachbait",
        cost: 70000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "dodge,loner-4,right-stuff,stunty,wrestle",
        hirableBy: ["underworld_challenge"],
        specialRule: "Scurry: Améliore Dodge"
    },
    rowana_forestfoot: {
        slug: "rowana_forestfoot",
        displayName: "Rowana Forestfoot",
        cost: 160000,
        ma: 8,
        st: 2,
        ag: 2,
        pa: 5,
        av: 8,
        skills: "dodge,hypnotic-gaze,jump-up,loner-4,side-step,sprint,stunty",
        hirableBy: ["halfling_thimble_cup"],
        specialRule: "Forest's Blessing: Améliore Sprint"
    },
    scyla_anfingrimm: {
        slug: "scyla_anfingrimm",
        displayName: "Scyla Anfingrimm",
        cost: 200000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: null,
        av: 9,
        skills: "claws,frenzy,loner-4,mighty-blow-1,prehensile-tail,thick-skull,wild-animal",
        hirableBy: ["favoured_of"],
        specialRule: "Savage Mauler: Améliore Claw + Frenzy"
    },
    skrorg_snowpelt: {
        slug: "skrorg_snowpelt",
        displayName: "Skrorg Gelfourure",
        cost: 250000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: null,
        av: 9,
        skills: "block,claw,frenzy,loner-4,prehensile-tail,thick-skull",
        hirableBy: ["old_world_classic", "favoured_of"],
        specialRule: "Snow Troll Rage: Améliore Block"
    },
    swiftvine_glimmershard: {
        slug: "swiftvine_glimmershard",
        displayName: "Swiftvine Glimmershard",
        cost: 110000,
        ma: 8,
        st: 2,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "dodge,hypnotic-gaze,loner-4,side-step,stunty",
        hirableBy: ["elven_kingdoms_league"],
        specialRule: "Fey Charm: Améliore Hypnotic Gaze"
    },
    thorsson_stoutmead: {
        slug: "thorsson_stoutmead",
        displayName: "Thorsson Gueuledebière",
        cost: 170000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "block,loner-4,mighty-blow-1,pass-block,thick-skull",
        hirableBy: ["old_world_classic", "worlds_edge_superleague"],
        specialRule: "Dwarven Resilience: Améliore Block"
    },
    wilhelm_chaney: {
        slug: "wilhelm_chaney",
        displayName: "Wilhelm Chaney",
        cost: 220000,
        ma: 8,
        st: 4,
        ag: 3,
        pa: null,
        av: 8,
        skills: "catch,claw,frenzy,loner-4,regeneration,wrestle",
        hirableBy: ["sylvanian_spotlight"],
        specialRule: "Werewolf Form: Peut se transformer"
    },
    withergrasp_doubledrool: {
        slug: "withergrasp_doubledrool",
        displayName: "Withergrasp Doubledrool",
        cost: 170000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "loner-4,prehensile-tail,tackle,tentacles,two-heads,wrestle",
        hirableBy: ["favoured_of"],
        specialRule: "Watch Out!: Esquive au premier blocage reçu"
    },
    guffle_pusmaw: {
        slug: "guffle_pusmaw",
        displayName: "Guffle Pusmaw",
        cost: 200000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: null,
        av: 10,
        skills: "foul-appearance,loner-4,mighty-blow-1,nurgles-rot,regeneration,tentacles",
        hirableBy: ["favoured_of"],
        specialRule: "Nurgle's Blessing: Améliore Nurgle's Rot"
    },
    hthark_unstoppable: {
        slug: "hthark_unstoppable",
        displayName: "H'thark l'Imparable",
        cost: 300000,
        ma: 6,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "break-tackle,juggernaut,loner-4,mighty-blow-2,prehensile-tail,sprint,sure-feet,thick-skull",
        hirableBy: ["lustrian_superleague"],
        specialRule: "Unstoppable Charge: Améliore Juggernaut"
    },
    dribl_and_drull: {
        slug: "dribl_and_drull",
        displayName: "Dribl et Drull",
        cost: 190000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "animosity-all,dodge,loner-4,right-stuff,stunty,sure-hands,two-heads",
        hirableBy: ["badlands_brawl", "underworld_challenge"],
        specialRule: "Two Heads Are Better: Améliore Two Heads"
    },
    zzharg_madeye: {
        slug: "zzharg_madeye",
        displayName: "Zzharg Madeye",
        cost: 130000,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 3,
        av: 10,
        skills: "cannoneer,hail-mary-pass,loner-4,nerves-of-steel,secret-weapon,sure-hands,thick-skull",
        hirableBy: ["badlands_brawl", "favoured_of"],
        specialRule: "Blunderbuss Blast: Action spéciale de tir"
    },
    bilerot_vomitflesh: {
        slug: "bilerot_vomitflesh",
        displayName: "Bilerot Vomipeau",
        cost: 180000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "dirty-player-2,disturbing-presence,foul-appearance,loner-4,mighty-blow-1,nurgles-rot,plague-ridden,regeneration",
        hirableBy: ["favoured_of"],
        specialRule: "Vomit: Peut vomir sur les adversaires"
    },
    maple_highgrove: {
        slug: "maple_highgrove",
        displayName: "Mapple Hihgrove",
        cost: 210000,
        ma: 2,
        st: 6,
        ag: 5,
        pa: 6,
        av: 11,
        skills: "block,grab,loner-4,mighty-blow-1,stand-firm,strong-arm,take-root,thick-skull,throw-team-mate,timmm-ber",
        hirableBy: ["halfling_thimble_cup"],
        specialRule: "Treeman Strength: Améliore Throw Team-Mate"
    },
};
/**
 * Obtenir un Star Player par son slug
 */
export function getStarPlayerBySlug(slug) {
    return STAR_PLAYERS[slug];
}
/**
 * Obtenir tous les Star Players disponibles pour une équipe donnée
 * @param teamRoster - Le roster de l'équipe (ex: "skaven")
 * @param teamRegionalRules - Les règles régionales de l'équipe (ex: ["underworld_challenge"])
 */
export function getAvailableStarPlayers(teamRoster, teamRegionalRules = []) {
    return Object.values(STAR_PLAYERS).filter(starPlayer => {
        // Si le Star Player est disponible pour tous
        if (starPlayer.hirableBy.includes("all")) {
            return true;
        }
        // Vérifier si l'équipe a une des règles régionales requises
        return starPlayer.hirableBy.some(rule => teamRegionalRules.includes(rule));
    });
}
/**
 * Mapping des équipes vers leurs règles régionales
 */
export const TEAM_REGIONAL_RULES = {
    skaven: ["underworld_challenge"],
    lizardmen: ["lustrian_superleague"],
    wood_elf: ["elven_kingdoms_league"],
    dark_elf: ["elven_kingdoms_league"],
    dwarf: ["old_world_classic", "worlds_edge_superleague"],
    goblin: ["badlands_brawl", "underworld_challenge"],
    undead: ["sylvanian_spotlight"],
    chaos_renegade: ["favoured_of"],
    ogre: ["badlands_brawl", "old_world_classic"],
    halfling: ["halfling_thimble_cup", "old_world_classic"],
    underworld: ["underworld_challenge"],
    chaos_chosen: ["favoured_of"],
    imperial_nobility: ["old_world_classic"],
    necromantic_horror: ["sylvanian_spotlight"],
    orc: ["badlands_brawl"],
    nurgle: ["favoured_of"],
    old_world_alliance: ["old_world_classic"],
    elven_union: ["elven_kingdoms_league"],
    human: ["old_world_classic"],
    black_orc: ["badlands_brawl"],
    snotling: ["underworld_challenge"],
    high_elf: ["elven_kingdoms_league"],
    norse: ["old_world_classic", "favoured_of"],
    amazon: ["lustrian_superleague"],
    vampire: ["sylvanian_spotlight"],
    tomb_kings: ["sylvanian_spotlight"],
    khorne: ["favoured_of"],
    chaos_dwarf: ["badlands_brawl", "worlds_edge_superleague", "favoured_of"],
    gnome: ["halfling_thimble_cup"],
};
