/**
 * Système de Star Players de Blood Bowl
 * Les Star Players sont des mercenaires légendaires pouvant être recrutés par plusieurs équipes
 */
/**
 * Liste complète des Star Players disponibles
 */
export const STAR_PLAYERS = {
    akhorne_the_squirrel: {
        slug: "akhorne_the_squirrel",
        displayName: "Akhorne The Squirrel",
        cost: 80000,
        ma: 7,
        st: 1,
        ag: 2,
        pa: null,
        av: 6,
        skills: "claws,dauntless,dodge,frenzy,jump-up,loner-4,no-hands,sidestep,stunty",
        hirableBy: ["all"],
        imageUrl: "/data/Star-Players_files/Fungus-the-Loon.webp",
        specialRule: "Blind Rage: Peut relancer le D6 pour Intrépide."
    },
    anqi_panqi: {
        slug: "anqi_panqi",
        displayName: "Anqi Panqi",
        cost: 190000,
        ma: 7,
        st: 4,
        ag: 5,
        pa: 6,
        av: 10,
        skills: "block,grab,loner-4,stand-firm",
        hirableBy: ["lustrian_superleague"],
        imageUrl: "/data/Star-Players_files/Anqi-Panqi-star-player-.webp",
        specialRule: "Coup Sauvage: Une fois par partie, lorsqu'Anqi effectue une action de Blocage contre un joueur adverse, il peut choisir de relancer n'importe quel nombre de dés de Blocage."
    },
    barik_farblast: {
        slug: "barik_farblast",
        displayName: "Barik Farblast",
        cost: 80000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 3,
        av: 9,
        skills: "hail-mary-pass,loner-4,pass,secret-weapon,cannoneer,sure-hands,thick-skull",
        hirableBy: ["old_world_classic"],
        imageUrl: "/data/Star-Players_files/barik-farblast.webp"
    },
    bilerot_vomitflesh: {
        slug: "bilerot_vomitflesh",
        displayName: "Bilerot Vomitflesh",
        cost: 180000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "dirty-player-1,disturbing-presence,foul-appearance,loner-4",
        hirableBy: ["all"],
        imageUrl: undefined
    },
    the_black_gobbo: {
        slug: "the_black_gobbo",
        displayName: "The Black Gobbo",
        cost: 225000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 3,
        av: 9,
        skills: "secret-weapon,disturbing-presence,dodge,loner-4,sidestep,sneaky-git,stab,stunty",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Fungus-the-Loon.webp"
    },
    boa_konssstriktr: {
        slug: "boa_konssstriktr",
        displayName: "Boa Kon’ssstriktr",
        cost: 200000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "dodge,sidestep,prehensile-tail,loner-4,hypnotic-gaze",
        hirableBy: ["lustrian_superleague"],
        imageUrl: undefined
    },
    bomber_dribblesnot: {
        slug: "bomber_dribblesnot",
        displayName: "Bomber Dribblesnot",
        cost: 50000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 3,
        av: 8,
        skills: "accurate,secret-weapon,dodge,loner-4,stunty,right-stuff",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Bomber-Dribblesnot.webp"
    },
    bryce_the_slice_cambuel: {
        slug: "bryce_the_slice_cambuel",
        displayName: "Bryce ‘The Slice’ Cambuel",
        cost: 130000,
        ma: 5,
        st: 3,
        ag: 4,
        pa: null,
        av: 9,
        skills: "chainsaw,loner-4,regeneration,secret-weapon,stand-firm,thick-skull",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: "/data/Star-Players_files/Bryce-The-Slice-Cambuel-2023.webp"
    },
    cindy_piewhistle: {
        slug: "cindy_piewhistle",
        displayName: "Cindy Piewhistle",
        cost: 50000,
        ma: 5,
        st: 2,
        ag: 3,
        pa: 3,
        av: 7,
        skills: "secret-weapon,dodge,stunty,accurate,loner-4",
        hirableBy: ["old_world_classic"],
        imageUrl: "/data/Star-Players_files/Cindy_Piewhistle.webp"
    },
    deeproot_strongbranch: {
        slug: "deeproot_strongbranch",
        displayName: "Deeproot Strongbranch",
        cost: 280000,
        ma: 2,
        st: 7,
        ag: 5,
        pa: 4,
        av: 11,
        skills: "block,loner-4,mighty-blow-1,stand-firm,strong-arm,thick-skull,throw-team-mate,timmm-ber",
        hirableBy: ["old_world_classic"],
        imageUrl: "/data/Star-Players_files/deeproot-strongbranch.webp"
    },
    eldril_sidewinder: {
        slug: "eldril_sidewinder",
        displayName: "Eldril Sidewinder",
        cost: 230000,
        ma: 8,
        st: 3,
        ag: 2,
        pa: 5,
        av: 8,
        skills: "loner-4,dodge,nerves-of-steel,catch,hypnotic-gaze,on-the-ball",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: "/data/Star-Players_files/Eldril-Sidewinder.webp"
    },
    estelle_la_veneaux: {
        slug: "estelle_la_veneaux",
        displayName: "Estelle la Veneaux",
        cost: 190000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "dodge,guard,sidestep,disturbing-presence,loner-4",
        hirableBy: ["lustrian_superleague"],
        imageUrl: "/data/Star-Players_files/star-player-whitergrasp-doubledrool.webp"
    },
    frank_n_stein: {
        slug: "frank_n_stein",
        displayName: "Frank ‘n’ Stein",
        cost: 250000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: null,
        av: 10,
        skills: "break-tackle,loner-4,mighty-blow-1,regeneration,stand-firm,thick-skull",
        hirableBy: ["old_world_classic", "sylvanian_spotlight"],
        imageUrl: "/data/Star-Players_files/frank-n-stein.webp"
    },
    fungus_the_loon: {
        slug: "fungus_the_loon",
        displayName: "Fungus The Loon",
        cost: 80000,
        ma: 4,
        st: 7,
        ag: 3,
        pa: null,
        av: 8,
        skills: "secret-weapon,ball-and-chain,mighty-blow-1,stunty,loner-4,no-hands",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Fungus-the-Loon.webp"
    },
    glart_smashrip: {
        slug: "glart_smashrip",
        displayName: "Glart Smashrip",
        cost: 195000,
        ma: 5,
        st: 4,
        ag: 4,
        pa: null,
        av: 9,
        skills: "block,claws,juggernaut,grab,loner-4,stand-firm",
        hirableBy: ["underworld_challenge"],
        imageUrl: "/data/Star-Players_files/Glart-Smashrip.webp"
    },
    gloriel_summerbloom: {
        slug: "gloriel_summerbloom",
        displayName: "Gloriel Summerbloom",
        cost: 150000,
        ma: 7,
        st: 2,
        ag: 2,
        pa: 2,
        av: 8,
        skills: "accurate,dodge,loner-4,pass,sidestep,sure-hands",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: undefined
    },
    glotl_stop: {
        slug: "glotl_stop",
        displayName: "Glotl Stop",
        cost: 270000,
        ma: 6,
        st: 6,
        ag: 5,
        pa: null,
        av: 10,
        skills: "mighty-blow-1,thick-skull,frenzy,animal-savagery,prehensile-tail,loner-4,stand-firm",
        hirableBy: ["lustrian_superleague"],
        imageUrl: undefined
    },
    grashnak_blackhoof: {
        slug: "grashnak_blackhoof",
        displayName: "Grashnak Blackhoof",
        cost: 240000,
        ma: 6,
        st: 6,
        ag: 4,
        pa: null,
        av: 9,
        skills: "frenzy,horns,loner-4,mighty-blow-1,thick-skull,wild-animal",
        hirableBy: ["all"],
        imageUrl: "/data/Star-Players_files/Grashnak-Blackhoof.webp"
    },
    gretchen_wachter_the_blood_bowl_widow: {
        slug: "gretchen_wachter_the_blood_bowl_widow",
        displayName: "Gretchen Wachter “The Blood Bowl Widow”",
        cost: 260000,
        ma: 7,
        st: 3,
        ag: 2,
        pa: null,
        av: 9,
        skills: "disturbing-presence,dodge,foul-appearance,jump-up,loner-4,no-hands,regeneration,shadowing,sidestep",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: "/data/Star-Players_files/Skitter-Stab-Stab-blood-bowl-star-player.webp"
    },
    griff_oberwald: {
        slug: "griff_oberwald",
        displayName: "Griff Oberwald",
        cost: 280000,
        ma: 7,
        st: 4,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "loner-4,block,sure-feet,dodge,fend,sprint",
        hirableBy: ["old_world_classic"],
        imageUrl: undefined
    },
    grim_ironjaw: {
        slug: "grim_ironjaw",
        displayName: "Grim Ironjaw",
        cost: 200000,
        ma: 5,
        st: 4,
        ag: 3,
        pa: null,
        av: 9,
        skills: "loner-4,block,dauntless,frenzy,multiple-block,thick-skull",
        hirableBy: ["old_world_classic"],
        imageUrl: "/data/Star-Players_files/grim-ironjaw-card.webp"
    },
    grombrindal_the_white_dwarf: {
        slug: "grombrindal_the_white_dwarf",
        displayName: "Grombrindal, the White Dwarf",
        cost: 210000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 10,
        skills: "block,dauntless,loner-4,mighty-blow-1,stand-firm,thick-skull",
        hirableBy: ["lustrian_superleague", "old_world_classic"],
        imageUrl: "/data/Star-Players_files/Fungus-the-Loon.webp"
    },
    guffle_pussmaw: {
        slug: "guffle_pussmaw",
        displayName: "Guffle Pussmaw",
        cost: 180000,
        ma: 5,
        st: 4,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "plague-ridden,monstrous-mouth,bloodlust,foul-appearance,loner-4",
        hirableBy: ["all"],
        imageUrl: "/data/Star-Players_files/Guffle-Pussmaw-Star-Player.webp"
    },
    hakflem_skuttlespike: {
        slug: "hakflem_skuttlespike",
        displayName: "Hakflem Skuttlespike",
        cost: 210000,
        ma: 9,
        st: 3,
        ag: 2,
        pa: 3,
        av: 8,
        skills: "loner-4,extra-arms,two-heads,dodge,prehensile-tail",
        hirableBy: ["underworld_challenge"],
        imageUrl: "/data/Star-Players_files/Hakflem-Skuttlespike.webp"
    },
    helmut_wulf: {
        slug: "helmut_wulf",
        displayName: "Helmut Wulf",
        cost: 140000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: null,
        av: 9,
        skills: "chainsaw,loner-4,secret-weapon,pro,stand-firm",
        hirableBy: ["all"],
        imageUrl: undefined
    },
    hthark_the_unstoppable: {
        slug: "hthark_the_unstoppable",
        displayName: "H’thark the Unstoppable",
        cost: 300000,
        ma: 6,
        st: 6,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "block,thick-skull,defensive,sure-feet,break-tackle,juggernaut,sprint,loner-4",
        hirableBy: ["badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Fungus-the-Loon.webp"
    },
    ivan_the_animal_deathshroud: {
        slug: "ivan_the_animal_deathshroud",
        displayName: "Ivan ‘the Animal’ Deathshroud",
        cost: 190000,
        ma: 6,
        st: 4,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "block,juggernaut,disturbing-presence,sure-hands,regeneration,loner-4,tackle",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: undefined
    },
    ivar_eriksson: {
        slug: "ivar_eriksson",
        displayName: "Ivar Eriksson",
        cost: 245000,
        ma: 6,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,guard,loner-4,tackle",
        hirableBy: ["old_world_classic"],
        imageUrl: undefined
    },
    jeremiah_kool: {
        slug: "jeremiah_kool",
        displayName: "Jeremiah Kool",
        cost: 320000,
        ma: 8,
        st: 3,
        ag: 1,
        pa: 2,
        av: 9,
        skills: "block,dump-off,dodge,sidestep,nerves-of-steel,pass,diving-catch,loner-4,on-the-ball",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: undefined
    },
    jordell_freshbreeze: {
        slug: "jordell_freshbreeze",
        displayName: "Jordell Freshbreeze",
        cost: 250000,
        ma: 8,
        st: 3,
        ag: 1,
        pa: 3,
        av: 8,
        skills: "block,dodge,sidestep,diving-catch,leap,loner-4",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: undefined
    },
    karina_von_riesz: {
        slug: "karina_von_riesz",
        displayName: "Karina von Riesz",
        cost: 230000,
        ma: 7,
        st: 4,
        ag: 2,
        pa: 4,
        av: 9,
        skills: "bloodlust,dodge,hypnotic-gaze,jump-up,loner-4,regeneration",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: undefined
    },
    karla_von_kill: {
        slug: "karla_von_kill",
        displayName: "Karla Von Kill",
        cost: 210000,
        ma: 6,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "block,dauntless,dodge,jump-up,loner-4",
        hirableBy: ["lustrian_superleague", "old_world_classic"],
        imageUrl: undefined
    },
    kiroth_krakeneye: {
        slug: "kiroth_krakeneye",
        displayName: "Kiroth Krakeneye",
        cost: 170000,
        ma: 7,
        st: 3,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "disturbing-presence,foul-appearance,loner-4,on-the-ball,tackle,tentacles",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: "/data/Star-Players_files/Kiroth-Krakeneye.webp"
    },
    kreek_rustgouger: {
        slug: "kreek_rustgouger",
        displayName: "Kreek Rustgouger",
        cost: 170000,
        ma: 5,
        st: 7,
        ag: 4,
        pa: null,
        av: 10,
        skills: "ball-and-chain,loner-4,mighty-blow-1,no-hands,prehensile-tail,secret-weapon",
        hirableBy: ["underworld_challenge"],
        imageUrl: "/data/Star-Players_files/Kreek-Rustgouger.webp"
    },
    lord_borak_the_despoiler: {
        slug: "lord_borak_the_despoiler",
        displayName: "Lord Borak The Despoiler",
        cost: 260000,
        ma: 5,
        st: 5,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "block,mighty-blow-1,dirty-player-1,loner-4,sneaky-git",
        hirableBy: ["all"],
        imageUrl: "/data/Star-Players_files/Lord-borak.webp"
    },
    luthor_von_drakenborg: {
        slug: "luthor_von_drakenborg",
        displayName: "Luthor von Drakenborg",
        cost: 340000,
        ma: 6,
        st: 5,
        ag: 2,
        pa: 3,
        av: 10,
        skills: "block,hypnotic-gaze,loner-4,regeneration,sidestep",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: undefined
    },
    maple_highgrove: {
        slug: "maple_highgrove",
        displayName: "Maple Highgrove",
        cost: 210000,
        ma: 3,
        st: 5,
        ag: 5,
        pa: 5,
        av: 11,
        skills: "brawler,mighty-blow-1,thick-skull,grab,loner-4,stand-firm,tentacles",
        hirableBy: ["elven_kingdoms_league", "old_world_classic"],
        imageUrl: undefined
    },
    max_spleenripper: {
        slug: "max_spleenripper",
        displayName: "Max Spleenripper",
        cost: 130000,
        ma: 5,
        st: 4,
        ag: 4,
        pa: null,
        av: 9,
        skills: "chainsaw,loner-4,secret-weapon",
        hirableBy: ["all"],
        imageUrl: undefined
    },
    mighty_zug: {
        slug: "mighty_zug",
        displayName: "Mighty Zug",
        cost: 220000,
        ma: 4,
        st: 5,
        ag: 4,
        pa: 6,
        av: 10,
        skills: "loner-4,block,mighty-blow-1",
        hirableBy: ["lustrian_superleague", "old_world_classic"],
        imageUrl: undefined
    },
    prince_moranion: {
        slug: "prince_moranion",
        displayName: "Prince Moranion",
        cost: 230000,
        ma: 7,
        st: 4,
        ag: 2,
        pa: 3,
        av: 9,
        skills: "block,dauntless,wrestle,loner-4,tackle",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: undefined
    },
    morg_n_thorg: {
        slug: "morg_n_thorg",
        displayName: "Morg 'n' Thorg",
        cost: 380000,
        ma: 6,
        st: 6,
        ag: 3,
        pa: 4,
        av: 11,
        skills: "loner-4,block,mighty-blow-1,thick-skull,throw-team-mate",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: "/data/Star-Players_files/Morg-'n-Thorg.webp",
        specialRule: "La Baliste: Une fois par match, si Morg rate le test de Passe quand il effectue une Passe ou un Lancer de Coéquipier, vous pouvez relancer le D6."
    },
    nobbla_blackwart: {
        slug: "nobbla_blackwart",
        displayName: "Nobbla Blackwart",
        cost: 120000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: null,
        av: 8,
        skills: "secret-weapon,block,dodge,stunty,loner-4,chainsaw",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Nobbla-Blackwart-3rd-Edition.webp"
    },
    puggy_baconbreath: {
        slug: "puggy_baconbreath",
        displayName: "Puggy Baconbreath",
        cost: 120000,
        ma: 5,
        st: 3,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "dodge,titchy,nerves-of-steel,right-stuff,loner-4",
        hirableBy: ["old_world_classic"],
        imageUrl: "/data/Star-Players_files/Puggy_Baconbreath.webp"
    },
    rashnak_backstabber: {
        slug: "rashnak_backstabber",
        displayName: "Rashnak Backstabber",
        cost: 130000,
        ma: 7,
        st: 3,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "sidestep,sneaky-git,shadowing,stab,loner-4",
        hirableBy: ["badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Grashnak-Blackhoof.webp"
    },
    ripper_bolgrot: {
        slug: "ripper_bolgrot",
        displayName: "Ripper Bolgrot",
        cost: 250000,
        ma: 4,
        st: 6,
        ag: 5,
        pa: 4,
        av: 10,
        skills: "throw-team-mate,grab,regeneration,loner-4",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: undefined
    },
    rodney_roachbait: {
        slug: "rodney_roachbait",
        displayName: "Rodney Roachbait",
        cost: 70000,
        ma: 6,
        st: 2,
        ag: 3,
        pa: 4,
        av: 7,
        skills: "catch,diving-catch,jump-up,loner-4,on-the-ball,sidestep,stunty,wrestle",
        hirableBy: ["all"],
        imageUrl: undefined
    },
    rowana_forestfoot: {
        slug: "rowana_forestfoot",
        displayName: "Rowana ForestFoot",
        cost: 160000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: 4,
        av: 8,
        skills: "horns,dump-off,dodge,guard,jump-up,leap,loner-4",
        hirableBy: ["all"],
        imageUrl: undefined
    },
    roxanna_darknail: {
        slug: "roxanna_darknail",
        displayName: "Roxanna Darknail",
        cost: 270000,
        ma: 8,
        st: 3,
        ag: 1,
        pa: 4,
        av: 8,
        skills: "loner-4,dodge,frenzy,jump-up,juggernaut,leap",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: undefined
    },
    rumbelow_sheepskin: {
        slug: "rumbelow_sheepskin",
        displayName: "Rumbelow Sheepskin",
        cost: 170000,
        ma: 6,
        st: 3,
        ag: 3,
        pa: null,
        av: 8,
        skills: "block,horns,juggernaut,loner-4,no-hands,tackle,thick-skull",
        hirableBy: ["old_world_classic"],
        imageUrl: undefined
    },
    scrappa_sorehead: {
        slug: "scrappa_sorehead",
        displayName: "Scrappa Sorehead",
        cost: 130000,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 5,
        av: 8,
        skills: "pogo-stick,dodge,sure-feet,dirty-player-1,stunty,right-stuff,loner-4,sprint",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: undefined
    },
    scyla_anfingrimm: {
        slug: "scyla_anfingrimm",
        displayName: "Scyla Anfingrimm",
        cost: 200000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: null,
        av: 10,
        skills: "claws,frenzy,loner-4,mighty-blow-1,prehensile-tail,thick-skull,wild-animal",
        hirableBy: ["all"],
        imageUrl: "/data/Star-Players_files/Scyla-Anfingrimm.webp"
    },
    skitter_stab_stab: {
        slug: "skitter_stab_stab",
        displayName: "Skitter Stab-Stab",
        cost: 150000,
        ma: 9,
        st: 2,
        ag: 2,
        pa: 4,
        av: 8,
        skills: "dodge,stab,shadowing,prehensile-tail,loner-4",
        hirableBy: ["underworld_challenge"],
        imageUrl: "/data/Star-Players_files/Skitter-Stab-Stab-blood-bowl-star-player.webp"
    },
    skorg_snowpelt: {
        slug: "skorg_snowpelt",
        displayName: "Skorg Snowpelt",
        cost: 250000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: null,
        av: 9,
        skills: "mighty-blow-1,claws,juggernaut,disturbing-presence,loner-4",
        hirableBy: ["old_world_classic"],
        imageUrl: undefined
    },
    skrull_halfheight: {
        slug: "skrull_halfheight",
        displayName: "Skrull Halfheight",
        cost: 150000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "accurate,loner-4,nerves-of-steel,pass,regeneration,sure-hands,thick-skull",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: undefined
    },
    swiftvine_glimmershard: {
        slug: "swiftvine_glimmershard",
        displayName: "Swiftvine Glimmershard",
        cost: 110000,
        ma: 7,
        st: 2,
        ag: 3,
        pa: 5,
        av: 7,
        skills: "sidestep,stunty,fend,stab,disturbing-presence,loner-4",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: undefined
    },
    thorsson_stoutmead: {
        slug: "thorsson_stoutmead",
        displayName: "Thorsson Stoutmead",
        cost: 170000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 3,
        av: 8,
        skills: "block,thick-skull,drunkard,loner-4",
        hirableBy: ["old_world_classic"],
        imageUrl: undefined
    },
    varag_ghoul_chewer: {
        slug: "varag_ghoul_chewer",
        displayName: "Varag Ghoul-Chewer",
        cost: 280000,
        ma: 6,
        st: 5,
        ag: 3,
        pa: 5,
        av: 10,
        skills: "loner-4,block,jump-up,mighty-blow-1,thick-skull",
        hirableBy: ["underworld_challenge", "badlands_brawl"],
        imageUrl: undefined
    },
    wilhelm_chaney: {
        slug: "wilhelm_chaney",
        displayName: "Wilhelm Chaney",
        cost: 220000,
        ma: 8,
        st: 4,
        ag: 3,
        pa: 4,
        av: 9,
        skills: "catch,claws,frenzy,loner-4,regeneration,wrestle",
        hirableBy: ["sylvanian_spotlight"],
        imageUrl: "/data/Star-Players_files/Wilhelm-Chaney.webp"
    },
    willow_rosebark: {
        slug: "willow_rosebark",
        displayName: "Willow Rosebark",
        cost: 150000,
        ma: 5,
        st: 4,
        ag: 3,
        pa: 6,
        av: 9,
        skills: "dauntless,loner-4,sidestep,thick-skull",
        hirableBy: ["elven_kingdoms_league"],
        imageUrl: "/data/Star-Players_files/Willow-Rosebark.webp"
    },
    withergrasp_doubledrool: {
        slug: "withergrasp_doubledrool",
        displayName: "Withergrasp Doubledrool",
        cost: 170000,
        ma: 6,
        st: 3,
        ag: 4,
        pa: 4,
        av: 9,
        skills: "loner-4,prehensile-tail,tackle,tentacles,two-heads,wrestle,hypnotic-gaze",
        hirableBy: ["all"],
        imageUrl: "/data/Star-Players_files/star-player-whitergrasp-doubledrool.webp"
    },
    zolcath_the_zoat: {
        slug: "zolcath_the_zoat",
        displayName: "Zolcath the Zoat",
        cost: 230000,
        ma: 5,
        st: 5,
        ag: 4,
        pa: 5,
        av: 10,
        skills: "disturbing-presence,juggernaut,loner-4,mighty-blow-1,prehensile-tail,regeneration,sure-feet",
        hirableBy: ["lustrian_superleague", "elven_kingdoms_league"],
        imageUrl: "/data/Star-Players_files/Fungus-the-Loon.webp"
    },
    zzharg_madeye: {
        slug: "zzharg_madeye",
        displayName: "Zzharg Madeye",
        cost: 130000,
        ma: 4,
        st: 4,
        ag: 4,
        pa: 3,
        av: 10,
        skills: "nerves-of-steel,hail-mary-pass,loner-4,secret-weapon,cannoneer,sure-hands,thick-skull",
        hirableBy: ["badlands_brawl"],
        imageUrl: "/data/Star-Players_files/Zzharg-Madeye-star-player-blood-bowl.webp"
    },
};
/**
 * Obtenir un Star Player par son slug
 */
export function getStarPlayerBySlug(slug) {
    return STAR_PLAYERS[slug];
}
/**
 * Obtenir tous les Star Players disponibles pour une équipe donnée
 * @param teamRoster - Le roster de l'équipe (ex: "skaven")
 * @param teamRegionalRules - Les règles régionales de l'équipe (ex: ["underworld_challenge"])
 */
export function getAvailableStarPlayers(teamRoster, teamRegionalRules = []) {
    return Object.values(STAR_PLAYERS).filter(starPlayer => {
        // Si le Star Player est disponible pour tous
        if (starPlayer.hirableBy.includes("all")) {
            return true;
        }
        // Vérifier si l'équipe a une des règles régionales requises
        return starPlayer.hirableBy.some(rule => teamRegionalRules.includes(rule));
    });
}
/**
 * Mapping des équipes vers leurs règles régionales
 */
export const TEAM_REGIONAL_RULES = {
    skaven: ["underworld_challenge"],
    lizardmen: ["lustrian_superleague"],
    wood_elf: ["elven_kingdoms_league"],
    dark_elf: ["elven_kingdoms_league"],
    dwarf: ["old_world_classic", "worlds_edge_superleague"],
    goblin: ["badlands_brawl", "underworld_challenge"],
    undead: ["sylvanian_spotlight"],
    chaos_renegade: ["favoured_of"],
    ogre: ["badlands_brawl", "old_world_classic"],
    halfling: ["halfling_thimble_cup", "old_world_classic"],
    underworld: ["underworld_challenge"],
    chaos_chosen: ["favoured_of"],
    imperial_nobility: ["old_world_classic"],
    necromantic_horror: ["sylvanian_spotlight"],
    orc: ["badlands_brawl"],
    nurgle: ["favoured_of"],
    old_world_alliance: ["old_world_classic"],
    elven_union: ["elven_kingdoms_league"],
    human: ["old_world_classic"],
    black_orc: ["badlands_brawl"],
    snotling: ["underworld_challenge"],
    high_elf: ["elven_kingdoms_league"],
    norse: ["old_world_classic", "favoured_of"],
    amazon: ["lustrian_superleague"],
    vampire: ["sylvanian_spotlight"],
    tomb_kings: ["sylvanian_spotlight"],
    khorne: ["favoured_of"],
    chaos_dwarf: ["badlands_brawl", "worlds_edge_superleague", "favoured_of"],
    gnome: ["halfling_thimble_cup"],
};
