name: Docker Server
on:
  push:
    branches: [ main ]
    tags: [ "server-v*" ]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/server
jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -f apps/server/Dockerfile -t $IMAGE_NAME:sha-${GITHUB_SHA::7} .
      - name: Push image (sha tag)
        run: docker push $IMAGE_NAME:sha-${GITHUB_SHA::7}
      - name: Push image (latest on main)
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          docker tag $IMAGE_NAME:sha-${GITHUB_SHA::7} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
      - name: Push image (tagged release)
        if: startsWith(github.ref, 'refs/tags/server-v')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag $IMAGE_NAME:sha-${GITHUB_SHA::7} $IMAGE_NAME:${TAG}
          docker push $IMAGE_NAME:${TAG}
