name: PR Labeler
on:
  # Workflow temporairement désactivé
  # pull_request_target:
  #   types: [opened, synchronize, reopened]
  # Désactiver temporairement en utilisant un événement qui ne se produira jamais
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
